//----------------------------------------
//
// Copyright © yanghy. All Rights Reserved.
//
// Licensed under Apache License 2.0
//
//----------------------------------------

package cef

import (
	"github.com/energye/lcl/lcl"
	"github.com/energye/lcl/types"

	cefTypes "github.com/energye/cef/109/types"
)

type TConstrainedResizeEvent func(sender lcl.IObject, minWidth *types.TConstraintSize, minHeight *types.TConstraintSize, maxWidth *types.TConstraintSize, maxHeight *types.TConstraintSize)
type TContextPopupEvent func(sender lcl.IObject, mousePos types.TPoint, handled *bool)
type TDragDropEvent func(sender lcl.IObject, source lcl.IObject, X int32, Y int32)
type TDragOverEvent func(sender lcl.IObject, source lcl.IObject, X int32, Y int32, state types.TDragState, accept *bool)
type TEndDragEvent func(sender lcl.IObject, target lcl.IObject, X int32, Y int32)
type TGetSiteInfoEvent func(sender lcl.IObject, dockClient lcl.IControl, influenceRect *types.TRect, mousePos types.TPoint, canDock *bool)
type TMouseEvent func(sender lcl.IObject, button types.TMouseButton, shift types.TShiftState, X int32, Y int32)
type TMouseMoveEvent func(sender lcl.IObject, shift types.TShiftState, X int32, Y int32)
type TMouseWheelEvent func(sender lcl.IObject, shift types.TShiftState, wheelDelta int32, mousePos types.TPoint, handled *bool)
type TNotifyEvent func(sender lcl.IObject)
type TOnAcceleratedPaint func(sender lcl.IObject, browser ICefBrowser, type_ cefTypes.TCefPaintElementType, dirtyRectsCount cefTypes.NativeUInt, dirtyRects ICefRectArray, sharedHandle uintptr)
type TOnAcceleratorEvent func(sender lcl.IObject, window ICefWindow, commandId int32, result *bool)
type TOnAccessibilityAccessibilityLocationChangeEvent func(value ICefValue)
type TOnAccessibilityAccessibilityTreeChangeEvent func(value ICefValue)
type TOnAccessibilityEvent func(sender lcl.IObject, value ICefValue)
type TOnAddressChange func(sender lcl.IObject, browser ICefBrowser, frame ICefFrame, url string)
type TOnAfterCreated func(sender lcl.IObject, browser ICefBrowser)
type TOnAfterUserActionEvent func(sender lcl.IObject, textfield ICefTextfield)
type TOnAllowEvent func(sender lcl.IObject, allow *bool)
type TOnAppBeforeCommandLineProcessingEvent func(processType string, commandLine ICefCommandLine)
type TOnAppGetBrowserProcessHandlerEvent func(handler *IEngBrowserProcessHandler)
type TOnAppGetRenderProcessHandlerEvent func(handler *IEngRenderProcessHandler)
type TOnAppGetResourceBundleHandlerEvent func(handler *IEngResourceBundleHandler)
type TOnAppRegisterCustomSchemesEvent func(registrar ICefSchemeRegistrarRef)
type TOnAudioAudioStreamErrorEvent func(browser ICefBrowser, message string)
type TOnAudioAudioStreamPacketEvent func(browser ICefBrowser, data PPSingle, frames int32, pts int64)
type TOnAudioAudioStreamStartedEvent func(browser ICefBrowser, params TCefAudioParameters, channels int32)
type TOnAudioAudioStreamStoppedEvent func(browser ICefBrowser)
type TOnAudioGetAudioParametersEvent func(browser ICefBrowser, params *TCefAudioParameters, result *bool)
type TOnAudioStreamErrorEvent func(sender lcl.IObject, browser ICefBrowser, message string)
type TOnAudioStreamPacketEvent func(sender lcl.IObject, browser ICefBrowser, data PPSingle, frames int32, pts int64)
type TOnAudioStreamStartedEvent func(sender lcl.IObject, browser ICefBrowser, params TCefAudioParameters, channels int32)
type TOnAudioStreamStoppedEvent func(sender lcl.IObject, browser ICefBrowser)
type TOnAutoResize func(sender lcl.IObject, browser ICefBrowser, newSize TCefSize, outResult *bool)
type TOnBeforeBackgroundBrowserEvent func(sender lcl.IObject, extension ICefExtension, url string, client *IEngClient, settings *TCefBrowserSettings, result *bool)
type TOnBeforeBrowse func(sender lcl.IObject, browser ICefBrowser, frame ICefFrame, request ICefRequest, userGesture bool, isRedirect bool, outResult *bool)
type TOnBeforeBrowserEvent func(sender lcl.IObject, extension ICefExtension, browser ICefBrowser, activeBrowser ICefBrowser, index int32, url string, active bool, windowInfo *TCefWindowInfo, client *IEngClient, settings *TCefBrowserSettings, result *bool)
type TOnBeforeChildProcessLaunchEvent func(commandLine ICefCommandLine)
type TOnBeforeClose func(sender lcl.IObject, browser ICefBrowser)
type TOnBeforeContextMenu func(sender lcl.IObject, browser ICefBrowser, frame ICefFrame, params ICefContextMenuParams, model ICefMenuModel)
type TOnBeforeDownload func(sender lcl.IObject, browser ICefBrowser, downloadItem ICefDownloadItem, suggestedName string, callback ICefBeforeDownloadCallback)
type TOnBeforePopup func(sender lcl.IObject, browser ICefBrowser, frame ICefFrame, targetUrl string, targetFrameName string, targetDisposition cefTypes.TCefWindowOpenDisposition, userGesture bool, popupFeatures TCefPopupFeatures, windowInfo *TCefWindowInfo, client *IEngClient, settings *TCefBrowserSettings, extraInfo *ICefDictionaryValue, noJavascriptAccess *bool, result *bool)
type TOnBeforeResourceLoad func(sender lcl.IObject, browser ICefBrowser, frame ICefFrame, request ICefRequest, callback ICefCallback, outResult *cefTypes.TCefReturnValue)
type TOnBeforeUnloadDialog func(sender lcl.IObject, browser ICefBrowser, messageText string, isReload bool, callback ICefJsDialogCallback, outResult *bool)
type TOnBlurEvent func(sender lcl.IObject, view ICefView)
type TOnBrowserCreatedEvent func(browser ICefBrowser, extraInfo ICefDictionaryValue)
type TOnBrowserDestroyedEvent func(browser ICefBrowser)
type TOnBrowserProcessBeforeChildProcessLaunchEvent func(commandLine ICefCommandLine)
type TOnBrowserProcessContextInitializedEvent func()
type TOnBrowserProcessGetDefaultClientEvent func(client *IEngClient)
type TOnBrowserProcessRegisterCustomPreferencesEvent func(type_ cefTypes.TCefPreferencesType, registrar TCefPreferenceRegistrar)
type TOnBrowserProcessScheduleMessagePumpWorkEvent func(delayMs int64)
type TOnBrowserViewBrowserCreatedEvent func(browserView ICefBrowserView, browser ICefBrowser)
type TOnBrowserViewBrowserDestroyedEvent func(browserView ICefBrowserView, browser ICefBrowser)
type TOnBrowserViewGetChromeToolbarTypeEvent func() TCefChromeToolbarType
type TOnBrowserViewGetDelegateForPopupBrowserViewEvent func(browserView ICefBrowserView, settings TCefBrowserSettings, client IEngClient, isDevtools bool, result *IEngBrowserViewDelegate)
type TOnBrowserViewPopupBrowserViewCreatedEvent func(browserView ICefBrowserView, popupBrowserView ICefBrowserView, isDevtools bool, result *bool)
type TOnButtonButtonPressedEvent func(button ICefButton)
type TOnButtonButtonStateChangedEvent func(button ICefButton)
type TOnButtonPressedEvent func(sender lcl.IObject, button ICefButton)
type TOnButtonStateChangedEvent func(sender lcl.IObject, button ICefButton)
type TOnCanAccessBrowserEvent func(sender lcl.IObject, extension ICefExtension, browser ICefBrowser, includeIncognito bool, targetBrowser ICefBrowser, result *bool)
type TOnCanCloseEvent func(sender lcl.IObject, window ICefWindow, result *bool)
type TOnCanDownloadEvent func(sender lcl.IObject, browser ICefBrowser, url string, requestMethod string, result *bool)
type TOnCanMaximizeEvent func(sender lcl.IObject, window ICefWindow, result *bool)
type TOnCanMinimizeEvent func(sender lcl.IObject, window ICefWindow, result *bool)
type TOnCanResizeEvent func(sender lcl.IObject, window ICefWindow, result *bool)
type TOnCanSaveCookie func(sender lcl.IObject, browser ICefBrowser, frame ICefFrame, request ICefRequest, response ICefResponse, cookie TCefCookie, result *bool)
type TOnCanSendCookie func(sender lcl.IObject, browser ICefBrowser, frame ICefFrame, request ICefRequest, cookie TCefCookie, result *bool)
type TOnCertificateError func(sender lcl.IObject, browser ICefBrowser, certError cefTypes.TCefErrorCode, requestUrl string, sslInfo ICefSslInfo, callback ICefCallback, outResult *bool)
type TOnChildViewChangedEvent func(sender lcl.IObject, view ICefView, added bool, child ICefView)
type TOnChromeCommandEvent func(sender lcl.IObject, browser ICefBrowser, commandId int32, disposition cefTypes.TCefWindowOpenDisposition, result *bool)
type TOnClientConnected func(sender lcl.IObject, server ICefServer, connectionId int32)
type TOnClientDisconnected func(sender lcl.IObject, server ICefServer, connectionId int32)
type TOnClientGetAudioHandlerEvent func(handler *IEngAudioHandler)
type TOnClientGetCommandHandlerEvent func(handler *IEngCommandHandler)
type TOnClientGetContextMenuHandlerEvent func(handler *IEngContextMenuHandler)
type TOnClientGetDialogHandlerEvent func(handler *IEngDialogHandler)
type TOnClientGetDisplayHandlerEvent func(handler *IEngDisplayHandler)
type TOnClientGetDownloadHandlerEvent func(handler *IEngDownloadHandler)
type TOnClientGetDragHandlerEvent func(handler *IEngDragHandler)
type TOnClientGetFindHandlerEvent func(handler *IEngFindHandler)
type TOnClientGetFocusHandlerEvent func(handler *IEngFocusHandler)
type TOnClientGetFrameHandlerEvent func(handler *IEngFrameHandler)
type TOnClientGetJsdialogHandlerEvent func(handler *IEngJsDialogHandler)
type TOnClientGetKeyboardHandlerEvent func(handler *IEngKeyboardHandler)
type TOnClientGetLifeSpanHandlerEvent func(handler *IEngLifeSpanHandler)
type TOnClientGetLoadHandlerEvent func(handler *IEngLoadHandler)
type TOnClientGetPermissionHandlerEvent func(handler *IEngPermissionHandler)
type TOnClientGetPrintHandlerEvent func(handler *IEngPrintHandler)
type TOnClientGetRenderHandlerEvent func(handler *IEngRenderHandler)
type TOnClientGetRequestHandlerEvent func(handler *IEngRequestHandler)
type TOnClientProcessMessageReceivedEvent func(browser ICefBrowser, frame ICefFrame, sourceProcess cefTypes.TCefProcessId, message ICefProcessMessage) bool
type TOnClose func(sender lcl.IObject, browser ICefBrowser, action *cefTypes.TCefCloseBrowserAction)
type TOnCommandChromeCommandEvent func(browser ICefBrowser, commandId int32, disposition cefTypes.TCefWindowOpenDisposition) bool
type TOnCompMsgEvent func(sender lcl.IObject, message *types.TMessage, handled *bool)
type TOnCompletionCallbackCompleteEvent func()
type TOnConsoleMessage func(sender lcl.IObject, browser ICefBrowser, level cefTypes.TCefLogSeverity, message string, source string, line int32, outResult *bool)
type TOnContextCreatedEvent func(browser ICefBrowser, frame ICefFrame, context ICefv8Context)
type TOnContextInitializedEvent func()
type TOnContextMenuBeforeContextMenuEvent func(browser ICefBrowser, frame ICefFrame, params ICefContextMenuParams, model ICefMenuModel)
type TOnContextMenuCommand func(sender lcl.IObject, browser ICefBrowser, frame ICefFrame, params ICefContextMenuParams, commandId int32, eventFlags cefTypes.TCefEventFlags, outResult *bool)
type TOnContextMenuContextMenuCommandEvent func(browser ICefBrowser, frame ICefFrame, params ICefContextMenuParams, commandId int32, eventFlags cefTypes.TCefEventFlags) bool
type TOnContextMenuContextMenuDismissedEvent func(browser ICefBrowser, frame ICefFrame)
type TOnContextMenuDismissed func(sender lcl.IObject, browser ICefBrowser, frame ICefFrame)
type TOnContextMenuQuickMenuCommandEvent func(browser ICefBrowser, frame ICefFrame, commandId int32, eventFlags cefTypes.TCefEventFlags) bool
type TOnContextMenuQuickMenuDismissedEvent func(browser ICefBrowser, frame ICefFrame)
type TOnContextMenuRunContextMenuEvent func(browser ICefBrowser, frame ICefFrame, params ICefContextMenuParams, model ICefMenuModel, callback ICefRunContextMenuCallback) bool
type TOnContextMenuRunQuickMenuEvent func(browser ICefBrowser, frame ICefFrame, location TCefPoint, size TCefSize, editStateFlags cefTypes.TCefQuickMenuEditStateFlags, callback ICefRunQuickMenuCallback) bool
type TOnContextReleasedEvent func(browser ICefBrowser, frame ICefFrame, context ICefv8Context)
type TOnCookieAccessFilterCanSaveCookieEvent func(browser ICefBrowser, frame ICefFrame, request ICefRequest, response ICefResponse, cookie TCefCookie) bool
type TOnCookieAccessFilterCanSendCookieEvent func(browser ICefBrowser, frame ICefFrame, request ICefRequest, cookie TCefCookie) bool
type TOnCookieSet func(sender lcl.IObject, success bool, iD int32)
type TOnCookieVisitorDestroyed func(sender lcl.IObject, iD int32)
type TOnCookieVisitorVisitEvent func(name string, value string, domain string, path string, secure bool, httponly bool, hasExpires bool, creation types.TDateTime, lastAccess types.TDateTime, expires types.TDateTime, count int32, total int32, sameSite cefTypes.TCefCookieSameSite, priority cefTypes.TCefCookiePriority, outDeleteCookie *bool) bool
type TOnCookiesDeletedEvent func(sender lcl.IObject, numDeleted int32)
type TOnCookiesVisited func(sender lcl.IObject, name string, value string, domain string, path string, secure bool, httponly bool, hasExpires bool, creation types.TDateTime, lastAccess types.TDateTime, expires types.TDateTime, count int32, total int32, iD int32, sameSite cefTypes.TCefCookieSameSite, priority cefTypes.TCefCookiePriority, deleteCookie *bool, result *bool)
type TOnCursorChange func(sender lcl.IObject, browser ICefBrowser, cursor cefTypes.TCefCursorHandle, cursorType cefTypes.TCefCursorType, customCursorInfo TCefCursorInfo, result *bool)
type TOnDeleteCookiesCallbackCompleteEvent func(numDeleted int32)
type TOnDevToolsAgentAttachedEvent func(sender lcl.IObject, browser ICefBrowser)
type TOnDevToolsAgentDetachedEvent func(sender lcl.IObject, browser ICefBrowser)
type TOnDevToolsEventEvent func(sender lcl.IObject, browser ICefBrowser, method string, params ICefValue)
type TOnDevToolsEventRawEvent func(sender lcl.IObject, browser ICefBrowser, method string, params uintptr, paramsSize cefTypes.NativeUInt)
type TOnDevToolsMessageEvent func(sender lcl.IObject, browser ICefBrowser, message ICefValue, handled *bool)
type TOnDevToolsMessageObserverDevToolsAgentAttachedEvent func(browser ICefBrowser)
type TOnDevToolsMessageObserverDevToolsAgentDetachedEvent func(browser ICefBrowser)
type TOnDevToolsMessageObserverDevToolsEvent func(browser ICefBrowser, method string, params uintptr, paramsSize cefTypes.NativeUInt)
type TOnDevToolsMessageObserverDevToolsMessageEvent func(browser ICefBrowser, message uintptr, messageSize cefTypes.NativeUInt, handled *bool)
type TOnDevToolsMessageObserverDevToolsMethodResultEvent func(browser ICefBrowser, messageId int32, success bool, result uintptr, resultSize cefTypes.NativeUInt)
type TOnDevToolsMethodRawResultEvent func(sender lcl.IObject, browser ICefBrowser, messageId int32, success bool, result uintptr, resultSize cefTypes.NativeUInt)
type TOnDevToolsMethodResultEvent func(sender lcl.IObject, browser ICefBrowser, messageId int32, success bool, result ICefValue)
type TOnDevToolsRawMessageEvent func(sender lcl.IObject, browser ICefBrowser, message uintptr, messageSize cefTypes.NativeUInt, handled *bool)
type TOnDialogClosed func(sender lcl.IObject, browser ICefBrowser)
type TOnDialogFileDialogEvent func(browser ICefBrowser, mode cefTypes.TCefFileDialogMode, title string, defaultFilePath string, acceptFilters lcl.IStrings, callback ICefFileDialogCallback) bool
type TOnDismissPermissionPromptEvent func(sender lcl.IObject, browser ICefBrowser, promptId uint64, result cefTypes.TCefPermissionRequestResult)
type TOnDisplayAddressChangeEvent func(browser ICefBrowser, frame ICefFrame, url string)
type TOnDisplayAutoResizeEvent func(browser ICefBrowser, newSize TCefSize) bool
type TOnDisplayConsoleMessageEvent func(browser ICefBrowser, level cefTypes.TCefLogSeverity, message string, source string, line int32) bool
type TOnDisplayCursorChangeEvent func(browser ICefBrowser, cursor cefTypes.TCefCursorHandle, cursorType cefTypes.TCefCursorType, customCursorInfo TCefCursorInfo, result *bool)
type TOnDisplayFaviconUrlChangeEvent func(browser ICefBrowser, iconUrls lcl.IStrings)
type TOnDisplayFullScreenModeChangeEvent func(browser ICefBrowser, fullscreen bool)
type TOnDisplayLoadingProgressChangeEvent func(browser ICefBrowser, progress float64)
type TOnDisplayMediaAccessChangeEvent func(browser ICefBrowser, hasVideoAccess bool, hasAudioAccess bool)
type TOnDisplayStatusMessageEvent func(browser ICefBrowser, value string)
type TOnDisplayTitleChangeEvent func(browser ICefBrowser, title string)
type TOnDisplayTooltipEvent func(browser ICefBrowser, text *string) bool
type TOnDocumentAvailableInMainFrame func(sender lcl.IObject, browser ICefBrowser)
type TOnDomVisitorVisitEvent func(document ICefDomDocument)
type TOnDownloadBeforeDownloadEvent func(browser ICefBrowser, downloadItem ICefDownloadItem, suggestedName string, callback ICefBeforeDownloadCallback)
type TOnDownloadCanDownloadEvent func(browser ICefBrowser, url string, requestMethod string) bool
type TOnDownloadData func(sender lcl.IObject, request ICefUrlRequest, data uintptr, dataLength cefTypes.NativeUInt)
type TOnDownloadDownloadUpdatedEvent func(browser ICefBrowser, downloadItem ICefDownloadItem, callback ICefDownloadItemCallback)
type TOnDownloadImageCallbackDownloadImageFinishedEvent func(imageUrl string, httpStatusCode int32, image ICefImage)
type TOnDownloadImageFinishedEvent func(sender lcl.IObject, imageUrl string, httpStatusCode int32, image ICefImage)
type TOnDownloadProgress func(sender lcl.IObject, request ICefUrlRequest, current int64, total int64)
type TOnDownloadUpdated func(sender lcl.IObject, browser ICefBrowser, downloadItem ICefDownloadItem, callback ICefDownloadItemCallback)
type TOnDragDragEnterEvent func(browser ICefBrowser, dragData ICefDragData, mask cefTypes.TCefDragOperations) bool
type TOnDragDraggableRegionsChangedEvent func(browser ICefBrowser, frame ICefFrame, regionsCount cefTypes.NativeUInt, regions ICefDraggableRegionArray)
type TOnDragEnter func(sender lcl.IObject, browser ICefBrowser, dragData ICefDragData, mask cefTypes.TCefDragOperations, outResult *bool)
type TOnDraggableRegionsChanged func(sender lcl.IObject, browser ICefBrowser, frame ICefFrame, regionsCount cefTypes.NativeUInt, regions ICefDraggableRegionArray)
type TOnEndTracingCallbackEndTracingCompleteEvent func(tracingFile string)
type TOnExecuteTaskOnCefThread func(sender lcl.IObject, taskID uint32)
type TOnExtensionBeforeBackgroundBrowserEvent func(extension ICefExtension, url string, client *IEngClient, settings *TCefBrowserSettings) bool
type TOnExtensionBeforeBrowserEvent func(extension ICefExtension, browser ICefBrowser, activeBrowser ICefBrowser, index int32, url string, active bool, windowInfo *TCefWindowInfo, client *IEngClient, settings *TCefBrowserSettings) bool
type TOnExtensionCanAccessBrowserEvent func(extension ICefExtension, browser ICefBrowser, includeIncognito bool, targetBrowser ICefBrowser) bool
type TOnExtensionExtensionLoadFailedEvent func(result cefTypes.TCefErrorCode)
type TOnExtensionExtensionLoadedEvent func(extension ICefExtension)
type TOnExtensionExtensionUnloadedEvent func(extension ICefExtension)
type TOnExtensionGetActiveBrowserEvent func(extension ICefExtension, browser ICefBrowser, includeIncognito bool, rsltBrowser *ICefBrowser)
type TOnExtensionGetExtensionResourceEvent func(extension ICefExtension, browser ICefBrowser, file string, callback ICefGetExtensionResourceCallback) bool
type TOnExtensionLoadFailedEvent func(sender lcl.IObject, result cefTypes.TCefErrorCode)
type TOnExtensionLoadedEvent func(sender lcl.IObject, extension ICefExtension)
type TOnExtensionUnloadedEvent func(sender lcl.IObject, extension ICefExtension)
type TOnFavIconUrlChange func(sender lcl.IObject, browser ICefBrowser, iconUrls lcl.IStrings)
type TOnFileDialog func(sender lcl.IObject, browser ICefBrowser, mode cefTypes.TCefFileDialogMode, title string, defaultFilePath string, acceptFilters lcl.IStrings, callback ICefFileDialogCallback, result *bool)
type TOnFilterEvent func(sender lcl.IObject, dataIn uintptr, dataInSize cefTypes.NativeUInt, dataInRead *cefTypes.NativeUInt, dataOut uintptr, dataOutSize cefTypes.NativeUInt, dataOutWritten *cefTypes.NativeUInt, result *cefTypes.TCefResponseFilterStatus)
type TOnFindFindResultEvent func(browser ICefBrowser, identifier int32, count int32, selectionRect TCefRect, activeMatchOrdinal int32, finalUpdate bool)
type TOnFindResult func(sender lcl.IObject, browser ICefBrowser, identifier int32, count int32, selectionRect TCefRect, activeMatchOrdinal int32, finalUpdate bool)
type TOnFocusEvent func(sender lcl.IObject, view ICefView)
type TOnFocusGotFocusEvent func(browser ICefBrowser)
type TOnFocusSetFocusEvent func(browser ICefBrowser, source cefTypes.TCefFocusSource) bool
type TOnFocusTakeFocusEvent func(browser ICefBrowser, next bool)
type TOnFocusedNodeChangedEvent func(browser ICefBrowser, frame ICefFrame, node ICefDomNode)
type TOnFrameAttached func(sender lcl.IObject, browser ICefBrowser, frame ICefFrame, reattached bool)
type TOnFrameCreated func(sender lcl.IObject, browser ICefBrowser, frame ICefFrame)
type TOnFrameDetached func(sender lcl.IObject, browser ICefBrowser, frame ICefFrame)
type TOnFrameFrameAttachedEvent func(browser ICefBrowser, frame ICefFrame, reattached bool)
type TOnFrameFrameCreatedEvent func(browser ICefBrowser, frame ICefFrame)
type TOnFrameFrameDetachedEvent func(browser ICefBrowser, frame ICefFrame)
type TOnFrameMainFrameChangedEvent func(browser ICefBrowser, oldFrame ICefFrame, newFrame ICefFrame)
type TOnFullScreenModeChange func(sender lcl.IObject, browser ICefBrowser, fullscreen bool)
type TOnGetAccessibilityHandler func(sender lcl.IObject, accessibilityHandler *IEngAccessibilityHandler)
type TOnGetActiveBrowserEvent func(sender lcl.IObject, extension ICefExtension, browser ICefBrowser, includeIncognito bool, rsltBrowser *ICefBrowser)
type TOnGetAudioParametersEvent func(sender lcl.IObject, browser ICefBrowser, params *TCefAudioParameters, result *bool)
type TOnGetAuthCredentials func(sender lcl.IObject, browser ICefBrowser, originUrl string, isProxy bool, host string, port int32, realm string, scheme string, callback ICefAuthCallback, outResult *bool)
type TOnGetChromeToolbarTypeEvent func(sender lcl.IObject, chromeToolbarType *TCefChromeToolbarType)
type TOnGetDataResourceEvent func(resourceId int32, outData *uintptr, outDataSize *cefTypes.NativeUInt, result *bool)
type TOnGetDataResourceForScaleEvent func(resourceId int32, scaleFactor cefTypes.TCefScaleFactor, outData *uintptr, outDataSize *cefTypes.NativeUInt, result *bool)
type TOnGetDefaultClientEvent func(client *IEngClient)
type TOnGetDelegateForPopupBrowserViewEvent func(sender lcl.IObject, browserView ICefBrowserView, settings TCefBrowserSettings, client IEngClient, isDevtools bool, result *IEngBrowserViewDelegate)
type TOnGetExtensionResourceEvent func(sender lcl.IObject, extension ICefExtension, browser ICefBrowser, file string, callback ICefGetExtensionResourceCallback, result *bool)
type TOnGetHeightForWidthEvent func(sender lcl.IObject, view ICefView, width int32, result *int32)
type TOnGetInitialBoundsEvent func(sender lcl.IObject, window ICefWindow, result *TCefRect)
type TOnGetInitialShowStateEvent func(sender lcl.IObject, window ICefWindow, result *cefTypes.TCefShowState)
type TOnGetLocalizedStringEvent func(stringId int32, outStringVal *string, result *bool)
type TOnGetMaximumSizeEvent func(sender lcl.IObject, view ICefView, result *TCefSize)
type TOnGetMinimumSizeEvent func(sender lcl.IObject, view ICefView, result *TCefSize)
type TOnGetPDFPaperSizeEvent func(sender lcl.IObject, browser ICefBrowser, deviceUnitsPerInch int32, result *TCefSize)
type TOnGetParentWindowEvent func(sender lcl.IObject, window ICefWindow, isMenu *bool, canActivateMenu *bool, result *ICefWindow)
type TOnGetPreferredSizeEvent func(sender lcl.IObject, view ICefView, result *TCefSize)
type TOnGetResourceHandler func(sender lcl.IObject, browser ICefBrowser, frame ICefFrame, request ICefRequest, resourceHandler *IEngResourceHandler)
type TOnGetResourceRequestHandler func(sender lcl.IObject, browser ICefBrowser, frame ICefFrame, request ICefRequest, isNavigation bool, isDownload bool, requestInitiator string, disableDefaultHandling *bool, externalResourceRequestHandler *IEngResourceRequestHandler)
type TOnGetResourceResponseFilter func(sender lcl.IObject, browser ICefBrowser, frame ICefFrame, request ICefRequest, response ICefResponse, outResult *IEngResponseFilter)
type TOnGetRootScreenRect func(sender lcl.IObject, browser ICefBrowser, rect *TCefRect, outResult *bool)
type TOnGetScreenInfo func(sender lcl.IObject, browser ICefBrowser, screenInfo *TCefScreenInfo, outResult *bool)
type TOnGetScreenPoint func(sender lcl.IObject, browser ICefBrowser, viewX int32, viewY int32, screenX *int32, screenY *int32, outResult *bool)
type TOnGetTouchHandleSize func(sender lcl.IObject, browser ICefBrowser, orientation cefTypes.TCefHorizontalAlignment, size *TCefSize)
type TOnGetViewRect func(sender lcl.IObject, browser ICefBrowser, rect *TCefRect)
type TOnGotFocus func(sender lcl.IObject, browser ICefBrowser)
type TOnHandledMessageEvent func(sender lcl.IObject, message *types.TMessage, handled *bool)
type TOnHttpRequest func(sender lcl.IObject, server ICefServer, connectionId int32, clientAddress string, request ICefRequest)
type TOnIMECommitTextEvent func(sender lcl.IObject, text string, replacementRange TCefRange, relativeCursorPos int32)
type TOnIMECompositionRangeChanged func(sender lcl.IObject, browser ICefBrowser, selectedRange TCefRange, characterBoundsCount cefTypes.NativeUInt, characterBounds TCefRect)
type TOnIMESetCompositionEvent func(sender lcl.IObject, text string, underlines ICefCompositionUnderlineArray, replacementRange TCefRange, selectionRange TCefRange)
type TOnInitFilterEvent func(sender lcl.IObject, result *bool)
type TOnIsFramelessEvent func(sender lcl.IObject, window ICefWindow, result *bool)
type TOnJsDialogBeforeUnloadDialogEvent func(browser ICefBrowser, messageText string, isReload bool, callback ICefJsDialogCallback) bool
type TOnJsDialogDialogClosedEvent func(browser ICefBrowser)
type TOnJsDialogJsdialogEvent func(browser ICefBrowser, originUrl string, dialogType cefTypes.TCefJsDialogType, messageText string, defaultPromptText string, callback ICefJsDialogCallback, outSuppressMessage *bool) bool
type TOnJsDialogResetDialogStateEvent func(browser ICefBrowser)
type TOnJsdialog func(sender lcl.IObject, browser ICefBrowser, originUrl string, dialogType cefTypes.TCefJsDialogType, messageText string, defaultPromptText string, callback ICefJsDialogCallback, outSuppressMessage *bool, outResult *bool)
type TOnKeyEvent func(sender lcl.IObject, browser ICefBrowser, event TCefKeyEvent, osEvent cefTypes.TCefEventHandle, outResult *bool)
type TOnKeyboardKeyEvent func(browser ICefBrowser, event TCefKeyEvent, osEvent cefTypes.TCefEventHandle) bool
type TOnKeyboardPreKeyEvent func(browser ICefBrowser, event TCefKeyEvent, osEvent cefTypes.TCefEventHandle, outIsKeyboardShortcut *bool) bool
type TOnLayoutChangedEvent func(sender lcl.IObject, view ICefView, newBounds TCefRect)
type TOnLifeSpanAfterCreatedEvent func(browser ICefBrowser)
type TOnLifeSpanBeforeCloseEvent func(browser ICefBrowser)
type TOnLifeSpanBeforePopupEvent func(browser ICefBrowser, frame ICefFrame, targetUrl string, targetFrameName string, targetDisposition cefTypes.TCefWindowOpenDisposition, userGesture bool, popupFeatures TCefPopupFeatures, windowInfo *TCefWindowInfo, client *IEngClient, settings *TCefBrowserSettings, extraInfo *ICefDictionaryValue, noJavascriptAccess *bool) bool
type TOnLifeSpanDoCloseEvent func(browser ICefBrowser) bool
type TOnLoadEnd func(sender lcl.IObject, browser ICefBrowser, frame ICefFrame, httpStatusCode int32)
type TOnLoadError func(sender lcl.IObject, browser ICefBrowser, frame ICefFrame, errorCode cefTypes.TCefErrorCode, errorText string, failedUrl string)
type TOnLoadLoadEndEvent func(browser ICefBrowser, frame ICefFrame, httpStatusCode int32)
type TOnLoadLoadErrorEvent func(browser ICefBrowser, frame ICefFrame, errorCode cefTypes.TCefErrorCode, errorText string, failedUrl string)
type TOnLoadLoadStartEvent func(browser ICefBrowser, frame ICefFrame, transitionType cefTypes.TCefTransitionType)
type TOnLoadLoadingStateChangeEvent func(browser ICefBrowser, isLoading bool, canGoBack bool, canGoForward bool)
type TOnLoadStart func(sender lcl.IObject, browser ICefBrowser, frame ICefFrame, transitionType cefTypes.TCefTransitionType)
type TOnLoadingProgressChange func(sender lcl.IObject, browser ICefBrowser, progress float64)
type TOnLoadingStateChange func(sender lcl.IObject, browser ICefBrowser, isLoading bool, canGoBack bool, canGoForward bool)
type TOnMainFrameChanged func(sender lcl.IObject, browser ICefBrowser, oldFrame ICefFrame, newFrame ICefFrame)
type TOnMediaAccessChange func(sender lcl.IObject, browser ICefBrowser, hasVideoAccess bool, hasAudioAccess bool)
type TOnMediaAccessRequestMediaAccessPermissionEvent func(browser ICefBrowser, frame ICefFrame, requestingUrl string, requestedPermissions cefTypes.TCefMediaAccessPermissionTypes, callback ICefMediaAccessCallback) bool
type TOnMediaObserverRouteMessageReceivedEvent func(route ICefMediaRoute, message string)
type TOnMediaObserverRouteStateChangedEvent func(route ICefMediaRoute, state cefTypes.TCefMediaRouteConnectionState)
type TOnMediaObserverRoutesEvent func(routes ICefMediaRouteArray)
type TOnMediaObserverSinksEvent func(sinks ICefMediaSinkArray)
type TOnMediaRouteCreateCallbackMediaRouteCreateFinishedEvent func(result cefTypes.TCefMediaRouterCreateResult, error_ string, route ICefMediaRoute)
type TOnMediaRouteCreateFinishedEvent func(sender lcl.IObject, result cefTypes.TCefMediaRouterCreateResult, error_ string, route ICefMediaRoute)
type TOnMediaSinkDeviceInfoCallbackMediaSinkDeviceInfoEvent func(ipAddress string, port int32, modelName string)
type TOnMediaSinkDeviceInfoEvent func(sender lcl.IObject, ipAddress string, port int32, modelName string)
type TOnMenuButtonMenuButtonPressedEvent func(menuButton ICefMenuButton, screenPoint TCefPoint, buttonPressedLock ICefMenuButtonPressedLock)
type TOnMenuButtonPressedEvent func(sender lcl.IObject, menuButton ICefMenuButton, screenPoint TCefPoint, buttonPressedLock ICefMenuButtonPressedLock)
type TOnMenuModelExecuteCommandEvent func(menuModel ICefMenuModel, commandId int32, eventFlags cefTypes.TCefEventFlags)
type TOnMenuModelFormatLabelEvent func(menuModel ICefMenuModel, label *string) bool
type TOnMenuModelMenuClosedEvent func(menuModel ICefMenuModel)
type TOnMenuModelMenuWillShowEvent func(menuModel ICefMenuModel)
type TOnMenuModelMouseOutsideMenuEvent func(menuModel ICefMenuModel, screenPoint TCefPoint)
type TOnMenuModelUnhandledCloseSubmenuEvent func(menuModel ICefMenuModel, isRTL bool)
type TOnMenuModelUnhandledOpenSubmenuEvent func(menuModel ICefMenuModel, isRTL bool)
type TOnNavigationEntryVisitorVisitEvent func(entry ICefNavigationEntry, current bool, index int32, total int32) bool
type TOnNavigationVisitorResultAvailableEvent func(sender lcl.IObject, entry ICefNavigationEntry, current bool, index int32, total int32, result *bool)
type TOnOpenUrlFromTab func(sender lcl.IObject, browser ICefBrowser, frame ICefFrame, targetUrl string, targetDisposition cefTypes.TCefWindowOpenDisposition, userGesture bool, outResult *bool)
type TOnPaint func(sender lcl.IObject, browser ICefBrowser, type_ cefTypes.TCefPaintElementType, dirtyRectsCount cefTypes.NativeUInt, dirtyRects ICefRectArray, buffer uintptr, width int32, height int32)
type TOnParentViewChangedEvent func(sender lcl.IObject, view ICefView, added bool, parent ICefView)
type TOnPdfPrintCallbackPdfPrintFinishedEvent func(path string, ok bool)
type TOnPdfPrintFinishedEvent func(sender lcl.IObject, resultOK bool)
type TOnPermissionDismissPermissionPromptEvent func(browser ICefBrowser, promptId uint64, result cefTypes.TCefPermissionRequestResult)
type TOnPermissionRequestMediaAccessPermissionEvent func(browser ICefBrowser, frame ICefFrame, requestingOrigin string, requestedPermissions uint32, callback ICefMediaAccessCallback) bool
type TOnPermissionShowPermissionPromptEvent func(browser ICefBrowser, promptId uint64, requestingOrigin string, requestedPermissions uint32, callback ICefPermissionPromptCallback) bool
type TOnPopupBrowserViewCreatedEvent func(sender lcl.IObject, browserView ICefBrowserView, popupBrowserView ICefBrowserView, isDevtools bool, result *bool)
type TOnPopupShow func(sender lcl.IObject, browser ICefBrowser, show bool)
type TOnPopupSize func(sender lcl.IObject, browser ICefBrowser, rect TCefRect)
type TOnPreKeyEvent func(sender lcl.IObject, browser ICefBrowser, event TCefKeyEvent, osEvent cefTypes.TCefEventHandle, outIsKeyboardShortcut *bool, outResult *bool)
type TOnPrefsAvailableEvent func(sender lcl.IObject, resultOK bool)
type TOnPrintDialogEvent func(sender lcl.IObject, browser ICefBrowser, hasSelection bool, callback ICefPrintDialogCallback, result *bool)
type TOnPrintGetPDFPaperSizeEvent func(browser ICefBrowser, deviceUnitsPerInch int32, result *TCefSize)
type TOnPrintJobEvent func(sender lcl.IObject, browser ICefBrowser, documentName string, pDFFilePath string, callback ICefPrintJobCallback, result *bool)
type TOnPrintPrintDialogEvent func(browser ICefBrowser, hasSelection bool, callback ICefPrintDialogCallback, result *bool)
type TOnPrintPrintJobEvent func(browser ICefBrowser, documentName string, pDFFilePath string, callback ICefPrintJobCallback, result *bool)
type TOnPrintPrintResetEvent func(browser ICefBrowser)
type TOnPrintPrintSettingsEvent func(browser ICefBrowser, settings ICefPrintSettings, getDefaults bool)
type TOnPrintPrintStartEvent func(browser ICefBrowser)
type TOnPrintResetEvent func(sender lcl.IObject, browser ICefBrowser)
type TOnPrintSettingsEvent func(sender lcl.IObject, browser ICefBrowser, settings ICefPrintSettings, getDefaults bool)
type TOnPrintStartEvent func(sender lcl.IObject, browser ICefBrowser)
type TOnProcessMessageReceived func(sender lcl.IObject, browser ICefBrowser, frame ICefFrame, sourceProcess cefTypes.TCefProcessId, message ICefProcessMessage, outResult *bool)
type TOnProcessMessageReceivedEvent func(browser ICefBrowser, frame ICefFrame, sourceProcess cefTypes.TCefProcessId, message ICefProcessMessage, handled *bool)
type TOnProtocolExecution func(sender lcl.IObject, browser ICefBrowser, frame ICefFrame, request ICefRequest, allowOsExecution *bool)
type TOnQuickMenuCommandEvent func(sender lcl.IObject, browser ICefBrowser, frame ICefFrame, commandId int32, eventFlags cefTypes.TCefEventFlags, result *bool)
type TOnQuickMenuDismissedEvent func(sender lcl.IObject, browser ICefBrowser, frame ICefFrame)
type TOnRegisterCustomPreferencesEvent func(type_ cefTypes.TCefPreferencesType, registrar ICefPreferenceRegistrarRef)
type TOnRegisterCustomSchemesEvent func(registrar ICefSchemeRegistrarRef)
type TOnRenderAcceleratedPaintEvent func(browser ICefBrowser, kind cefTypes.TCefPaintElementType, dirtyRectsCount cefTypes.NativeUInt, dirtyRects ICefRectArray, sharedHandle uintptr)
type TOnRenderGetAccessibilityHandlerEvent func(accessibilityHandler *IEngAccessibilityHandler)
type TOnRenderGetRootScreenRectEvent func(browser ICefBrowser, rect *TCefRect) bool
type TOnRenderGetScreenInfoEvent func(browser ICefBrowser, screenInfo *TCefScreenInfo) bool
type TOnRenderGetScreenPointEvent func(browser ICefBrowser, viewX int32, viewY int32, screenX *int32, screenY *int32) bool
type TOnRenderGetTouchHandleSizeEvent func(browser ICefBrowser, orientation cefTypes.TCefHorizontalAlignment, size *TCefSize)
type TOnRenderGetViewRectEvent func(browser ICefBrowser, rect *TCefRect)
type TOnRenderIMECompositionRangeChangedEvent func(browser ICefBrowser, selectedRange TCefRange, characterBoundsCount cefTypes.NativeUInt, characterBounds TCefRect)
type TOnRenderLoadEnd func(browser ICefBrowser, frame ICefFrame, httpStatusCode int32)
type TOnRenderLoadError func(browser ICefBrowser, frame ICefFrame, errorCode cefTypes.TCefErrorCode, errorText string, failedUrl string)
type TOnRenderLoadStart func(browser ICefBrowser, frame ICefFrame, transitionType cefTypes.TCefTransitionType)
type TOnRenderLoadingStateChange func(browser ICefBrowser, isLoading bool, canGoBack bool, canGoForward bool)
type TOnRenderPaintEvent func(browser ICefBrowser, kind cefTypes.TCefPaintElementType, dirtyRectsCount cefTypes.NativeUInt, dirtyRects ICefRectArray, buffer uintptr, width int32, height int32)
type TOnRenderPopupShowEvent func(browser ICefBrowser, show bool)
type TOnRenderPopupSizeEvent func(browser ICefBrowser, rect TCefRect)
type TOnRenderProcessBrowserCreatedEvent func(browser ICefBrowser, extraInfo ICefDictionaryValue)
type TOnRenderProcessBrowserDestroyedEvent func(browser ICefBrowser)
type TOnRenderProcessContextCreatedEvent func(browser ICefBrowser, frame ICefFrame, context ICefv8Context)
type TOnRenderProcessContextReleasedEvent func(browser ICefBrowser, frame ICefFrame, context ICefv8Context)
type TOnRenderProcessFocusedNodeChangedEvent func(browser ICefBrowser, frame ICefFrame, node ICefDomNode)
type TOnRenderProcessGetLoadHandlerEvent func() IEngLoadHandler
type TOnRenderProcessProcessMessageReceivedEvent func(browser ICefBrowser, frame ICefFrame, sourceProcess cefTypes.TCefProcessId, message ICefProcessMessage) bool
type TOnRenderProcessTerminated func(sender lcl.IObject, browser ICefBrowser, status cefTypes.TCefTerminationStatus)
type TOnRenderProcessUncaughtExceptionEvent func(browser ICefBrowser, frame ICefFrame, context ICefv8Context, v8Exception ICefV8Exception, stackTrace ICefV8StackTrace)
type TOnRenderProcessWebKitInitializedEvent func()
type TOnRenderScrollOffsetChangedEvent func(browser ICefBrowser, X float64, Y float64)
type TOnRenderStartDraggingEvent func(browser ICefBrowser, dragData ICefDragData, allowedOps cefTypes.TCefDragOperations, X int32, Y int32) bool
type TOnRenderTextSelectionChangedEvent func(browser ICefBrowser, selectedText string, selectedRange TCefRange)
type TOnRenderTouchHandleStateChangedEvent func(browser ICefBrowser, state TCefTouchHandleState)
type TOnRenderUpdateDragCursorEvent func(browser ICefBrowser, operation cefTypes.TCefDragOperation)
type TOnRenderViewReady func(sender lcl.IObject, browser ICefBrowser)
type TOnRenderVirtualKeyboardRequestedEvent func(browser ICefBrowser, inputMode cefTypes.TCefTextInpuMode)
type TOnRequestBeforeBrowseEvent func(browser ICefBrowser, frame ICefFrame, request ICefRequest, userGesture bool, isRedirect bool) bool
type TOnRequestCertificateErrorEvent func(browser ICefBrowser, certError cefTypes.TCefErrorCode, requestUrl string, sslInfo ICefSslInfo, callback ICefCallback) bool
type TOnRequestComplete func(sender lcl.IObject, request ICefUrlRequest)
type TOnRequestContextGetResourceRequestHandlerEvent func(browser ICefBrowser, frame ICefFrame, request ICefRequest, isNavigation bool, isDownload bool, requestInitiator string, disableDefaultHandling *bool, resourceRequestHandler *IEngResourceRequestHandler)
type TOnRequestContextInitialized func(sender lcl.IObject, requestContext ICefRequestContext)
type TOnRequestContextRequestContextInitializedEvent func(requestContext ICefRequestContext)
type TOnRequestDocumentAvailableInMainFrameEvent func(browser ICefBrowser)
type TOnRequestGetAuthCredentialsEvent func(browser ICefBrowser, originUrl string, isProxy bool, host string, port int32, realm string, scheme string, callback ICefAuthCallback) bool
type TOnRequestGetResourceRequestHandlerEvent func(browser ICefBrowser, frame ICefFrame, request ICefRequest, isNavigation bool, isDownload bool, requestInitiator string, disableDefaultHandling *bool, resourceRequestHandler *IEngResourceRequestHandler)
type TOnRequestMediaAccessPermissionEvent func(sender lcl.IObject, browser ICefBrowser, frame ICefFrame, requestingOrigin string, requestedPermissions uint32, callback ICefMediaAccessCallback, result *bool)
type TOnRequestOpenUrlFromTabEvent func(browser ICefBrowser, frame ICefFrame, targetUrl string, targetDisposition cefTypes.TCefWindowOpenDisposition, userGesture bool) bool
type TOnRequestRenderProcessTerminatedEvent func(browser ICefBrowser, status cefTypes.TCefTerminationStatus)
type TOnRequestRenderViewReadyEvent func(browser ICefBrowser)
type TOnRequestSelectClientCertificateEvent func(browser ICefBrowser, isProxy bool, host string, port int32, certificatesCount cefTypes.NativeUInt, certificates ICefX509CertificateArray, callback ICefSelectClientCertificateCallback) bool
type TOnResetDialogState func(sender lcl.IObject, browser ICefBrowser)
type TOnResolveCallbackResolveCompletedEvent func(result cefTypes.TCefErrorCode, resolvedIps lcl.IStrings)
type TOnResolvedIPsAvailableEvent func(sender lcl.IObject, result cefTypes.TCefErrorCode, resolvedIps lcl.IStrings)
type TOnResourceBundleGetDataResourceEvent func(resourceId int32, data *uintptr, dataSize *cefTypes.NativeUInt) bool
type TOnResourceBundleGetDataResourceForScaleEvent func(resourceId int32, scaleFactor cefTypes.TCefScaleFactor, data *uintptr, dataSize *cefTypes.NativeUInt) bool
type TOnResourceBundleGetLocalizedStringEvent func(stringid int32, stringVal *string) bool
type TOnResourceCancelEvent func()
type TOnResourceGetResponseHeadersEvent func(response ICefResponse, outResponseLength *int64, outRedirectUrl *string)
type TOnResourceLoadComplete func(sender lcl.IObject, browser ICefBrowser, frame ICefFrame, request ICefRequest, response ICefResponse, status cefTypes.TCefUrlRequestStatus, receivedContentLength int64)
type TOnResourceOpenEvent func(request ICefRequest, handleRequest *bool, callback ICefCallback) bool
type TOnResourceProcessRequestEvent func(request ICefRequest, callback ICefCallback) bool
type TOnResourceReadEvent func(dataOut uintptr, bytesToRead int32, bytesRead *int32, callback ICefResourceReadCallback) bool
type TOnResourceReadResponseEvent func(dataOut uintptr, bytesToRead int32, bytesRead *int32, callback ICefCallback) bool
type TOnResourceRedirect func(sender lcl.IObject, browser ICefBrowser, frame ICefFrame, request ICefRequest, response ICefResponse, newUrl *string)
type TOnResourceRequestBeforeResourceLoadEvent func(browser ICefBrowser, frame ICefFrame, request ICefRequest, callback ICefCallback) cefTypes.TCefReturnValue
type TOnResourceRequestGetCookieAccessFilterEvent func(browser ICefBrowser, frame ICefFrame, request ICefRequest, filter *IEngCookieAccessFilter)
type TOnResourceRequestGetResourceHandlerEvent func(browser ICefBrowser, frame ICefFrame, request ICefRequest, resourceHandler *IEngResourceHandler)
type TOnResourceRequestGetResourceResponseFilterEvent func(browser ICefBrowser, frame ICefFrame, request ICefRequest, response ICefResponse, responseFilter *IEngResponseFilter)
type TOnResourceRequestProtocolExecutionEvent func(browser ICefBrowser, frame ICefFrame, request ICefRequest, allowOsExecution *bool)
type TOnResourceRequestResourceLoadCompleteEvent func(browser ICefBrowser, frame ICefFrame, request ICefRequest, response ICefResponse, status cefTypes.TCefUrlRequestStatus, receivedContentLength int64)
type TOnResourceRequestResourceRedirectEvent func(browser ICefBrowser, frame ICefFrame, request ICefRequest, response ICefResponse, newUrl *string)
type TOnResourceRequestResourceResponseEvent func(browser ICefBrowser, frame ICefFrame, request ICefRequest, response ICefResponse) bool
type TOnResourceResponse func(sender lcl.IObject, browser ICefBrowser, frame ICefFrame, request ICefRequest, response ICefResponse, outResult *bool)
type TOnResourceSkipEvent func(bytesToSkip int64, bytesSkipped *int64, callback ICefResourceSkipCallback) bool
type TOnResponseFilterFilterEvent func(dataIn uintptr, dataInSize cefTypes.NativeUInt, dataInRead *cefTypes.NativeUInt, dataOut uintptr, dataOutSize cefTypes.NativeUInt, dataOutWritten *cefTypes.NativeUInt) cefTypes.TCefResponseFilterStatus
type TOnResponseFilterInitFilterEvent func() bool
type TOnRouteMessageReceivedEvent func(sender lcl.IObject, route ICefMediaRoute, message string)
type TOnRouteStateChangedEvent func(sender lcl.IObject, route ICefMediaRoute, state cefTypes.TCefMediaRouteConnectionState)
type TOnRoutesEvent func(sender lcl.IObject, routes ICefMediaRouteArray)
type TOnRunContextMenu func(sender lcl.IObject, browser ICefBrowser, frame ICefFrame, params ICefContextMenuParams, model ICefMenuModel, callback ICefRunContextMenuCallback, result *bool)
type TOnRunFileDialogCallbackFileDialogDismissedEvent func(filePaths lcl.IStrings)
type TOnRunQuickMenuEvent func(sender lcl.IObject, browser ICefBrowser, frame ICefFrame, location TCefPoint, size TCefSize, editStateFlags cefTypes.TCefQuickMenuEditStateFlags, callback ICefRunQuickMenuCallback, result *bool)
type TOnScheduleMessagePumpWorkEvent func(delayMs int64)
type TOnSchemeFactoryNewEvent func(browser ICefBrowser, frame ICefFrame, schemeName string, request ICefRequest) IEngResourceHandler
type TOnScrollOffsetChanged func(sender lcl.IObject, browser ICefBrowser, X float64, Y float64)
type TOnSelectClientCertificate func(sender lcl.IObject, browser ICefBrowser, isProxy bool, host string, port int32, certificatesCount cefTypes.NativeUInt, certificates ICefX509CertificateArray, callback ICefSelectClientCertificateCallback, result *bool)
type TOnServerClientConnectedEvent func(server ICefServer, connectionId int32)
type TOnServerClientDisconnectedEvent func(server ICefServer, connectionId int32)
type TOnServerCreated func(sender lcl.IObject, server ICefServer)
type TOnServerDestroyed func(sender lcl.IObject, server ICefServer)
type TOnServerHttpRequestEvent func(server ICefServer, connectionId int32, clientAddress string, request ICefRequest)
type TOnServerServerCreatedEvent func(server ICefServer)
type TOnServerServerDestroyedEvent func(server ICefServer)
type TOnServerWebSocketConnectedEvent func(server ICefServer, connectionId int32)
type TOnServerWebSocketMessageEvent func(server ICefServer, connectionId int32, data uintptr, dataSize cefTypes.NativeUInt)
type TOnServerWebSocketRequestEvent func(server ICefServer, connectionId int32, clientAddress string, request ICefRequest, callback ICefCallback)
type TOnSetCookieCallbackCompleteEvent func(success bool)
type TOnSetFocus func(sender lcl.IObject, browser ICefBrowser, source cefTypes.TCefFocusSource, outResult *bool)
type TOnShowPermissionPromptEvent func(sender lcl.IObject, browser ICefBrowser, promptId uint64, requestingOrigin string, requestedPermissions uint32, callback ICefPermissionPromptCallback, result *bool)
type TOnSinksEvent func(sender lcl.IObject, sinks ICefMediaSinkArray)
type TOnStartDragging func(sender lcl.IObject, browser ICefBrowser, dragData ICefDragData, allowedOps cefTypes.TCefDragOperations, X int32, Y int32, outResult *bool)
type TOnStatusMessage func(sender lcl.IObject, browser ICefBrowser, value string)
type TOnStringVisitorVisitEvent func(str string)
type TOnTakeFocus func(sender lcl.IObject, browser ICefBrowser, next bool)
type TOnTaskExecuteEvent func()
type TOnTextResultAvailableEvent func(sender lcl.IObject, text string)
type TOnTextSelectionChanged func(sender lcl.IObject, browser ICefBrowser, selectedText string, selectedRange TCefRange)
type TOnTextfieldAfterUserActionEvent func(textfield ICefTextfield)
type TOnTextfieldKeyEvent func(textfield ICefTextfield, event TCefKeyEvent, result *bool)
type TOnTextfieldKeyEventEvent func(sender lcl.IObject, textfield ICefTextfield, event TCefKeyEvent, result *bool)
type TOnTitleChange func(sender lcl.IObject, browser ICefBrowser, title string)
type TOnTooltip func(sender lcl.IObject, browser ICefBrowser, text *string, outResult *bool)
type TOnTouchHandleStateChanged func(sender lcl.IObject, browser ICefBrowser, state TCefTouchHandleState)
type TOnUncaughtExceptionEvent func(browser ICefBrowser, frame ICefFrame, context ICefv8Context, exception ICefV8Exception, stackTrace ICefV8StackTrace)
type TOnUpdateDragCursor func(sender lcl.IObject, browser ICefBrowser, operation cefTypes.TCefDragOperation)
type TOnUploadProgress func(sender lcl.IObject, request ICefUrlRequest, current int64, total int64)
type TOnUrlrequestClientDownloadDataEvent func(request ICefUrlRequest, data uintptr, dataLength cefTypes.NativeUInt)
type TOnUrlrequestClientDownloadProgressEvent func(request ICefUrlRequest, current int64, total int64)
type TOnUrlrequestClientGetAuthCredentialsEvent func(isProxy bool, host string, port int32, realm string, scheme string, callback ICefAuthCallback) bool
type TOnUrlrequestClientRequestCompleteEvent func(request ICefUrlRequest)
type TOnUrlrequestClientUploadProgressEvent func(request ICefUrlRequest, current int64, total int64)
type TOnV8AccessorGetEvent func(name string, object ICefv8Value, retval *ICefv8Value, exception *string) bool
type TOnV8AccessorSet_Event func(name string, object ICefv8Value, value ICefv8Value, exception *string) bool
type TOnV8ArrayBufferReleaseCallbackReleaseBufferEvent func(buffer uintptr)
type TOnV8ExecuteEvent func(name string, object ICefv8Value, arguments ICefv8ValueArray, retval *ICefv8Value, exception *string) bool
type TOnV8InterceptorGetByIndexEvent func(index int32, object ICefv8Value, retval *ICefv8Value, exception *string) bool
type TOnV8InterceptorGetByNameEvent func(name string, object ICefv8Value, retval *ICefv8Value, exception *string) bool
type TOnV8InterceptorSetByIndexEvent func(index int32, object ICefv8Value, value ICefv8Value, exception *string) bool
type TOnV8InterceptorSetByNameEvent func(name string, object ICefv8Value, value ICefv8Value, exception *string) bool
type TOnViewBlurEvent func(view ICefView)
type TOnViewChildViewChangedEvent func(view ICefView, added bool, child ICefView)
type TOnViewFocusEvent func(view ICefView)
type TOnViewGetHeightForWidthEvent func(view ICefView, width int32, result *int32)
type TOnViewGetMaximumSizeEvent func(view ICefView, result *TCefSize)
type TOnViewGetMinimumSizeEvent func(view ICefView, result *TCefSize)
type TOnViewGetPreferredSizeEvent func(view ICefView, result *TCefSize)
type TOnViewLayoutChangedEvent func(view ICefView, newBounds TCefRect)
type TOnViewParentViewChangedEvent func(view ICefView, added bool, parent ICefView)
type TOnViewWindowChangedEvent func(view ICefView, added bool)
type TOnVirtualKeyboardRequested func(sender lcl.IObject, browser ICefBrowser, inputMode cefTypes.TCefTextInpuMode)
type TOnWebKitInitializedEvent func()
type TOnWebSocketConnected func(sender lcl.IObject, server ICefServer, connectionId int32)
type TOnWebSocketMessage func(sender lcl.IObject, server ICefServer, connectionId int32, data uintptr, dataSize cefTypes.NativeUInt)
type TOnWebSocketRequest func(sender lcl.IObject, server ICefServer, connectionId int32, clientAddress string, request ICefRequest, callback ICefCallback)
type TOnWindowAcceleratorEvent func(window ICefWindow, commandId int32, result *bool)
type TOnWindowActivationChangedEvent func(sender lcl.IObject, window ICefWindow, active bool)
type TOnWindowBoundsChangedEvent func(sender lcl.IObject, window ICefWindow, newBounds TCefRect)
type TOnWindowCanCloseEvent func(window ICefWindow, result *bool)
type TOnWindowCanMaximizeEvent func(window ICefWindow, result *bool)
type TOnWindowCanMinimizeEvent func(window ICefWindow, result *bool)
type TOnWindowCanResizeEvent func(window ICefWindow, result *bool)
type TOnWindowChangedEvent func(sender lcl.IObject, view ICefView, added bool)
type TOnWindowClosingEvent func(sender lcl.IObject, window ICefWindow)
type TOnWindowCreatedEvent func(sender lcl.IObject, window ICefWindow)
type TOnWindowDestroyedEvent func(sender lcl.IObject, window ICefWindow)
type TOnWindowGetInitialBoundsEvent func(window ICefWindow, result *TCefRect)
type TOnWindowGetInitialShowStateEvent func(window ICefWindow, result *cefTypes.TCefShowState)
type TOnWindowGetParentWindowEvent func(window ICefWindow, isMenu *bool, canActivateMenu *bool, result *ICefWindow)
type TOnWindowIsFramelessEvent func(window ICefWindow, result *bool)
type TOnWindowKeyEvent func(window ICefWindow, event TCefKeyEvent, result *bool)
type TOnWindowKeyEventEvent func(sender lcl.IObject, window ICefWindow, event TCefKeyEvent, result *bool)
type TOnWindowWindowActivationChangedEvent func(window ICefWindow, active bool)
type TOnWindowWindowBoundsChangedEvent func(window ICefWindow, newBounds TCefRect)
type TOnWindowWindowClosingEvent func(window ICefWindow)
type TOnWindowWindowCreatedEvent func(window ICefWindow)
type TOnWindowWindowDestroyedEvent func(window ICefWindow)
type TOnWriteEllEvent func() int64
type TOnWriteFlushEvent func() int32
type TOnWriteMayBlockEvent func() bool
type TOnWriteSeekEvent func(offset int64, whence int32) int32
type TOnWriteWriteEvent func(ptr uintptr, size cefTypes.NativeUInt, N cefTypes.NativeUInt) cefTypes.NativeUInt
type TOnZoomPctAvailable func(sender lcl.IObject, zoomPct float64)
type TStartDockEvent func(sender lcl.IObject, dragObject *lcl.IDragDockObject)
type TStartDragEvent func(sender lcl.IObject, dragObject *lcl.IDragObject)
