// Code generated by cefgen. DO NOT EDIT.
//
//----------------------------------------
//
// Copyright © yanghy. All Rights Reserved.
//
// Licensed under Apache License 2.0
//
//----------------------------------------

package cef

import cefbase "github.com/energye/cef/base"

func Init() {
	cefbase.Init()
}
