// Code generated by cefgen. DO NOT EDIT.
//
//----------------------------------------
//
// Copyright © yanghy. All Rights Reserved.
//
// Licensed under Apache License 2.0
//
//----------------------------------------

//go:build CEF109 || (!CEF127 && !CEF147)

package cef

import (
	cefTypes "github.com/energye/cef/cef/types"
	"github.com/energye/lcl/lcl"
	"github.com/energye/lcl/types"
)

type ICEFPanelComponent_109 interface {
	ICEFPanelComponent
	GetChildViewCount() cefTypes.NativeUInt
}

type ICEFTextfieldComponent_109 interface {
	ICEFTextfieldComponent
	SelectRange(range_ TCefRange)
}

type ICEFWindowComponent_109 interface {
	ICEFWindowComponent
	ICEFPanelComponent_109
	AddOverlayView(view ICefView, dockingMode cefTypes.TCefDockingMode) ICefOverlayController
	SetAccelerator(commandId int32, keyCode int32, shiftPressed bool, ctrlPressed bool, altPressed bool)
}

type ICefApplication_109 interface {
	ICefApplication
	ICefApplicationCore_109
}

type ICefApplicationCore_109 interface {
	ICefApplicationCore
	AfterConstruction()
	ApiHashUniversal() string
	ChromeRuntime() bool
	DisableSafeBrowsing() bool
	EnableHighDPISupport() bool
	FastUnload() bool
	InternalGetDataResourceForScale(resourceId int32, scaleFactor cefTypes.TCefScaleFactor, data *uintptr, dataSize *cefTypes.NativeUInt) bool
	InternalGetDataResource(resourceId int32, data *uintptr, dataSize *cefTypes.NativeUInt) bool
	InternalGetDefaultClient(client *IEngClient)
	InternalGetLocalizedString(stringId int32, stringVal *string) bool
	InternalOnBeforeChildProcessLaunch(commandLine ICefCommandLine)
	// InternalOnBeforeCommandLineProcessing
	// Internal procedures. Only ICefApp, ICefBrowserProcessHandler,
	// ICefResourceBundleHandler, ICefRenderProcessHandler, ICefRegisterCDMCallback and
	// ICefLoadHandler should use them.
	InternalOnBeforeCommandLineProcessing(processType string, commandLine ICefCommandLine)
	InternalOnBrowserCreated(browser ICefBrowser, extraInfo ICefDictionaryValue)
	InternalOnBrowserDestroyed(browser ICefBrowser)
	InternalOnContextCreated(browser ICefBrowser, frame ICefFrame, context ICefv8Context)
	InternalOnContextInitialized()
	InternalOnContextReleased(browser ICefBrowser, frame ICefFrame, context ICefv8Context)
	InternalOnFocusedNodeChanged(browser ICefBrowser, frame ICefFrame, node ICefDomNode)
	InternalOnLoadEnd(browser ICefBrowser, frame ICefFrame, httpStatusCode int32)
	InternalOnLoadError(browser ICefBrowser, frame ICefFrame, errorCode int32, errorText string, failedUrl string)
	InternalOnLoadStart(browser ICefBrowser, frame ICefFrame, transitionType cefTypes.TCefTransitionType)
	InternalOnLoadingStateChange(browser ICefBrowser, isLoading bool, canGoBack bool, canGoForward bool)
	InternalOnProcessMessageReceived(browser ICefBrowser, frame ICefFrame, sourceProcess cefTypes.TCefProcessId, message ICefProcessMessage, handled *bool)
	InternalOnRegisterCustomPreferences(type_ cefTypes.TCefPreferencesType, registrar ICefPreferenceRegistrarRef)
	InternalOnRegisterCustomSchemes(registrar ICefSchemeRegistrarRef)
	InternalOnScheduleMessagePumpWork(delayMs int64)
	InternalOnUncaughtException(browser ICefBrowser, frame ICefFrame, context ICefv8Context, exception ICefV8Exception, stackTrace ICefV8StackTrace)
	InternalOnWebKitInitialized()
	PackLoadingDisabled() bool
	PersistUserPreferences() bool
	SetChromeRuntime(value bool)
	SetDisableSafeBrowsing(value bool)
	SetEnableHighDPISupport(value bool)
	SetFastUnload(value bool)
	SetPackLoadingDisabled(value bool)
	SetPersistUserPreferences(value bool)
	SetUserDataPath(value string)
	UserDataPath() string
}

type ICefBrowser_109 interface {
	ICefBrowser
	GetFrameByident(identifier int64) ICefFrame
	GetFrameIdentifiers(frameCount *cefTypes.NativeUInt, frameIdentifierArray *ICefFrameIdentifierArray) bool
	GetFrame(name string) ICefFrame
}

type ICefBrowserHost_109 interface {
	ICefBrowserHost
	GetExtension() ICefExtension_109
	IsBackgroundHost() bool
}

type ICefBrowserHostRef_109 interface {
	ICefBrowserHostRef
	ICefBrowserHost_109
}

type ICefBrowserRef_109 interface {
	ICefBrowserRef
	ICefBrowser_109
}

type ICefCustomStringList_109 interface {
	ICefCustomStringList
	ICefStringList_109
}

type ICefDomNode_109 interface {
	ICefDomNode
	GetFormControlElementType() string
}

type ICefDomNodeRef_109 interface {
	ICefDomNodeRef
	ICefDomNode_109
}

type ICefDownLoadItemRef_109 interface {
	ICefBaseRefCountedRef
	ICefDownloadItem
	AsIntfDownloadItem() uintptr
}

type ICefExtension_109 interface {
	ICefBaseRefCounted
	GetBackgroundPage() string
	GetBrowserActionIcon() string
	GetBrowserActionPopup() string
	GetHandler() IEngExtensionHandler_109
	GetIdentifier() string
	GetLoaderContext() ICefRequestContext
	GetManifest() ICefDictionaryValue
	GetOptionsPage() string
	GetOptionsUIPage() string
	GetPageActionIcon() string
	GetPageActionPopup() string
	GetPath() string
	GetURL() string
	IsLoaded() bool
	IsSame(that ICefExtension_109) bool
	Unload()
}

type ICefExtensionHandler_109 interface {
	ICefBaseRefCounted
}

type ICefExtensionHandlerOwn_109 interface {
	ICefBaseRefCountedOwn
	ICefExtensionHandler_109
}

type ICefExtensionRef_109 interface {
	ICefBaseRefCountedRef
	ICefExtension_109
	AsIntfExtension() uintptr
}

type ICefGenericTask_109 interface {
	ICefGenericTask
	ICefTaskOwn
}

type ICefGetExtensionResourceCallback_109 interface {
	ICefBaseRefCounted
	Cancel()
	Cont(stream ICefStreamReader)
}

type ICefGetExtensionResourceCallbackRef_109 interface {
	ICefBaseRefCountedRef
	ICefGetExtensionResourceCallback_109
	AsIntfGetExtensionResourceCallback() uintptr
}

type ICefMediaAccessHandler_109 interface {
	ICefBaseRefCounted
}

type ICefMediaAccessHandlerOwn_109 interface {
	ICefBaseRefCountedOwn
	ICefMediaAccessHandler_109
}

type ICefMediaSink_109 interface {
	ICefMediaSink
	GetDescription() string
}

type ICefMediaSinkRef_109 interface {
	ICefMediaSinkRef
	ICefMediaSink_109
}

type ICefRequestContext_109 interface {
	ICefRequestContext
	DidLoadExtension(extensionId string) bool
	GetExtensions(extensionIds lcl.IStringList) bool
	GetExtension(extensionId string) ICefExtension_109
	HasExtension(extensionId string) bool
	LoadExtension(rootDirectory string, manifest ICefDictionaryValue, handler IEngExtensionHandler_109)
}

type ICefRequestContextRef_109 interface {
	ICefRequestContextRef
	ICefRequestContext_109
}

type ICefStringList_109 interface {
	ICefStringList
	GetHandle() cefTypes.TCefStringMap
}

type ICefStringListOwn_109 interface {
	ICefStringListOwn
	ICefCustomStringList_109
}

type ICefStringListRef_109 interface {
	ICefStringListRef
	ICefCustomStringList_109
}

type ICefWindow_109 interface {
	ICefWindow
	AddOverlayView(view ICefView, dockingMode cefTypes.TCefDockingMode) ICefOverlayController
	SetAccelerator(commandId int32, keyCode int32, shiftPressed bool, ctrlPressed bool, altPressed bool)
}

type ICefWindowRef_109 interface {
	ICefWindowRef
	ICefWindow_109
}

type ICefX509CertPrincipal_109 interface {
	ICefX509CertPrincipal
	GetDomainComponents(components lcl.IStrings)
	GetStreetAddresses(addresses lcl.IStrings)
}

type ICefX509CertPrincipalRef_109 interface {
	ICefX509CertPrincipalRef
	ICefX509CertPrincipal_109
}

type ICefv8Value_109 interface {
	ICefv8Value
	GetUserData() ICefv8Value
	SetUserData(data ICefv8Value) bool
	SetValueByAccessor(key string, settings cefTypes.TCefV8AccessControls, attribute cefTypes.TCefV8PropertyAttributes) bool
}

type ICefv8ValueRef_109 interface {
	ICefv8ValueRef
	ICefv8Value_109
}

type IChromium_109 interface {
	IChromium
	IChromiumCore_109
}

type IChromiumCore_109 interface {
	IChromiumCore
	AcceptLanguageList() string
	BatterySaverModeState() cefTypes.TCefBatterySaverModeState
	CreateUrlRequestWithRequestUClientInt64(request ICefRequest, client IEngUrlrequestClient, frameIdentifier int64) ICefUrlRequest
	CreateUrlRequestWithRequestUClientStr(request ICefRequest, client IEngUrlrequestClient, frameName string) ICefUrlRequest
	DidLoadExtension(extensionId string) bool
	ExecuteJavaScriptWithStrX2Int64Int(code string, scriptURL string, frameIdentifier int64, startLine int32)
	ExecuteJavaScriptWithStrX3Int(code string, scriptURL string, frameName string, startLine int32)
	ExtensionHandler() IEngExtensionHandler_109
	GetExtensions(extensionIds lcl.IStringList) bool
	GetExtension(extensionId string) ICefExtension_109
	GetFrameIdentifiers(frameCount *cefTypes.NativeUInt, frameIdentifierArray *ICefFrameIdentifierArray) bool
	HasExtension(extensionId string) bool
	HighEfficiencyMode() cefTypes.TCefState
	// LoadExtension
	// ICefRequestContext methods for extensions
	LoadExtension(rootDirectory string, manifest ICefDictionaryValue, handler IEngExtensionHandler_109, requestContext ICefRequestContext) bool
	LoadResourceWithCMStreamStrX2Int64(stream lcl.ICustomMemoryStream, mimeType string, charset string, frameIdentifier int64)
	LoadResourceWithCMStreamStrX3(stream lcl.ICustomMemoryStream, mimeType string, charset string, frameName string)
	LoadStringWithStrInt64(hTML string, frameIdentifier int64)
	LoadStringWithStrX2(hTML string, frameName string)
	LoadURLWithStrInt64(uRL string, frameIdentifier int64)
	LoadURLWithStrX2(uRL string, frameName string)
	RetrieveHTMLWithInt64(frameIdentifier int64)
	RetrieveHTMLWithStr(frameName string)
	RetrieveTextWithInt64(frameIdentifier int64)
	RetrieveTextWithStr(frameName string)
	SendProcessMessageWithPIdPMessageInt64(targetProcess cefTypes.TCefProcessId, procMessage ICefProcessMessage, frameIdentifier int64)
	SendProcessMessageWithPIdPMessageStr(targetProcess cefTypes.TCefProcessId, procMessage ICefProcessMessage, frameName string)
	SetAcceptLanguageList(value string)
	SetBatterySaverModeState(value cefTypes.TCefBatterySaverModeState)
	SetHighEfficiencyMode(value cefTypes.TCefState)
	SetOnExtensionBeforeBackgroundBrowser(fn TOnBeforeBackgroundBrowserEvent)
	SetOnExtensionBeforeBrowser(fn TOnBeforeBrowserEvent)
	SetOnExtensionCanAccessBrowser(fn TOnCanAccessBrowserEvent)
	SetOnExtensionGetActiveBrowser(fn TOnGetActiveBrowserEvent)
	SetOnExtensionGetExtensionResource(fn TOnGetExtensionResourceEvent)
	SetOnExtensionLoadFailed(fn TOnExtensionLoadFailedEvent)
	SetOnExtensionLoaded(fn TOnExtensionLoadedEvent)
	SetOnExtensionUnloaded(fn TOnExtensionUnloadedEvent)
	SetOnWidgetCompMsg(fn TOnCompMsgEvent)
	WidgetHandle() types.THandle
}

type IChromiumOptions_109 interface {
	IChromiumOptions
	AcceptLanguageList() string
	SetAcceptLanguageList(value string)
}

type IChromiumWindow_109 interface {
	IChromiumWindow
	SetUseSetFocus(value bool)
	UseSetFocus() bool
}

type IEngExtensionHandler_109 interface {
	ICefExtensionHandlerOwn_109
	AsIntfExtensionHandler() uintptr
	SetOnExtensionBeforeBackgroundBrowser(fn TOnExtensionBeforeBackgroundBrowserEvent)
	SetOnExtensionBeforeBrowser(fn TOnExtensionBeforeBrowserEvent)
	SetOnExtensionCanAccessBrowser(fn TOnExtensionCanAccessBrowserEvent)
	SetOnExtensionExtensionLoadFailed(fn TOnExtensionExtensionLoadFailedEvent)
	SetOnExtensionExtensionLoaded(fn TOnExtensionExtensionLoadedEvent)
	SetOnExtensionExtensionUnloaded(fn TOnExtensionExtensionUnloadedEvent)
	SetOnExtensionGetActiveBrowser(fn TOnExtensionGetActiveBrowserEvent)
	SetOnExtensionGetExtensionResource(fn TOnExtensionGetExtensionResourceEvent)
}

type IEngMediaAccessHandler_109 interface {
	ICefMediaAccessHandlerOwn_109
	AsIntfMediaAccessHandler() uintptr
	SetOnMediaAccessRequestMediaAccessPermission(fn TOnMediaAccessRequestMediaAccessPermissionEvent)
}
