// Code generated by cefgen. DO NOT EDIT.
//
//----------------------------------------
//
// Copyright © yanghy. All Rights Reserved.
//
// Licensed under Apache License 2.0
//
//----------------------------------------

//go:build CEF147

package cef

import (
	cefTypes "github.com/energye/cef/cef/types"
	"github.com/energye/lcl/lcl"
)

type IApplicationCoreEvents_147 interface {
	IObject
}

type ICEFBrowserViewComponent_147 interface {
	ICEFBrowserViewComponent
	ICEFViewComponent_147
	// ChromeToolbar
	// Returns the Chrome toolbar associated with this BrowserView. Only
	// supported when using Chrome style. The ICefBrowserViewDelegate.GetChromeToolbarType
	// function must return a value other than
	// CEF_CTT_NONE and the toolbar will not be available until after this
	// BrowserView is added to a ICefWindow and
	// ICefViewDelegate.OnWindowChanged() has been called.
	ChromeToolbar() ICefView
	// RuntimeStyle
	// Returns the runtime style for this BrowserView (ALLOY or CHROME). See
	// TCefRuntimeStyle documentation for details.
	RuntimeStyle() cefTypes.TCefRuntimeStyle
	SetOnAllowMoveForPictureInPicture(fn TOnAllowMoveForPictureInPictureEvent)
	SetOnAllowPictureInPictureWithoutUserActivation(fn TOnAllowPictureInPictureWithoutUserActivationEvent)
	SetOnGestureCommand(fn TOnGestureCommandEvent)
	SetOnGetBrowserRuntimeStyle(fn TOnGetBrowserRuntimeStyleEvent)
	SetOnUseFramelessWindowForPictureInPicture(fn TOnUseFramelessWindowForPictureInPicture)
}

type ICEFButtonComponent_147 interface {
	ICEFButtonComponent
	ICEFViewComponent_147
}

type ICEFFileDialogInfo_147 interface {
	ICEFFileDialogInfo
	SetAcceptDescriptions(value lcl.IStrings)
	SetAcceptExtensions(value lcl.IStrings)
}

type ICEFLabelButtonComponent_147 interface {
	ICEFLabelButtonComponent
	ICEFButtonComponent_147
}

type ICEFLinkedWinControlBase_147 interface {
	ICEFLinkedWinControlBase
	SetUseSetFocus(value bool)
	// UseSetFocus
	// Use TChromium.SetFocus when the component receives a WM_SETFOCUS message in Windows.
	UseSetFocus() bool
}

type ICEFLinkedWindowParent_147 interface {
	ICEFLinkedWindowParent
	ICEFLinkedWinControlBase_147
}

type ICEFMenuButtonComponent_147 interface {
	ICEFMenuButtonComponent
	ICEFLabelButtonComponent_147
}

type ICEFPanelComponent_147 interface {
	ICEFPanelComponent
	ICEFViewComponent_147
	// ChildViewCount
	// Returns the number of child Views.
	ChildViewCount() cefTypes.NativeUInt
}

type ICEFProxySettings_147 interface {
	IObject
	AutoDetect() bool
	ByPassList() string
	NoProxyServer() bool
	PacUrl() string
	Server() string
	SetAutoDetect(value bool)
	SetByPassList(value string)
	SetNoProxyServer(value bool)
	SetPacUrl(value string)
	SetServer(value string)
}

type ICEFScrollViewComponent_147 interface {
	ICEFScrollViewComponent
	ICEFViewComponent_147
}

type ICEFTextfieldComponent_147 interface {
	ICEFTextfieldComponent
	ICEFViewComponent_147
	// CursorPosition
	// Returns the current cursor position.
	CursorPosition() cefTypes.NativeUInt
	// SelectedRange
	// Returns the selected logical text range.
	SelectedRange() TCefRange
	SetSelectedRange(value TCefRange)
}

type ICEFViewComponent_147 interface {
	ICEFViewComponent
	// GetThemeColor
	// Returns the current theme color associated with |color_id|, or the
	// placeholder color (red) if unset. See cef_color_ids.h for standard ID
	// values. Standard colors can be overridden and custom colors can be added
	// using ICefWindow.SetThemeColor.
	GetThemeColor(colorId int32) cefTypes.TCefColor
	// HasFocus
	// Returns true (1) if this View has focus in the context of the containing
	// Window. Check both this function and ICefWindow.IsActive to determine
	// global keyboard focus.
	HasFocus() bool
	// Insets
	// Returns the insets for this View in parent coordinates, or DIP screen
	// coordinates if there is no parent.
	Insets() TCefInsets
	SetInsets(value TCefInsets)
	SetOnThemeChanged(fn TOnThemeChangedEvent)
}

type ICEFWindowComponent_147 interface {
	ICEFWindowComponent
	ICEFPanelComponent_147
	// AddOverlayView
	// Add a View that will be overlayed on the Window contents with absolute
	// positioning and high z-order. Positioning is controlled by |docking_mode|
	// as described below. Setting |can_activate| to true (1) will allow the
	// overlay view to receive input focus. The returned cef_overlay_controller_t
	// object is used to control the overlay. Overlays are hidden by default.
	// With CEF_DOCKING_MODE_CUSTOM:
	// <code>
	// 1. The overlay is initially hidden, sized to |view|'s preferred size,
	// and positioned in the top-left corner.
	// 2. Optionally change the overlay position and/or size by calling
	// CefOverlayController methods.
	// 3. Call CefOverlayController::SetVisible(true) to show the overlay.
	// 4. The overlay will be automatically re-sized if |view|'s layout
	// changes. Optionally change the overlay position and/or size when
	// OnLayoutChanged is called on the Window's delegate to indicate a
	// change in Window bounds.</code>
	// With other docking modes:
	// <code>
	// 1. The overlay is initially hidden, sized to |view|'s preferred size,
	// and positioned based on |docking_mode|.
	// 2. Call CefOverlayController::SetVisible(true) to show the overlay.
	// 3. The overlay will be automatically re-sized if |view|'s layout changes
	// and re-positioned as appropriate when the Window resizes.</code>
	// Overlays created by this function will receive a higher z-order then any
	// child Views added previously. It is therefore recommended to call this
	// function last after all other child Views have been added so that the
	// overlay displays as the top-most child of the Window.
	AddOverlayView(view ICefView, dockingMode cefTypes.TCefDockingMode, canActivate bool) ICefOverlayController
	// FocusedView
	// Returns the View that currently has focus in this Window, or nullptr if no
	// View currently has focus. A Window may have a focused View even if it is
	// not currently active. Any focus changes while a Window is not active may
	// be applied after that Window next becomes active.
	FocusedView() ICefView
	// RuntimeStyle
	// Returns the runtime style for this Window (ALLOY or CHROME). See
	// TCefRuntimeStyle documentation for details.
	RuntimeStyle() cefTypes.TCefRuntimeStyle
	// SetAccelerator
	// Set the keyboard accelerator for the specified |command_id|. |key_code|
	// can be any virtual key or character value. Required modifier keys are
	// specified by |shift_pressed|, |ctrl_pressed| and/or |alt_pressed|.
	// ICefWindowDelegate.OnAccelerator will be called if the keyboard
	// combination is triggered while this window has focus.
	// The |high_priority| value will be considered if a child ICefBrowserView
	// has focus when the keyboard combination is triggered. If |high_priority|
	// is true (1) then the key event will not be forwarded to the web content
	// (`keydown` event handler) or ICefKeyboardHandler first. If
	// |high_priority| is false (0) then the behavior will depend on the
	// ICefBrowserView.SetPreferAccelerators configuration.
	SetAccelerator(commandId int32, keyCode int32, shiftPressed bool, ctrlPressed bool, altPressed bool, highPriority bool)
	SetOnAcceptsFirstMouse(fn TOnAcceptsFirstMouseEvent)
	SetOnGetLinuxWindowProperties(fn TOnGetLinuxWindowPropertiesEvent)
	SetOnGetTitlebarHeight(fn TOnGetTitlebarHeightEvent)
	SetOnGetWindowRuntimeStyle(fn TOnGetWindowRuntimeStyleEvent)
	SetOnIsWindowModalDialog(fn TOnIsWindowModalDialogEvent)
	SetOnThemeColorsChanged(fn TOnThemeColorsChangedEvent)
	SetOnWindowFullscreenTransition(fn TOnWindowFullscreenTransitionEvent)
	SetOnWithStandardWindowButtons(fn TOnWithStandardWindowButtonsEvent)
	// SetThemeColor
	// Override a standard theme color or add a custom color associated with
	// |color_id|. See cef_color_ids.h for standard ID values. Recommended usage
	// is as follows:
	// <code>
	// 1. Customize the default native/OS theme by calling SetThemeColor before
	// showing the first Window. When done setting colors call
	// ICefWindow.ThemeChanged to trigger ICefViewDelegate.OnThemeChanged
	// notifications.
	// 2. Customize the current native/OS or Chrome theme after it changes by
	// calling SetThemeColor from the ICefWindowDelegate.OnThemeColorsChanged
	// callback. ICefViewDelegate.OnThemeChanged notifications will then be
	// triggered automatically.
	// </code>
	// The configured color will be available immediately via
	// ICefView.GetThemeColor and will be applied to each View in this
	// Window's component hierarchy when ICefViewDelegate.OnThemeChanged is
	// called. See OnThemeColorsChanged documentation for additional details.
	// Clients wishing to add custom colors should use |color_id| values >=
	// CEF_ChromeColorsEnd.
	SetThemeColor(colorId int32, color cefTypes.TCefColor)
	// ShowAsBrowserModalDialog
	// Show the Window as a browser modal dialog relative to |browser_view|. A
	// parent Window must be returned via
	// ICefWindowDelegate.OnGetParentWindow and |browser_view| must belong
	// to that parent Window. While this Window is visible, |browser_view| will
	// be disabled while other controls in the parent Window remain enabled.
	// Navigating or destroying the |browser_view| will close this Window
	// automatically. Alternately, use show() and return true (1) from
	// ICefWindowDelegate.OnIsWindowModalDialog for a window modal dialog
	// where all controls in the parent Window are disabled.
	ShowAsBrowserModalDialog(browserView ICefBrowserView)
	// ThemeChanged
	// Trigger ICefViewDelegate.OnThemeChanged callbacks for each View in
	// this Window's component hierarchy. Unlike a native/OS or Chrome theme
	// change this function does not reset theme colors to standard values and
	// does not result in a call to ICefWindowDelegate.OnThemeColorsChanged.
	// Do not call this function from ICefWindowDelegate.OnThemeColorsChanged
	// or ICefViewDelegate.OnThemeChanged.
	ThemeChanged()
}

type ICefApplication_147 interface {
	ICefApplication
	ICefApplicationCore_147
	IInterfacedObject
	AsIntfApplicationCoreEvents() uintptr
}

type ICefApplicationCore_147 interface {
	ICefApplicationCore
	IApplicationCoreEvents_147
	IInterfacedObject
	// ApiVersion
	// Returns the CEF API version that was configured by the first call to
	// cef_api_hash().
	ApiVersion() int32
	AsIntfApplicationCoreEvents() uintptr
	// AutoAcceptCamAndMicCapture
	// Bypasses the dialog prompting the user for permission to capture cameras and microphones.
	// Useful in automatic tests of video-conferencing Web applications. This is nearly
	// identical to kUseFakeUIForMediaStream, with the exception being that this flag does NOT
	// affect screen-capture.
	// <see href="https://peter.sh/experiments/chromium-command-line-switches/">Uses the following command line switch: --auto-accept-camera-and-microphone-capture</see>
	AutoAcceptCamAndMicCapture() bool
	// BrowserById
	// Returns the browser (if any) with the specified identifier.
	BrowserById(id int32) ICefBrowser
	// ChromeAppIconId
	// Specify an ID for an ICON resource that can be loaded from the main
	// executable and used when creating default Chrome windows such as DevTools
	// and Task Manager. If unspecified the default Chromium ICON (IDR_MAINFRAME
	// [101]) will be loaded from libcef.dll. Only supported with Chrome style on
	// Windows.
	ChromeAppIconId() int32
	// ChromePolicyId
	// Specify an ID to enable Chrome policy management via Platform and OS-user
	// policies. On Windows, this is a registry key like
	// "SOFTWARE\\Policies\\Google\\Chrome". On MacOS, this is a bundle ID like
	// "com.google.Chrome". On Linux, this is an absolute directory path like
	// "/etc/opt/chrome/policies". Only supported with Chrome style. See
	// https://support.google.com/chrome/a/answer/9037717 for details.
	// Chrome Browser Cloud Management integration, when enabled via the
	// "enable-chrome-browser-cloud-management" command-line flag, will also use
	// the specified ID. See https://support.google.com/chrome/a/answer/9116814
	// for details.
	ChromePolicyId() string
	// DisableHangMonitor
	// Suppresses hang monitor dialogs in renderer processes. This may allow slow unload handlers on a page to prevent the tab from closing, but the Task Manager can be used to terminate the offending process in this case.
	// <see href="https://peter.sh/experiments/chromium-command-line-switches/">Uses the following command line switch: --disable-hang-monitor</see>
	DisableHangMonitor() bool
	// DisableSignalHandlers
	// Specify whether signal handlers must be disabled on POSIX systems.
	DisableSignalHandlers() bool
	// DisplayServer
	// Linux display server type.
	DisplayServer() cefTypes.TCefLinuxDisplayServer
	// DoNotDeElevate
	// Do not de-elevate the browser on launch. Used after de-elevating to prevent infinite loops.
	// <see href="https://peter.sh/experiments/chromium-command-line-switches/#do-not-de-elevate">Uses the following command line switch: --do-not-de-elevate</see>
	DoNotDeElevate() bool
	// DumpWithoutCrashing
	// This function allows for generating of crash dumps with a throttling
	// mechanism, preventing frequent dumps from being generated in a short period
	// of time from the same location. If should only be called after cef_initialize
	// has been successfully called. The |function_name|, |file_name|, and
	// |line_number| parameters specify the origin location of the dump. The
	// |mseconds_between_dumps| is an interval between consecutive dumps in
	// milliseconds from the same location.
	// For detailed behavior, usage instructions, and considerations, refer to the
	// documentation of DumpWithoutCrashing in base/debug/dump_without_crashing.h.
	// <returns>
	// Returns true if the dump was successfully generated, false otherwise.
	// </returns>
	// <see href="https://bitbucket.org/chromiumembedded/cef/src/master/include/base/cef_dump_without_crashing.h">CEF source file: /include/base/cef_dump_without_crashing.h (CefDumpWithoutCrashing)</see>
	DumpWithoutCrashing(msecondsBetweenDumps int64, functionName string, fileName string, lineNumber int32) bool
	// EnableAutomation
	// Enable indication that browser is controlled by automation.
	// <see href="https://peter.sh/experiments/chromium-command-line-switches/#enable-automation">Uses the following command line switch: --enable-automation</see>
	EnableAutomation() bool
	// ExitCode
	// This property can optionally be read on the main application thread after
	// cef_initialize to retrieve the initialization exit code. When cef_initialize
	// returns true (1) the exit code will be 0 (CEF_RESULT_CODE_NORMAL_EXIT).
	// Otherwise, see TCefResultCode for possible exit code values including
	// browser process initialization errors and normal early exit conditions (such
	// as CEF_RESULT_CODE_NORMAL_EXIT_PROCESS_NOTIFIED for process singleton
	// relaunch behavior).
	ExitCode() cefTypes.TCefResultCode
	// ExternalBeginFrameEnabled
	// Set to true (1) to enable the ability to issue BeginFrame requests from
	// the client application by calling ICefBrowserHost.SendExternalBeginFrame.
	ExternalBeginFrameEnabled() bool
	// FieldTrialConfig
	// Enable field trial tests configured in fieldtrial_testing_config.json.
	// If the "disable_fieldtrial_testing_config" GN flag is set to true, then this switch is a no-op.
	// Otherwise, for non-Chrome branded builds, the testing config is already applied by default,
	// unless the "--disable-field-trial-config", "--force-fieldtrials", and/or "--variations-server-url"
	// switches are passed. It is however possible to apply the testing config as well as specify
	// additional field trials (using "--force-fieldtrials") by using this switch. For Chrome-branded
	// builds, the testing config is not enabled by default, so this switch is required to enable it.
	// <see href="https://peter.sh/experiments/chromium-command-line-switches/#enable-field-trial-config">Uses the following command line switch: --enable-field-trial-config</see>
	// <see href="https://peter.sh/experiments/chromium-command-line-switches/#disable-field-trial-config">Uses the following command line switch: --disable-field-trial-config</see>
	FieldTrialConfig() cefTypes.TCefState
	// GTKVersion
	// Preferred GTK version loaded by Chromium.
	// <see href="https://github.com/chromium/chromium/blob/main/ui/gtk/gtk_compat.cc">See the LoadGtkImpl function in ui/gtk/gtk_compat.cc</see>
	GTKVersion() cefTypes.TCefGTKVersion
	// GetCEFVersionInfo
	// Returns CEF version information for the libcef library.
	// <returns>
	// Returns true if successfull.
	// </returns>
	// <see href="https://bitbucket.org/chromiumembedded/cef/src/master/include/cef_version_info.h">CEF source file: /include/cef_version_info.h (cef_version_info)</see>
	GetCEFVersionInfo(cEFVersionInfo *TCefVersionInfo) bool
	// GetChromiumVersionInfo
	// Returns Chromium version information for the libcef library.
	// <returns>
	// Returns true if successfull.
	// </returns>
	// <see href="https://bitbucket.org/chromiumembedded/cef/src/master/include/cef_version_info.h">CEF source file: /include/cef_version_info.h (cef_version_info)</see>
	GetChromiumVersionInfo(chromiumVersionInfo *TChromiumVersionInfo) bool
	// GetIdForCommandIdName
	// Returns the numeric ID value for an IDC |name| from cef_command_ids.h or -1
	// if |name| is unrecognized by the current CEF/Chromium build. This function
	// provides version-safe mapping of command IDC names to version-specific
	// numeric ID values. Numeric ID values are likely to change across
	// CEF/Chromium versions but names generally remain the same.
	// <see href="https://bitbucket.org/chromiumembedded/cef/src/master/include/cef_id_mappers.h">CEF source file: /include/cef_id_mappers.h (cef_id_for_command_id_name)</see>
	GetIdForCommandIdName(name string) int32
	// GetIdForPackResourceName
	// Returns the numeric ID value for an IDR |name| from cef_pack_resources.h or
	// -1 if |name| is unrecognized by the current CEF/Chromium build. This
	// function provides version-safe mapping of resource IDR names to
	// version-specific numeric ID values. Numeric ID values are likely to change
	// across CEF/Chromium versions but names generally remain the same.
	// <see href="https://bitbucket.org/chromiumembedded/cef/src/master/include/cef_id_mappers.h">CEF source file: /include/cef_id_mappers.h (cef_id_for_pack_resource_name)</see>
	GetIdForPackResourceName(name string) int32
	// GetIdForPackStringName
	// Returns the numeric ID value for an IDS |name| from cef_pack_strings.h or -1
	// if |name| is unrecognized by the current CEF/Chromium build. This function
	// provides version-safe mapping of string IDS names to version-specific
	// numeric ID values. Numeric ID values are likely to change across
	// CEF/Chromium versions but names generally remain the same.
	// <see href="https://bitbucket.org/chromiumembedded/cef/src/master/include/cef_id_mappers.h">CEF source file: /include/cef_id_mappers.h (cef_id_for_pack_string_name)</see>
	GetIdForPackStringName(name string) int32
	// HideCrashRestoreBubble
	// Does not show the "Restore pages" popup bubble after incorrect shutdown.
	// <see href="https://peter.sh/experiments/chromium-command-line-switches/">Uses the following command line switch: --hide-crash-restore-bubble</see>
	HideCrashRestoreBubble() bool
	// LogItems
	// The log items prepended to each log line. If not set the default log items
	// will be used. Also configurable using the "log-items" command-line switch
	// with a value of "none" for no log items, or a comma-delimited list of
	// values "pid", "tid", "timestamp" or "tickcount" for custom log items.
	LogItems() cefTypes.TCefLogItems
	// NextComponentID
	// Returns the next component ID and adds this value to the valid ID list.
	NextComponentID() int32
	// NoDefaultBrowserCheck
	// Disables the default browser check. Useful for UI/browser tests where we want to avoid having the default browser info-bar displayed.
	// <see href="https://peter.sh/experiments/chromium-command-line-switches/#no-default-browser-check">Uses the following command line switch: --no-default-browser-check</see>
	NoDefaultBrowserCheck() bool
	// NoFirstRun
	// Skip First Run tasks as well as not showing additional dialogs, prompts or bubbles. Suppressing dialogs, prompts, and bubbles is
	// important as this switch is used by automation (including performance benchmarks) where it's important only a browser window is shown.
	// This may not actually be the first run or the What's New page. Its effect can be partially ignored by adding kForceFirstRun (for FRE),
	// kForceWhatsNew (for What's New) and/or kIgnoreNoFirstRunForSearchEngineChoiceScreen (for the DSE choice screen). This does not drop
	// the First Run sentinel and thus doesn't prevent first run from occurring the next time chrome is launched without this flag.
	// It also does not update the last What's New milestone, so does not prevent What's New from occurring the next time chrome is launched
	// without this flag.
	// <see href="https://peter.sh/experiments/chromium-command-line-switches/#no-first-run">Uses the following command line switch: --no-first-run</see>
	NoFirstRun() bool
	// OzonePlatform
	// Preferred GTK version loaded by Chromium.
	// <see href="https://peter.sh/experiments/chromium-command-line-switches/#ozone-platform">Uses the following command line switch: --ozone-platform</see>
	OzonePlatform() cefTypes.TCefOzonePlatform
	// PasswordStorage
	// Specifies which encryption storage backend to use in Linux.
	// <see href="https://source.chromium.org/chromium/chromium/src/+/main:docs/linux/password_storage.md">Chromium document: docs/linux/password_storage.md</see>
	PasswordStorage() cefTypes.TCefPasswordStorage
	// ProxySettings
	// Configure all the browsers to use a proxy server.
	// If you use the proxy settings in GlobalCEFApp you will not be able to use the proxy properties in TChromiumCore.
	// <see href="https://peter.sh/experiments/chromium-command-line-switches/">Uses the following command line switch: --no-proxy-server</see>
	// <see href="https://peter.sh/experiments/chromium-command-line-switches/">Uses the following command line switch: --proxy-auto-detect</see>
	// <see href="https://peter.sh/experiments/chromium-command-line-switches/">Uses the following command line switch: --proxy-bypass-list</see>
	// <see href="https://peter.sh/experiments/chromium-command-line-switches/">Uses the following command line switch: --proxy-pac-url</see>
	// <see href="https://peter.sh/experiments/chromium-command-line-switches/">Uses the following command line switch: --proxy-server</see>
	// <see href="https://www.chromium.org/developers/design-documents/network-settings/">See the Network Settings article.</see>
	// <see href="https://github.com/chromium/chromium/blob/main/net/docs/proxy.md"/">See the Proxy Support article.</see>
	// <see href="https://developer.chrome.com/docs/extensions/reference/api/proxy">See the chrome.proxy API article.</see>
	ProxySettings() ICEFProxySettings_147
	// RemoteAllowOrigins
	// Enables web socket connections from the specified origins only. '*' allows any origin.
	// <see href="https://peter.sh/experiments/chromium-command-line-switches/">Uses the following command line switch: --remote-allow-origins</see>
	RemoteAllowOrigins() string
	// RemoveComponentID
	// Removes a component ID from the valid ID list when a component is destroyed.
	RemoveComponentID(componentID int32)
	SetAutoAcceptCamAndMicCapture(value bool)
	SetChromeAppIconId(value int32)
	SetChromePolicyId(value string)
	SetDisableHangMonitor(value bool)
	SetDisableSignalHandlers(value bool)
	SetDoNotDeElevate(value bool)
	SetEnableAutomation(value bool)
	SetExternalBeginFrameEnabled(value bool)
	SetFieldTrialConfig(value cefTypes.TCefState)
	SetGTKVersion(value cefTypes.TCefGTKVersion)
	SetHideCrashRestoreBubble(value bool)
	SetLogItems(value cefTypes.TCefLogItems)
	// SetNestableTasksAllowed
	// Set to true (1) before calling OS APIs on the CEF UI thread that will enter
	// a native message loop (see usage restrictions below). Set to false (0) after
	// exiting the native message loop. On Windows, use the CefSetOSModalLoop
	// function instead in cases like native top menus where resize of the browser
	// content is not required, or in cases like printer APIs where reentrancy
	// safety cannot be guaranteed.
	// Nested processing of Chromium tasks is disabled by default because common
	// controls and/or printer functions may use nested native message loops that
	// lead to unplanned reentrancy. This function re-enables nested processing in
	// the scope of an upcoming native message loop. It must only be used in cases
	// where the stack is reentrancy safe and processing nestable tasks is
	// explicitly safe. Do not use in cases (like the printer example) where an OS
	// API may experience unplanned reentrancy as a result of a new task executing
	// immediately.
	// For instance,
	// <code>
	// - The UI thread is running a message loop.
	// - It receives a task #1 and executes it.
	// - The task #1 implicitly starts a nested message loop. For example, via
	// Windows APIs such as MessageBox or GetSaveFileName, or default handling of
	// a user-initiated drag/resize operation (e.g. DefWindowProc handling of
	// WM_SYSCOMMAND for SC_MOVE/SC_SIZE).
	// - The UI thread receives a task #2 before or while in this second message
	// loop.
	// - With NestableTasksAllowed set to true (1), the task #2 will run right
	// away. Otherwise, it will be executed right after task #1 completes at
	// "thread message loop level".
	// </code>
	SetNestableTasksAllowed(allowed bool)
	SetNoDefaultBrowserCheck(value bool)
	SetNoFirstRun(value bool)
	SetOnAlreadyRunningAppRelaunch(fn TOnAlreadyRunningAppRelaunchEvent)
	SetOnGetDefaultRequestContextHandler(fn TOnGetDefaultRequestContextHandlerEvent)
	SetOzonePlatform(value cefTypes.TCefOzonePlatform)
	SetPasswordStorage(value cefTypes.TCefPasswordStorage)
	SetRemoteAllowOrigins(value string)
	SetSharedTextureEnabled(value bool)
	SetTLS13HybridizedKyberSupport(value cefTypes.TCefState)
	SetUIColorMode(value cefTypes.TCefUIColorMode)
	SetUseAngle(value cefTypes.TCefAngleImplementation)
	SetUseGL(value cefTypes.TCefGLImplementation)
	SetUseViewsDefaultPopup(value bool)
	// SharedTextureEnabled
	// Set to true (1) to enable shared textures for windowless rendering. Only
	// valid if windowless_rendering_enabled above is also set to true. Currently
	// only supported on Windows (D3D11).
	SharedTextureEnabled() bool
	// TLS13HybridizedKyberSupport
	// This option enables a combination of X25519 and Kyber in TLS 1.3.
	TLS13HybridizedKyberSupport() cefTypes.TCefState
	// UIColorMode
	// Forces light or dark mode in UI for platforms that support it.
	// <see href="https://peter.sh/experiments/chromium-command-line-switches/">Uses the following command line switches: --force-dark-mode --force-light-mode</see>
	UIColorMode() cefTypes.TCefUIColorMode
	// UseAngle
	// Select which ANGLE backend to use.
	// <see href="https://peter.sh/experiments/chromium-command-line-switches/#use-angle">Uses the following command line switch: --use-angle</see>
	// <see href="https://source.chromium.org/chromium/chromium/src/+/main:ui/gl/gl_switches.cc">See the gl_switches.cc file</see>
	UseAngle() cefTypes.TCefAngleImplementation
	// UseGL
	// Select which implementation of GL the GPU process should use.
	// <see href="https://peter.sh/experiments/chromium-command-line-switches/#use-gl">Uses the following command line switch: --use-gl</see>
	// <see href="https://source.chromium.org/chromium/chromium/src/+/main:ui/gl/gl_switches.cc">See the gl_switches.cc file</see>
	UseGL() cefTypes.TCefGLImplementation
	// UseViewsDefaultPopup
	// If true use a Views (bare-bones) window instead of a Chrome UI window when
	// creating default popups for Chrome style native-hosted (non-Views)
	// browsers. This applies when ICefLifeSpanHandler.OnBeforePopup has not been
	// implemented to provide parent window information for the new popup.
	UseViewsDefaultPopup() bool
	// ValidComponentID
	// Returns true if a custom component ID is valid before executing a CEF task.
	ValidComponentID(componentID int32) bool
}

type ICefBinaryValue_147 interface {
	ICefBinaryValue
	// GetRawData
	// Returns a pointer to the beginning of the memory block. The returned
	// pointer is valid as long as the ICefBinaryValue is alive.
	GetRawData() uintptr
}

type ICefBinaryValueRef_147 interface {
	ICefBinaryValueRef
	ICefBinaryValue_147
}

type ICefBrowser_147 interface {
	ICefBrowser
	// GetFrameByIdentifier
	// Returns the frame with the specified identifier, or NULL if not found.
	GetFrameByIdentifier(identifier string) ICefFrame
	// GetFrameByName
	// Returns the frame with the specified name, or NULL if not found.
	GetFrameByName(name string) ICefFrame
	// GetFrameIdentifiers
	// Returns the identifiers of all existing frames.
	GetFrameIdentifiers(frameIdentifiers *lcl.IStrings) bool
}

type ICefBrowserHost_147 interface {
	ICefBrowserHost
	// CanExecuteChromeCommand
	// Returns true (1) if a Chrome command is supported and enabled. Use the
	// cef_id_for_command_id_name() function for version-safe mapping of command
	// IDC names from cef_command_ids.h to version-specific numerical
	// |command_id| values. This function can only be called on the UI thread.
	// Only used with Chrome style.
	// <see cref="uCEFConstants">See the IDC_* constants in uCEFConstants.pas for all the |command_id| values.</see>
	// <see href="https://source.chromium.org/chromium/chromium/src/+/main:chrome/app/chrome_command_ids.h">The command_id values are also available in chrome/app/chrome_command_ids.h</see>
	CanExecuteChromeCommand(commandId int32) bool
	// CanZoom
	// Returns true (1) if this browser can execute the specified zoom command.
	// This function can only be called on the UI thread.
	CanZoom(command cefTypes.TCefZoomCommand) bool
	// ExecuteChromeCommand
	// Returns true (1) if a Chrome command is supported and enabled. Use the
	// cef_id_for_command_id_name() function for version-safe mapping of command
	// IDC names from cef_command_ids.h to version-specific numerical
	// |command_id| values. This function can only be called on the UI thread.
	// Only used with Chrome style.
	// <see cref="uCEFConstants">See the IDC_* constants in uCEFConstants.pas for all the |command_id| values.</see>
	// <see href="https://source.chromium.org/chromium/chromium/src/+/main:chrome/app/chrome_command_ids.h">The command_id values are also available in chrome/app/chrome_command_ids.h</see>
	ExecuteChromeCommand(commandId int32, disposition cefTypes.TCefWindowOpenDisposition)
	// ExitFullscreen
	// Requests the renderer to exit browser fullscreen. In most cases exiting
	// window fullscreen should also exit browser fullscreen. With Alloy style
	// this function should be called in response to a user action such as
	// clicking the green traffic light button on MacOS
	// (ICefWindowDelegate.OnWindowFullscreenTransition callback) or pressing
	// the "ESC" key (ICefKeyboardHandler.OnPreKeyEvent callback). With
	// Chrome style these standard exit actions are handled internally but
	// new/additional user actions can use this function. Set |will_cause_resize|
	// to true (1) if exiting browser fullscreen will cause a view resize.
	ExitFullscreen(willCauseResize bool)
	// GetClient
	// Returns the client for this browser.
	GetClient() IEngClient
	// GetDefaultZoomLevel
	// Get the default zoom level. This value will be 0.0 by default but can be
	// configured. This function can only be called on the UI thread.
	GetDefaultZoomLevel() float64
	// GetOpenerIdentifier
	// Retrieve the unique identifier of the browser that opened this browser.
	// Will return 0 for non-popup browsers.
	GetOpenerIdentifier() int32
	// GetRuntimeStyle
	// Returns the runtime style for this browser (ALLOY or CHROME). See
	// TCefRuntimeStyle documentation for details.
	// This function can only be called on the CEF UI thread.
	GetRuntimeStyle() cefTypes.TCefRuntimeStyle
	// IsFullscreen
	// Returns true (1) if the renderer is currently in browser fullscreen. This
	// differs from window fullscreen in that browser fullscreen is entered using
	// the JavaScript Fullscreen API and modifies CSS attributes such as the
	// ::backdrop pseudo-element and :fullscreen pseudo-structure. This function
	// can only be called on the UI thread.
	IsFullscreen() bool
	// IsReadyToBeClosed
	// Returns true (1) if the browser is ready to be closed, meaning that the
	// close has already been initiated and that JavaScript unload handlers have
	// already executed or should be ignored. This can be used from a top-level
	// window close handler such as TCEFWindowComponent.OnCanClose (or platform-
	// specific equivalent) to distringuish between potentially cancelable
	// browser close events (like the user clicking the top-level window close
	// button before browser close has started) and mandatory browser close
	// events (like JavaScript `window.close()` or after browser close has
	// started in response to [Try]CloseBrowser()). Not completing the browser
	// close for mandatory close events (when this function returns true (1))
	// will leave the browser in a partially closed state that interferes with
	// proper functioning. See CloseBrowser() documentation for additional usage
	// information. This function must be called on the browser process UI
	// thread.
	IsReadyToBeClosed() bool
	// IsRenderProcessUnresponsive
	// Returns true (1) if the render process associated with this browser is
	// currently unresponsive as indicated by a lack of input event processing
	// for at least 15 seconds. To receive associated state change notifications
	// and optionally handle an unresponsive render process implement
	// ICefRequestHandler.OnRenderProcessUnresponsive.
	// This function can only be called on the CEF UI thread.
	IsRenderProcessUnresponsive() bool
	// SetAxViewportCollapse
	// Enable or disable CDP accessibility tree viewport collapse for this
	// browser. When enabled, off-screen landmarks and headings are serialized as
	// summaries and other off-screen nodes are pruned. Overrides the
	// TCefBrowserSettings.ax_viewport_collapse value. If called on the UI
	// thread the change will be applied immediately. Otherwise, the change will
	// be applied asynchronously on the UI thread. WARNING: This collapses the
	// CDP accessibility tree and disables CDP dynamic tree updates (nodesUpdated
	// events). The DevTools Accessibility panel will show an incomplete tree.
	// Platform screen readers (NVDA, JAWS, VoiceOver) are unaffected they use
	// a separate code path.
	SetAxViewportCollapse(enabled bool)
	// Zoom
	// Execute a zoom command in this browser. If called on the UI thread the
	// change will be applied immediately. Otherwise, the change will be applied
	// asynchronously on the UI thread.
	Zoom(command cefTypes.TCefZoomCommand)
}

type ICefBrowserHostRef_147 interface {
	ICefBrowserHostRef
	ICefBrowserHost_147
}

type ICefBrowserRef_147 interface {
	ICefBrowserRef
	ICefBrowser_147
}

type ICefBrowserView_147 interface {
	ICefBrowserView
	ICefView_147
	// GetRuntimeStyle
	// Returns the runtime style for this BrowserView (ALLOY or CHROME). See
	// TCefRuntimeStyle documentation for details.
	GetRuntimeStyle() cefTypes.TCefRuntimeStyle
}

type ICefBrowserViewRef_147 interface {
	ICefBrowserViewRef
	ICefBrowserView_147
	ICefViewRef_147
}

type ICefButton_147 interface {
	ICefButton
	ICefView_147
}

type ICefButtonRef_147 interface {
	ICefButtonRef
	ICefButton_147
	ICefViewRef_147
}

type ICefChromiumTask_147 interface {
	ICefManagedTask_147
	AsIntfTask() uintptr
}

type ICefCommandLine_147 interface {
	ICefCommandLine
	// RemoveSwitch
	// Remove a switch from the command line. If no such switch is present, this
	// has no effect.
	RemoveSwitch(name string)
}

type ICefCommandLineRef_147 interface {
	ICefCommandLineRef
	ICefCommandLine_147
}

type ICefComponent_147 interface {
	ICefBaseRefCounted
	// GetId
	// Returns the unique identifier for this component.
	GetId() string
	// GetName
	// Returns the human-readable name of this component. Returns an NULL string
	// if the component is not installed.
	GetName() string
	// GetState
	// Returns the state of this component at the time this object was created. A
	// component is considered installed when its state is one of:
	// CEF_COMPONENT_STATE_UPDATED, CEF_COMPONENT_STATE_UP_TO_DATE, or
	// CEF_COMPONENT_STATE_RUN.
	GetState() cefTypes.TCefComponentState
	// GetVersion
	// Returns the version of this component as a string (e.g., "1.2.3.4").
	// Returns an NULL string if the component is not installed.
	GetVersion() string
}

type ICefComponentRef_147 interface {
	ICefBaseRefCountedRef
	ICefComponent_147
	AsIntfComponent() uintptr
}

type ICefCustomStringList_147 interface {
	ICefCustomStringList
	ICefStringList_147
}

type ICefCustomUserData_147 interface {
	ICefBaseRefCountedOwn
	AsIntfCustomUserData() uintptr
	GetUserDataType() uintptr
	GetUserData() uintptr
}

type ICefDomNode_147 interface {
	ICefDomNode
	// GetFormControlElementType
	// Returns the type of this form control element node.
	GetFormControlElementType() cefTypes.TCefDomFormControlType
}

type ICefDomNodeRef_147 interface {
	ICefDomNodeRef
	ICefDomNode_147
}

type ICefDownloadItem_147 interface {
	ICefDownloadItem
	// GetInterruptReason
	// Returns the most recent interrupt reason.
	GetInterruptReason() cefTypes.TCefDownloadInterruptReason
	// IsInterrupted
	// Returns true (1) if the download has been interrupted.
	IsInterrupted() bool
	// IsPaused
	// Returns true (1) if the download has been paused.
	IsPaused() bool
}

type ICefDownloadItemRef_147 interface {
	ICefBaseRefCountedRef
	ICefDownloadItem_147
	AsIntfDownloadItem() uintptr
}

type ICefDragData_147 interface {
	ICefDragData
	// GetFilePaths
	// Retrieve the list of file paths that are being dragged into the browser
	// window.
	GetFilePaths(paths *lcl.IStrings) int32
}

type ICefDragDataRef_147 interface {
	ICefDragDataRef
	ICefDragData_147
}

type ICefFrame_147 interface {
	ICefFrame
	// PasteAndMatchStyle
	// Execute paste and match style in this frame.
	PasteAndMatchStyle()
}

type ICefFrameRef_147 interface {
	ICefFrameRef
	ICefFrame_147
}

type ICefGenericTask_147 interface {
	ICefGenericTask
	ICefChromiumTask_147
}

type ICefLabelButton_147 interface {
	ICefLabelButton
	ICefButton_147
}

type ICefLabelButtonRef_147 interface {
	ICefLabelButtonRef
	ICefButtonRef_147
	ICefLabelButton_147
}

type ICefManagedTask_147 interface {
	ICefTaskOwn
	AsIntfTask() uintptr
}

type ICefMenuButton_147 interface {
	ICefMenuButton
	ICefLabelButton_147
}

type ICefMenuButtonRef_147 interface {
	ICefMenuButtonRef
	ICefLabelButtonRef_147
	ICefMenuButton_147
}

type ICefPanel_147 interface {
	ICefPanel
	ICefView_147
}

type ICefPanelRef_147 interface {
	ICefPanelRef
	ICefPanel_147
	ICefViewRef_147
}

type ICefPreferenceManager_147 interface {
	ICefPreferenceManager
	// AddPreferenceObserver
	// Add an observer for preference changes. |name| is the name of the
	// preference to observe. If |name| is NULL then all preferences will be
	// observed. Observing all preferences has performance consequences and is
	// not recommended outside of testing scenarios. The observer will remain
	// registered until the returned Registration object is destroyed. This
	// function must be called on the browser process UI thread.
	AddPreferenceObserver(name string, observer IEngPreferenceObserver_147) ICefRegistration
}

type ICefPreferenceManagerRef_147 interface {
	ICefPreferenceManagerRef
	ICefPreferenceManager_147
}

type ICefPreferenceObserver_147 interface {
	ICefBaseRefCounted
}

type ICefPreferenceObserverOwn_147 interface {
	ICefBaseRefCountedOwn
	ICefPreferenceObserver_147
}

type ICefRequestContext_147 interface {
	ICefRequestContext
	ICefPreferenceManager_147
	// AddSettingObserver
	// Add an observer for content and website setting changes. The observer will
	// remain registered until the returned Registration object is destroyed.
	// This function must be called on the browser process UI thread.
	AddSettingObserver(observer IEngSettingObserver_147) ICefRegistration
	// ClearHttpCache
	// Clears the HTTP cache. If |callback| is non-NULL it will be executed on
	// the UI thread after completion.
	ClearHttpCache(callback IEngCompletionCallback)
	// GetChromeColorSchemeColor
	// Returns the current Chrome color scheme color, or transparent (0) for the
	// default color. Must be called on the browser process UI thread.
	GetChromeColorSchemeColor() cefTypes.TCefColor
	// GetChromeColorSchemeMode
	// Returns the current Chrome color scheme mode (SYSTEM, LIGHT or DARK). Must
	// be called on the browser process UI thread.
	GetChromeColorSchemeMode() cefTypes.TCefColorVariant
	// GetChromeColorSchemeVariant
	// Returns the current Chrome color scheme variant. Must be called on the
	// browser process UI thread.
	GetChromeColorSchemeVariant() cefTypes.TCefColorVariant
	// GetContentSetting
	// Returns the current value for |content_type| that applies for the
	// specified URLs. If both URLs are NULL the default value will be returned.
	// Returns CEF_CONTENT_SETTING_VALUE_DEFAULT if no value is configured. Must
	// be called on the browser process UI thread.
	GetContentSetting(requestingUrl string, topLevelUrl string, contentType cefTypes.TCefContentSettingTypes) cefTypes.TCefContentSettingValues
	// GetWebsiteSetting
	// Returns the current value for |content_type| that applies for the
	// specified URLs. If both URLs are NULL the default value will be returned.
	// Returns nullptr if no value is configured. Must be called on the browser
	// process UI thread.
	GetWebsiteSetting(requestingUrl string, topLevelUrl string, contentType cefTypes.TCefContentSettingTypes) ICefValue
	// SetChromeColorScheme
	// Sets the Chrome color scheme for all browsers that share this request
	// context. |variant| values of SYSTEM, LIGHT and DARK change the underlying
	// color mode (e.g. light vs dark). Other |variant| values determine how
	// |user_color| will be applied in the current color mode. If |user_color| is
	// transparent (0) the default color will be used.
	SetChromeColorScheme(variant cefTypes.TCefColorVariant, userColor cefTypes.TCefColor)
	// SetContentSetting
	// Sets the current value for |content_type| for the specified URLs in the
	// default scope. If both URLs are NULL, and the context is not incognito,
	// the default value will be set. Pass CEF_CONTENT_SETTING_VALUE_DEFAULT for
	// |value| to use the default value for this content type.
	// WARNING: Incorrect usage of this function may cause instability or
	// security issues in Chromium. Make sure that you first understand the
	// potential impact of any changes to |content_type| by reviewing the related
	// source code in Chromium. For example, if you plan to modify
	// CEF_CONTENT_SETTING_TYPE_POPUPS, first review and understand the usage of
	// ContentSettingsType::POPUPS in Chromium:
	// https://source.chromium.org/search?q=ContentSettingsType::POPUPS
	SetContentSetting(requestingUrl string, topLevelUrl string, contentType cefTypes.TCefContentSettingTypes, value cefTypes.TCefContentSettingValues)
	// SetWebsiteSetting
	// Sets the current value for |content_type| for the specified URLs in the
	// default scope. If both URLs are NULL, and the context is not incognito,
	// the default value will be set. Pass nullptr for |value| to remove the
	// default value for this content type.
	// WARNING: Incorrect usage of this function may cause instability or
	// security issues in Chromium. Make sure that you first understand the
	// potential impact of any changes to |content_type| by reviewing the related
	// source code in Chromium. For example, if you plan to modify
	// CEF_CONTENT_SETTING_TYPE_POPUPS, first review and understand the usage of
	// ContentSettingsType::POPUPS in Chromium:
	// https://source.chromium.org/search?q=ContentSettingsType::POPUPS
	SetWebsiteSetting(requestingUrl string, topLevelUrl string, contentType cefTypes.TCefContentSettingTypes, value ICefValue)
}

type ICefRequestContextRef_147 interface {
	ICefRequestContextRef
	ICefPreferenceManagerRef_147
	ICefRequestContext_147
}

type ICefScrollView_147 interface {
	ICefScrollView
	ICefView_147
}

type ICefScrollViewRef_147 interface {
	ICefScrollViewRef
	ICefScrollView_147
	ICefViewRef_147
}

type ICefSettingObserver_147 interface {
	ICefBaseRefCounted
}

type ICefSettingObserverOwn_147 interface {
	ICefBaseRefCountedOwn
	ICefSettingObserver_147
}

type ICefStringList_147 interface {
	ICefStringList
	GetHandle() cefTypes.TCefStringList
}

type ICefStringListOwn_147 interface {
	ICefStringListOwn
	ICefCustomStringList_147
}

type ICefStringListRef_147 interface {
	ICefStringListRef
	ICefCustomStringList_147
}

type ICefTaskManager_147 interface {
	ICefBaseRefCounted
	// GetTaskIdForBrowserId
	// Returns the task ID associated with the main task for |browser_id| (value
	// from cef_browser_t::GetIdentifier). Returns -1 if |browser_id| is invalid,
	// does not currently have an associated task, or the function was called
	// from the incorrect thread.
	GetTaskIdForBrowserId(browserId int32) int64
	// GetTaskIdsList
	// Gets the list of task IDs currently tracked by the task manager. Tasks
	// that share the same process id will always be consecutive. The list will
	// be sorted in a way that reflects the process tree: the browser process
	// will be first, followed by the gpu process if it exists. Related processes
	// (e.g., a subframe process and its parent) will be kept together if
	// possible. Callers can expect this ordering to be stable when a process is
	// added or removed. The task IDs are unique within the application lifespan.
	// Returns false (0) if the function was called from the incorrect thread.
	GetTaskIdsList(taskIds *lcl.IInt64ArrayWrap) bool
	// GetTaskInfo
	// Gets information about the task with |task_id|. Returns true (1) if the
	// information about the task was successfully retrieved and false (0) if the
	// |task_id| is invalid or the function was called from the incorrect thread.
	GetTaskInfo(taskId int64, info *TCustomTaskInfo) bool
	// GetTasksCount
	// Returns the number of tasks currently tracked by the task manager. Returns
	// 0 if the function was called from the incorrect thread.
	GetTasksCount() cefTypes.NativeUInt
	// KillTask
	// Attempts to terminate a task with |task_id|. Returns false (0) if the
	// |task_id| is invalid, the call is made from an incorrect thread, or if the
	// task cannot be terminated.
	KillTask(taskId int64) bool
}

type ICefTaskManagerRef_147 interface {
	ICefBaseRefCountedRef
	ICefTaskManager_147
	AsIntfTaskManager() uintptr
}

type ICefTaskRef_147 interface {
	ICefBaseRefCountedRef
	ICefTask
	AsIntfTask() uintptr
}

type ICefTextfield_147 interface {
	ICefTextfield
	ICefView_147
}

type ICefTextfieldRef_147 interface {
	ICefTextfieldRef
	ICefTextfield_147
	ICefViewRef_147
}

type ICefURLRequestClientTask_147 interface {
	ICefManagedTask_147
	AsIntfTask() uintptr
}

type ICefUnresponsiveProcessCallback_147 interface {
	ICefBaseRefCounted
	// Terminate
	// Terminate the unresponsive process.
	Terminate()
	// Wait
	// Reset the timeout for the unresponsive process.
	Wait()
}

type ICefUnresponsiveProcessCallbackRef_147 interface {
	ICefBaseRefCountedRef
	ICefUnresponsiveProcessCallback_147
	AsIntfUnresponsiveProcessCallback() uintptr
}

type ICefUrlRequest_147 interface {
	ICefUrlRequest
	// GetClient
	// Returns the client.
	GetClient() IEngUrlrequestClient
}

type ICefUrlRequestRef_147 interface {
	ICefUrlRequestRef
	ICefUrlRequest_147
}

type ICefUrlrequestClientRef_147 interface {
	ICefBaseRefCountedRef
	ICefUrlrequestClient
	AsIntfUrlrequestClient() uintptr
}

type ICefView_147 interface {
	ICefView
	// GetThemeColor
	// Returns the current theme color associated with |color_id|, or the
	// placeholder color (red) if unset. See cef_color_ids.h for standard ID
	// values. Standard colors can be overridden and custom colors can be added
	// using ICefWindow.SetThemeColor.
	GetThemeColor(colorId int32) cefTypes.TCefColor
	// HasFocus
	// Returns true (1) if this View has focus in the context of the containing
	// Window. Check both this function and ICefWindow.IsActive to determine
	// global keyboard focus.
	HasFocus() bool
}

type ICefViewDelegateTask_147 interface {
	ICefManagedTask_147
	AsIntfTask() uintptr
}

type ICefViewRef_147 interface {
	ICefViewRef
	ICefView_147
}

type ICefWindow_147 interface {
	ICefWindow
	ICefPanel_147
	// AddOverlayView
	// Add a View that will be overlayed on the Window contents with absolute
	// positioning and high z-order. Positioning is controlled by |docking_mode|
	// as described below. Setting |can_activate| to true (1) will allow the
	// overlay view to receive input focus. The returned cef_overlay_controller_t
	// object is used to control the overlay. Overlays are hidden by default.
	// With CEF_DOCKING_MODE_CUSTOM:
	// 1. The overlay is initially hidden, sized to |view|'s preferred size,
	// and positioned in the top-left corner.
	// 2. Optionally change the overlay position and/or size by calling
	// CefOverlayController methods.
	// 3. Call ICefOverlayController.SetVisible(true) to show the overlay.
	// 4. The overlay will be automatically re-sized if |view|'s layout
	// changes. Optionally change the overlay position and/or size when
	// OnLayoutChanged is called on the Window's delegate to indicate a
	// change in Window bounds.
	// With other docking modes:
	// 1. The overlay is initially hidden, sized to |view|'s preferred size,
	// and positioned based on |docking_mode|.
	// 2. Call ICefOverlayController.SetVisible(true) to show the overlay.
	// 3. The overlay will be automatically re-sized if |view|'s layout changes
	// and re-positioned as appropriate when the Window resizes.
	// Overlays created by this function will receive a higher z-order then any
	// child Views added previously. It is therefore recommended to call this
	// function last after all other child Views have been added so that the
	// overlay displays as the top-most child of the Window.
	AddOverlayView(view ICefView, dockingMode cefTypes.TCefDockingMode, canActivate bool) ICefOverlayController
	// GetFocusedView
	// Returns the View that currently has focus in this Window, or nullptr if no
	// View currently has focus. A Window may have a focused View even if it is
	// not currently active. Any focus changes while a Window is not active may
	// be applied after that Window next becomes active.
	GetFocusedView() ICefView
	// GetRuntimeStyle
	// Returns the runtime style for this Window (ALLOY or CHROME). See
	// TCefRuntimeStyle documentation for details.
	GetRuntimeStyle() cefTypes.TCefRuntimeStyle
	// SetAccelerator
	// Set the keyboard accelerator for the specified |command_id|. |key_code|
	// can be any virtual key or character value. Required modifier keys are
	// specified by |shift_pressed|, |ctrl_pressed| and/or |alt_pressed|.
	// ICefWindowDelegate.OnAccelerator will be called if the keyboard
	// combination is triggered while this window has focus.
	// The |high_priority| value will be considered if a child ICefBrowserView
	// has focus when the keyboard combination is triggered. If |high_priority|
	// is true (1) then the key event will not be forwarded to the web content
	// (`keydown` event handler) or ICefKeyboardHandler first. If
	// |high_priority| is false (0) then the behavior will depend on the
	// ICefBrowserView.SetPreferAccelerators configuration.
	SetAccelerator(commandId int32, keyCode int32, shiftPressed bool, ctrlPressed bool, altPressed bool, highPriority bool)
	// SetThemeColor
	// Override a standard theme color or add a custom color associated with
	// |color_id|. See cef_color_ids.h for standard ID values. Recommended usage
	// is as follows:
	// <code>
	// 1. Customize the default native/OS theme by calling SetThemeColor before
	// showing the first Window. When done setting colors call
	// ICefWindow.ThemeChanged to trigger ICefViewDelegate.OnThemeChanged
	// notifications.
	// 2. Customize the current native/OS or Chrome theme after it changes by
	// calling SetThemeColor from the ICefWindowDelegate.OnThemeColorsChanged
	// callback. ICefViewDelegate.OnThemeChanged notifications will then be
	// triggered automatically.
	// </code>
	// The configured color will be available immediately via
	// ICefView.GetThemeColor and will be applied to each View in this
	// Window's component hierarchy when ICefViewDelegate.OnThemeChanged is
	// called. See OnThemeColorsChanged documentation for additional details.
	// Clients wishing to add custom colors should use |color_id| values >=
	// CEF_ChromeColorsEnd.
	SetThemeColor(colorId int32, color cefTypes.TCefColor)
	// ShowAsBrowserModalDialog
	// Show the Window as a browser modal dialog relative to |browser_view|. A
	// parent Window must be returned via
	// ICefWindowDelegate.GetParentWindow() and |browser_view| must belong
	// to that parent Window. While this Window is visible, |browser_view| will
	// be disabled while other controls in the parent Window remain enabled.
	// Navigating or destroying the |browser_view| will close this Window
	// automatically. Alternately, use show() and return true (1) from
	// ICefWindowDelegate.IsWindowModalDialog() for a window modal dialog
	// where all controls in the parent Window are disabled.
	ShowAsBrowserModalDialog(browserView ICefBrowserView)
	// ThemeChanged
	// Trigger ICefViewDelegate.OnThemeChanged callbacks for each View in
	// this Window's component hierarchy. Unlike a native/OS or Chrome theme
	// change this function does not reset theme colors to standard values and
	// does not result in a call to ICefWindowDelegate.OnThemeColorsChanged.
	// Do not call this function from ICefWindowDelegate.OnThemeColorsChanged
	// or ICefViewDelegate.OnThemeChanged.
	ThemeChanged()
}

type ICefWindowRef_147 interface {
	ICefWindowRef
	ICefPanelRef_147
	ICefWindow_147
}

type ICefv8BackingStore_147 interface {
	ICefBaseRefCounted
	// ByteLength
	// Returns the size of the allocated memory in bytes, or 0 if the backing
	// store has been consumed.
	ByteLength() cefTypes.NativeUInt
	// Data
	// Returns a pointer to the allocated memory, or nullptr if the backing store
	// has been consumed or is otherwise invalid. The pointer is safe to
	// read/write from any thread. The caller must ensure all writes are complete
	// before passing this object to
	// TCefv8ValueRef.NewArrayBufferFromBackingStore(). Pointers obtained
	// from this function should not be retained after calling
	// TCefv8ValueRef.NewArrayBufferFromBackingStore(), as the memory will
	// then be owned by the ArrayBuffer and subject to V8 garbage collection.
	Data() uintptr
	// IsValid
	// Returns true (1) if this backing store has not yet been consumed by
	// TCefv8ValueRef.NewArrayBufferFromBackingStore().
	IsValid() bool
}

type ICefv8BackingStoreRef_147 interface {
	ICefBaseRefCountedRef
	ICefv8BackingStore_147
	AsIntfV8BackingStore() uintptr
}

type ICefv8Value_147 interface {
	ICefv8Value
	// GetArrayBufferByteLength
	// Returns the length (in bytes) of the ArrayBuffer.
	GetArrayBufferByteLength() cefTypes.NativeUInt
	// GetArrayBufferData
	// Returns a pointer to the beginning of the memory block for this
	// ArrayBuffer backing store. The returned pointer is valid as long as the
	// ICefv8value is alive.
	GetArrayBufferData() uintptr
	// GetUserData
	// Returns the user data, if any, assigned to this object.
	GetUserData() ICefCustomUserData_147
	// SetUserData
	// Sets the user data for this object and returns true (1) on success.
	// Returns false (0) if this function is called incorrectly. This function
	// can only be called on user created objects.
	SetUserData(data ICefCustomUserData_147) bool
	// SetValueByAccessor
	// Registers an identifier and returns true (1) on success. Access to the
	// identifier will be forwarded to the ICefV8Accessor instance passed to
	// cef_v8_value_create_object(). Returns false (0) if this
	// function is called incorrectly or an exception is thrown. For read-only
	// values this function will return true (1) even though assignment failed.
	SetValueByAccessor(key string, attribute cefTypes.TCefV8PropertyAttributes) bool
}

type ICefv8ValueRef_147 interface {
	ICefv8ValueRef
	ICefv8Value_147
}

type IChromium_147 interface {
	IChromium
	IChromiumCore_147
}

type IChromiumCore_147 interface {
	IChromiumCore
	// AddPreferenceObserver
	// Add an observer for preference changes. |name| is the name of the
	// preference to observe. If |name| is NULL then all preferences will be
	// observed. Observing all preferences has performance consequences and is
	// not recommended outside of testing scenarios. The observer will remain
	// registered until the returned Registration object is destroyed. This
	// function must be called on the browser process UI thread.
	// <see href="https://bitbucket.org/chromiumembedded/cef/src/master/include/capi/cef_preference_capi.h">CEF source file: /include/capi/cef_preference_capi.h (cef_preference_manager_t)</see>
	AddPreferenceObserver(name string)
	// AddSettingObserver
	// Add an observer for content and website setting changes. The observer will
	// remain registered until the returned Registration object is destroyed.
	// This function must be called on the browser process UI thread.
	// <see href="https://bitbucket.org/chromiumembedded/cef/src/master/include/capi/cef_request_context_capi.h">CEF source file: /include/capi/cef_request_context_capi.h (cef_request_context_t)</see>
	AddSettingObserver(observer IEngSettingObserver_147) ICefRegistration
	// AutofillCreditCard
	// Browser preference used to enable the autofill feature for credit card information.
	// Disabling this property is a suggested workaround for some autofill crashes in Alloy style.
	AutofillCreditCard() cefTypes.TCefState
	// AutofillProfile
	// Browser preference used to enable the autofill feature for profile information.
	// Disabling this property is a suggested workaround for some autofill crashes in Alloy style.
	AutofillProfile() cefTypes.TCefState
	// AutofillSaveData
	// Browser preference used to enable the autofill feature for saving data.
	// Disabling this property is a suggested workaround for some autofill crashes in Alloy style.
	AutofillSaveData() cefTypes.TCefState
	// CanDecZoom
	// Returns true (1) if this browser can execute the zoom OUT command.
	// This function can only be called on the CEF UI thread.
	CanDecZoom() bool
	// CanExecuteChromeCommand
	// Returns true (1) if a Chrome command is supported and enabled. Use the
	// cef_id_for_command_id_name() function for version-safe mapping of command
	// IDC names from cef_command_ids.h to version-specific numerical
	// |command_id| values. This function can only be called on the UI thread.
	// Only used with Chrome style.
	// <see cref="uCEFConstants">See the IDC_* constants in uCEFConstants.pas for all the |command_id| values.</see>
	// <see href="https://source.chromium.org/chromium/chromium/src/+/main:chrome/app/chrome_command_ids.h">The command_id values are also available in chrome/app/chrome_command_ids.h</see>
	CanExecuteChromeCommand(commandId int32) bool
	// CanFocus
	// Indicates whether the browser can receive focus.
	CanFocus() bool
	// CanIncZoom
	// Returns true (1) if this browser can execute the zoom IN command.
	// This function can only be called on the CEF UI thread.
	CanIncZoom() bool
	// CanMakePayment
	// Browser preference used to enable saving information about payments.
	// Disabling this property is a suggested workaround for some autofill crashes in Alloy style.
	CanMakePayment() cefTypes.TCefState
	// CanResetZoom
	// Returns true (1) if this browser can execute the zoom RESET command.
	// This function can only be called on the CEF UI thread.
	CanResetZoom() bool
	// ChromeColorSchemeColor
	// Returns the current Chrome color scheme color, or transparent (0) for the
	// default color. Must be called on the browser process UI thread.
	ChromeColorSchemeColor() cefTypes.TCefColor
	// ChromeColorSchemeMode
	// Returns the current Chrome color scheme mode (SYSTEM, LIGHT or DARK). Must
	// be called on the browser process UI thread.
	ChromeColorSchemeMode() cefTypes.TCefColorVariant
	// ChromeColorSchemeVariant
	// Returns the current Chrome color scheme variant. Must be called on the
	// browser process UI thread.
	ChromeColorSchemeVariant() cefTypes.TCefColorVariant
	// ClearHttpCache
	// Clears the HTTP cache.
	// If aClearImmediately is false then OnHttpCacheCleared is triggered
	// when the http cache is cleared.
	ClearHttpCache(clearImmediately bool) bool
	// ClipboardPasteAndMatchStyle
	// Execute paste and match style on the focused frame.
	ClipboardPasteAndMatchStyle()
	// CreateUrlRequestWithRequestUClientStrX2
	// Create a new URL request that will be treated as originating from this
	// frame and the associated browser. Use TCustomCefUrlrequestClient.Create instead if
	// you do not want the request to have this association, in which case it may
	// be handled differently (see documentation on that function). A request
	// created with this function may only originate from the browser process,
	// and will behave as follows:
	// <code>
	// - It may be intercepted by the client via CefResourceRequestHandler or
	// CefSchemeHandlerFactory.
	// - POST data may only contain a single element of type PDE_TYPE_FILE or
	// PDE_TYPE_BYTES.
	// </code>
	// The |request| object will be marked as read-only after calling this
	// function.
	CreateUrlRequestWithRequestUClientStrX2(request ICefRequest, client IEngUrlrequestClient, frameName string, frameIdentifier string) ICefUrlRequest
	// CredentialsService
	// This service shows a dialog to save the usernames and passwords in Chrome style.
	CredentialsService() cefTypes.TCefState
	// DecZoomCommand
	// Execute a zoom OUT command in this browser. If called on the CEF UI thread the
	// change will be applied immediately. Otherwise, the change will be applied
	// asynchronously on the CEF UI thread.
	DecZoomCommand()
	// DefaultZoomLevel
	// Get the default zoom level. This value will be 0.0 by default but can be
	// configured. This function can only be called on the UI thread.
	DefaultZoomLevel() float64
	// DownloadBubble
	// Enable the file download bubble when using Chrome style.
	DownloadBubble() cefTypes.TCefState
	// EnableFocusDelayMs
	// Delay in milliseconds to enable browser focus.
	EnableFocusDelayMs() uint32
	// ExecuteChromeCommand
	// Returns true (1) if a Chrome command is supported and enabled. Use the
	// cef_id_for_command_id_name() function for version-safe mapping of command
	// IDC names from cef_command_ids.h to version-specific numerical
	// |command_id| values. This function can only be called on the UI thread.
	// Only used with Chrome style.
	// <see cref="uCEFConstants">See the IDC_* constants in uCEFConstants.pas for all the |command_id| values.</see>
	// <see href="https://source.chromium.org/chromium/chromium/src/+/main:chrome/app/chrome_command_ids.h">The command_id values are also available in chrome/app/chrome_command_ids.h</see>
	ExecuteChromeCommand(commandId int32, disposition cefTypes.TCefWindowOpenDisposition)
	// ExecuteJavaScriptWithStrX4Int
	// Execute a string of JavaScript code in the specified frame or the main frame.
	// <param name="aCode">JavaScript code.</param>
	// <param name="aScriptURL">The URL where the script in question can be found, if any. The renderer may request this URL to show the developer the source of the error.</param>
	// <param name="aFrameName">Name of the frame where the JavaScript code will be executed. This name is generated automatically by Chromium. See ICefBrowser.GetFrameNames.</param>
	// <param name="aFrameIdentifier">Identifier of the frame where the JavaScript code will be executed.</param>
	// <param name="aStartLine">The base line number to use for error reporting.</param>
	ExecuteJavaScriptWithStrX4Int(code string, scriptURL string, frameName string, frameIdentifier string, startLine int32)
	// ExitFullscreen
	// Requests the renderer to exit browser fullscreen. In most cases exiting
	// window fullscreen should also exit browser fullscreen. With Alloy style
	// this function should be called in response to a user action such as
	// clicking the green traffic light button on MacOS
	// (ICefWindowDelegate.OnWindowFullscreenTransition callback) or pressing
	// the "ESC" key (ICefKeyboardHandler.OnPreKeyEvent callback). With
	// Chrome style these standard exit actions are handled internally but
	// new/additional user actions can use this function. Set |will_cause_resize|
	// to true (1) if exiting browser fullscreen will cause a view resize.
	ExitFullscreen(willCauseResize bool)
	// Fullscreen
	// Returns true (1) if the renderer is currently in browser fullscreen. This
	// differs from window fullscreen in that browser fullscreen is entered using
	// the JavaScript Fullscreen API and modifies CSS attributes such as the
	// ::backdrop pseudo-element and :fullscreen pseudo-structure. This property
	// can only be called on the UI thread.
	Fullscreen() bool
	// GetComponentById
	// Returns the component with the specified |component_id|, or nullptr if not
	// found or the service is not available.
	// This function may only be called on the browser process UI thread.
	// <see href="https://bitbucket.org/chromiumembedded/cef/src/master/include/capi/cef_component_updater_capi.h">CEF source file: /include/capi/cef_component_updater_capi.h (cef_component_updater_t)</see>
	GetComponentById(componentId string, result *ICefComponent_147) bool
	// GetComponentCount
	// Returns the number of registered components, or 0 if the service is not
	// available.
	// This function may only be called on the browser process UI thread.
	// <see href="https://bitbucket.org/chromiumembedded/cef/src/master/include/capi/cef_component_updater_capi.h">CEF source file: /include/capi/cef_component_updater_capi.h (cef_component_updater_t)</see>
	GetComponentCount() cefTypes.NativeUInt
	// GetComponents
	// Populates |components_| with all registered components. Any existing
	// contents will be cleared first.
	// This function may only be called on the browser process UI thread.
	// <see href="https://bitbucket.org/chromiumembedded/cef/src/master/include/capi/cef_component_updater_capi.h">CEF source file: /include/capi/cef_component_updater_capi.h (cef_component_updater_t)</see>
	GetComponents(components *ICefComponentArray) bool
	// GetContentSetting
	// Returns the current value for |content_type| that applies for the
	// specified URLs. If both URLs are NULL the default value will be returned.
	// Returns CEF_CONTENT_SETTING_VALUE_DEFAULT if no value is configured. Must
	// be called on the browser process UI thread.
	GetContentSetting(requestingUrl string, topLevelUrl string, contentType cefTypes.TCefContentSettingTypes) cefTypes.TCefContentSettingValues
	// GetFrameIdentifiers
	// Returns the identifiers of all existing frames.
	GetFrameIdentifiers(frameIdentifiers *lcl.IStrings) bool
	// GetWebsiteSetting
	// Returns the current value for |content_type| that applies for the
	// specified URLs. If both URLs are NULL the default value will be returned.
	// Returns nullptr if no value is configured. Must be called on the browser
	// process UI thread.
	GetWebsiteSetting(requestingUrl string, topLevelUrl string, contentType cefTypes.TCefContentSettingTypes) ICefValue
	// HSTSPolicyBypassList
	// List of comma-delimited single-label hostnames that will skip the check to possibly upgrade from http to https.
	HSTSPolicyBypassList() string
	// HTTPSUpgrade
	// Automatically upgrade to HTTPS connections.
	HTTPSUpgrade() cefTypes.TCefState
	// IncZoomCommand
	// Execute a zoom IN command in this browser. If called on the CEF UI thread the
	// change will be applied immediately. Otherwise, the change will be applied
	// asynchronously on the CEF UI thread.
	IncZoomCommand()
	// IsReadyToBeClosed
	// Returns true (1) if the browser is ready to be closed, meaning that the
	// close has already been initiated and that JavaScript unload handlers have
	// already executed or should be ignored. This can be used from a top-level
	// window close handler such as TCEFWindowComponent.OnCanClose (or platform-
	// specific equivalent) to distringuish between potentially cancelable
	// browser close events (like the user clicking the top-level window close
	// button before browser close has started) and mandatory browser close
	// events (like JavaScript `window.close()` or after browser close has
	// started in response to [Try]CloseBrowser()). Not completing the browser
	// close for mandatory close events (when this function returns true (1))
	// will leave the browser in a partially closed state that interferes with
	// proper functioning. See CloseBrowser() documentation for additional usage
	// information. This function must be called on the browser process UI
	// thread.
	IsReadyToBeClosed() bool
	// IsRenderProcessUnresponsive
	// Returns true (1) if the render process associated with this browser is
	// currently unresponsive as indicated by a lack of input event processing
	// for at least 15 seconds. To receive associated state change notifications
	// and optionally handle an unresponsive render process implement
	// ICefRequestHandler.OnRenderProcessUnresponsive.
	// This property can only be read on the CEF UI thread.
	IsRenderProcessUnresponsive() bool
	// LoadResourceWithCMStreamStrX4
	// Used to load a DATA URI with the stream contents in the specified frame or the main frame.
	// The DATA URI will be configured with the mime type and charset specified in the parameters.
	LoadResourceWithCMStreamStrX4(stream lcl.ICustomMemoryStream, mimeType string, charset string, frameName string, frameIdentifier string)
	// LoadStringWithStrX3
	// Used to load a DATA URI with the HTML string contents in the specified frame or the main frame.
	LoadStringWithStrX3(hTML string, frameName string, frameIdentifier string)
	// LoadURLWithStrX3
	// Used to navigate to a URL in the specified frame or the main frame.
	LoadURLWithStrX3(uRL string, frameName string, frameIdentifier string)
	// OpenerIdentifier
	// Retrieve the unique identifier of the browser that opened this browser.
	// Will return 0 for non-popup browsers.
	OpenerIdentifier() int32
	// RemovePreferenceObserver
	// Remove an observer for preference changes.
	// <see href="https://bitbucket.org/chromiumembedded/cef/src/master/include/capi/cef_preference_capi.h">CEF source file: /include/capi/cef_preference_capi.h (cef_preference_manager_t)</see>
	RemovePreferenceObserver(name string)
	// ResetZoomCommand
	// Execute a zoom RESET command in this browser. If called on the CEF UI thread the
	// change will be applied immediately. Otherwise, the change will be applied
	// asynchronously on the CEF UI thread.
	ResetZoomCommand()
	// RetrieveHTMLWithStrX2
	// Retrieve all the HTML content from the specified frame or the main frame.
	// Leave aFrameName empty to get the HTML source from the main frame.
	// It uses a CefStringVisitor to get the HTML content asynchronously and the
	// result will be received in the TChromiumCore.OnTextResultAvailable event.
	RetrieveHTMLWithStrX2(frameName string, frameIdentifier string)
	// RetrieveTextWithStrX2
	// Retrieve all the text content from the specified frame or the main frame.
	// Leave aFrameName empty to get the text from the main frame.
	// It uses a CefStringVisitor to get the text asynchronously and the
	// result will be received in the TChromiumCore.OnTextResultAvailable event.
	RetrieveTextWithStrX2(frameName string, frameIdentifier string)
	// RuntimeStyle
	// Returns the runtime style for this browser (ALLOY or CHROME). See
	// TCefRuntimeStyle documentation for details.
	// This property can only be read on the CEF UI thread.
	RuntimeStyle() cefTypes.TCefRuntimeStyle
	// SearchSuggestEnabled
	// Browser preference used to enable search suggestions.
	// Disabling this property is a suggested workaround for some autofill crashes in Alloy style.
	SearchSuggestEnabled() cefTypes.TCefState
	// SendProcessMessageWithPIdPMessageStrX2
	// Send a message to the specified |targetProcess|. Ownership of the message
	// contents will be transferred and the |ProcMessage| reference will be
	// invalidated. Message delivery is not guaranteed in all cases (for example,
	// if the browser is closing, navigating, or if the target process crashes).
	// Send an ACK message back from the target process if confirmation is
	// required.
	SendProcessMessageWithPIdPMessageStrX2(targetProcess cefTypes.TCefProcessId, procMessage ICefProcessMessage, frameName string, frameIdentifier string)
	SetAutofillCreditCard(value cefTypes.TCefState)
	SetAutofillProfile(value cefTypes.TCefState)
	SetAutofillSaveData(value cefTypes.TCefState)
	// SetAxViewportCollapse
	// Enable or disable CDP accessibility tree viewport collapse for this
	// browser. When enabled, off-screen landmarks and headings are serialized as
	// summaries and other off-screen nodes are pruned. Overrides the
	// TChromiumOptions.AxViewportCollapse value. If called on the UI
	// thread the change will be applied immediately. Otherwise, the change will
	// be applied asynchronously on the UI thread. WARNING: This collapses the
	// CDP accessibility tree and disables CDP dynamic tree updates (nodesUpdated
	// events). The DevTools Accessibility panel will show an incomplete tree.
	// Platform screen readers (NVDA, JAWS, VoiceOver) are unaffected they use
	// a separate code path.
	SetAxViewportCollapse(enabled bool)
	SetCanMakePayment(value cefTypes.TCefState)
	// SetChromeColorScheme
	// Sets the Chrome color scheme for all browsers that share this request
	// context. |variant| values of SYSTEM, LIGHT and DARK change the underlying
	// color mode (e.g. light vs dark). Other |variant| values determine how
	// |user_color| will be applied in the current color mode. If |user_color| is
	// transparent (0) the default color will be used.
	SetChromeColorScheme(variant cefTypes.TCefColorVariant, userColor cefTypes.TCefColor)
	// SetContentSetting
	// Sets the current value for |content_type| for the specified URLs in the
	// default scope. If both URLs are NULL, and the context is not incognito,
	// the default value will be set. Pass CEF_CONTENT_SETTING_VALUE_DEFAULT for
	// |value| to use the default value for this content type.
	// WARNING: Incorrect usage of this function may cause instability or
	// security issues in Chromium. Make sure that you first understand the
	// potential impact of any changes to |content_type| by reviewing the related
	// source code in Chromium. For example, if you plan to modify
	// CEF_CONTENT_SETTING_TYPE_POPUPS, first review and understand the usage of
	// ContentSettingsType::POPUPS in Chromium:
	// https://source.chromium.org/search?q=ContentSettingsType::POPUPS
	SetContentSetting(requestingUrl string, topLevelUrl string, contentType cefTypes.TCefContentSettingTypes, value cefTypes.TCefContentSettingValues)
	SetCredentialsService(value cefTypes.TCefState)
	SetDownloadBubble(value cefTypes.TCefState)
	SetEnableFocusDelayMs(value uint32)
	SetHSTSPolicyBypassList(value string)
	SetHTTPSUpgrade(value cefTypes.TCefState)
	SetOnBeforeDevToolsPopup(fn TOnBeforeDevToolsPopup)
	SetOnBeforePopupAborted(fn TOnBeforePopupAborted)
	SetOnCanFocus(fn TNotifyEvent)
	SetOnComponentUpdateCompleted(fn TOnComponentUpdateCompletedEvent)
	SetOnContentsBoundsChange(fn TOnContentsBoundsChange)
	SetOnFrameDestroyed(fn TOnFrameDestroyed)
	SetOnGetRootWindowScreenRect(fn TOnGetRootWindowScreenRect)
	SetOnHttpCacheCleared(fn TNotifyEvent)
	SetOnIsChromeAppMenuItemEnabled(fn TOnIsChromeAppMenuItemEnabledEvent)
	SetOnIsChromeAppMenuItemVisible(fn TOnIsChromeAppMenuItemVisibleEvent)
	SetOnIsChromePageActionIconVisible(fn TOnIsChromePageActionIconVisibleEvent)
	SetOnIsChromeToolbarButtonVisible(fn TOnIsChromeToolbarButtonVisibleEvent)
	SetOnPreferenceChanged(fn TOnPreferenceChangedEvent)
	SetOnRenderProcessResponsive(fn TOnRenderProcessResponsive)
	SetOnRenderProcessUnresponsive(fn TOnRenderProcessUnresponsive)
	SetOnSettingChanged(fn TOnSettingChangedEvent)
	SetRuntimeStyle(value cefTypes.TCefRuntimeStyle)
	SetSearchSuggestEnabled(value cefTypes.TCefState)
	SetStorageNotificationService(value cefTypes.TCefState)
	SetURLDataCollection(value cefTypes.TCefState)
	// SetWebsiteSetting
	// Sets the current value for |content_type| for the specified URLs in the
	// default scope. If both URLs are NULL, and the context is not incognito,
	// the default value will be set. Pass nullptr for |value| to remove the
	// default value for this content type.
	// WARNING: Incorrect usage of this function may cause instability or
	// security issues in Chromium. Make sure that you first understand the
	// potential impact of any changes to |content_type| by reviewing the related
	// source code in Chromium. For example, if you plan to modify
	// CEF_CONTENT_SETTING_TYPE_POPUPS, first review and understand the usage of
	// ContentSettingsType::POPUPS in Chromium:
	// https://source.chromium.org/search?q=ContentSettingsType::POPUPS
	SetWebsiteSetting(requestingUrl string, topLevelUrl string, contentType cefTypes.TCefContentSettingTypes, value ICefValue)
	// SimulateEditingCommand
	// Simulate editing commands using the "Input.dispatchKeyEvent" DevTools method.
	// <see href="https://chromedevtools.github.io/devtools-protocol/1-3/Input/#method-dispatchKeyEvent">See the "Input.dispatchKeyEvent" DevTools method.</see>
	// <see href="https://source.chromium.org/chromium/chromium/src/+/master:third_party/blink/renderer/core/editing/commands/editor_command_names.h">See the Chromium sources.</see>
	SimulateEditingCommand(command cefTypes.TCefEditingCommand)
	// SimulateKeyEvent
	// Dispatches a key event to the page using the "Input.dispatchKeyEvent"
	// DevTools method. The browser has to be focused before simulating any
	// key event.
	// <param name="type_">Type of the key event.</param>
	// <param name="modifiers">Bit field representing pressed modifier keys. Alt=1, Ctrl=2, Meta/Command=4, Shift=8.(default: 0).</param>
	// <param name="timestamp">Time at which the event occurred.</param>
	// <param name="text">Text as generated by processing a virtual key code with a keyboard layout. Not needed for for keyUp and rawKeyDown events.(default: "")</param>
	// <param name="unmodifiedtext">Text that would have been generated by the keyboard if no modifiers were pressed (except for shift). Useful for shortcut (accelerator) key handling.(default: "").</param>
	// <param name="keyIdentifier">Unique key identifier (e.g., 'U+0041').(default: "").</param>
	// <param name="code">Unique DOM defined string value for each physical key (e.g., 'KeyA').(default: "").</param>
	// <param name="key">Unique DOM defined string value describing the meaning of the key in the context of active modifiers, keyboard layout, etc (e.g., 'AltGr').(default: "").</param>
	// <param name="windowsVirtualKeyCode">Windows virtual key code.(default: 0).</param>
	// <param name="nativeVirtualKeyCode">Native virtual key code.(default: 0).</param>
	// <param name="autoRepeat">Whether the event was generated from auto repeat.(default: false).</param>
	// <param name="isKeypad">Whether the event was generated from the keypad.(default: false).</param>
	// <param name="isSystemKey">Whether the event was a system key event.(default: false).</param>
	// <param name="location">Whether the event was from the left or right side of the keyboard. 1=Left, 2=Right.(default: 0).</param>
	// <param name="commands">Editing commands to send with the key event (e.g., 'selectAll') (default: []). These are related to but not equal the command names used in document.execCommand and NSStandardKeyBindingResponding. See https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/editing/commands/editor_command_names.h for valid command names.</param>
	// <see href="https://chromedevtools.github.io/devtools-protocol/1-3/Input/#method-dispatchKeyEvent">See the "Input.dispatchKeyEvent" DevTools method.</see>
	SimulateKeyEvent(args TChromiumCoreSimulateKeyEventArgs)
	// SimulateMouseEvent
	// Dispatches a key event to the page using the "Input.dispatchKeyEvent"
	// DevTools method. The browser has to be focused before simulating any
	// key event.
	// <param name="type_">Type of the mouse event.</param>
	// <param name="x">X coordinate of the event relative to the main frame's viewport in CSS pixels.</param>
	// <param name="y">Y coordinate of the event relative to the main frame's viewport in CSS pixels. 0 refers to the top of the viewport and Y increases as it proceeds towards the bottom of the viewport.</param>
	// <param name="modifiers">Bit field representing pressed modifier keys. Alt=1, Ctrl=2, Meta/Command=4, Shift=8 (default: 0). See the CEF_MOUSETOUCH_EVENT_MODIFIERS_* constants.</param>
	// <param name="timestamp">Time at which the event occurred.</param>
	// <param name="button">Mouse button (default: "none").</param>
	// <param name="buttons">A number indicating which buttons are pressed on the mouse when a mouse event is triggered. Left=1, Right=2, Middle=4, Back=8, Forward=16, None=0.</param>
	// <param name="clickCount">Number of times the mouse button was clicked (default: 0).</param>
	// <param name="force">The normalized pressure, which has a range of [0,1] (default: 0). </param>
	// <param name="tangentialPressure">The normalized tangential pressure, which has a range of [-1,1] (default: 0).</param>
	// <param name="tiltX">The plane angle between the Y-Z plane and the plane containing both the stylus axis and the Y axis, in degrees of the range [-90,90], a positive tiltX is to the right (default: 0).</param>
	// <param name="tiltY">The plane angle between the X-Z plane and the plane containing both the stylus axis and the X axis, in degrees of the range [-90,90], a positive tiltY is towards the user (default: 0).</param>
	// <param name="twist">The clockwise rotation of a pen stylus around its own major axis, in degrees in the range [0,359] (default: 0).</param>
	// <param name="deltaX">X delta in CSS pixels for mouse wheel event (default: 0).</param>
	// <param name="deltaY">Y delta in CSS pixels for mouse wheel event (default: 0).</param>
	// <param name="pointerType">Pointer type (default: "mouse").</param>
	// <see href="https://chromedevtools.github.io/devtools-protocol/1-3/Input/#method-dispatchKeyEvent">See the "Input.dispatchKeyEvent" DevTools method.</see>
	SimulateMouseEvent(args TChromiumCoreSimulateMouseEventArgs)
	// StorageNotificationService
	// Used to disable the "Free up space to continue" notification for the current profile.
	StorageNotificationService() cefTypes.TCefState
	// URLDataCollection
	// Browser preference used to enable url keyed anonymized data collection.
	// Disabling this property is a suggested workaround for some autofill crashes in Alloy style.
	URLDataCollection() cefTypes.TCefState
	// UpdateComponent
	// Triggers an on-demand update for the component with the specified
	// |component_id|. |priority| specifies whether the update should be
	// processed in the background or foreground. Use
	// CEF_COMPONENT_UPDATE_PRIORITY_FOREGROUND for user-initiated updates.
	// TChromiumCore.OnComponentUpdateCompleted will be triggered
	// asynchronously on the UI thread when the update
	// operation completes. The event is always executed, including when the
	// component is already up-to-date (returns CEF_COMPONENT_UPDATE_ERROR_NONE),
	// when the requested component doesn't exist, or when the service is
	// unavailable (returns CEF_COMPONENT_UPDATE_ERROR_SERVICE_ERROR).
	// This function may only be called on the browser process UI thread.
	// <see href="https://bitbucket.org/chromiumembedded/cef/src/master/include/capi/cef_component_updater_capi.h">CEF source file: /include/capi/cef_component_updater_capi.h (cef_component_updater_t)</see>
	UpdateComponent(componentId string, priority cefTypes.TCefComponentUpdatePriority)
}

type IChromiumOptions_147 interface {
	IChromiumOptions
	// AxViewportCollapse
	// Controls whether CDP accessibility tree serialization collapses off-screen
	// nodes. When enabled, off-screen landmarks and headings are serialized as
	// summaries (role + name only) and other off-screen nodes are pruned.
	// This reduces snapshot size for AI agents using Playwright ariaSnapshot().
	// WARNING: This collapses the CDP accessibility tree and disables CDP
	// dynamic tree updates (nodesUpdated events). The DevTools Accessibility
	// panel will show an incomplete tree. Platform screen readers (NVDA, JAWS,
	// VoiceOver) are unaffected they use a separate code path.
	// Can also be configured at runtime using
	// ICefBrowserHost.SetAxViewportCollapse.
	AxViewportCollapse() cefTypes.TCefState
	// ChromeZoomBubble
	// Controls whether the Chrome zoom bubble will be shown when zooming. Only
	// supported with Chrome style.
	ChromeZoomBubble() cefTypes.TCefState
	SetAxViewportCollapse(value cefTypes.TCefState)
	SetChromeZoomBubble(value cefTypes.TCefState)
}

type IChromiumWindow_147 interface {
	IChromiumWindow
	ICEFLinkedWinControlBase_147
}

type IEngBrowserProcessHandler_147 interface {
	IEngBrowserProcessHandler
	SetOnBrowserProcessAlreadyRunningAppRelaunch(fn TOnBrowserProcessAlreadyRunningAppRelaunchEvent)
	SetOnBrowserProcessGetDefaultRequestContextHandler(fn TOnBrowserProcessGetDefaultRequestContextHandlerEvent)
}

type IEngBrowserViewDelegate_147 interface {
	IEngBrowserViewDelegate
	SetOnBrowserViewAllowMoveForPictureInPicture(fn TOnBrowserViewAllowMoveForPictureInPictureEvent)
	SetOnBrowserViewAllowPictureInPictureWithoutUserActivation(fn TOnBrowserViewAllowPictureInPictureWithoutUserActivationEvent)
	SetOnBrowserViewGestureCommand(fn TOnBrowserViewGestureCommandEvent)
	SetOnBrowserViewGetBrowserRuntimeStyle(fn TOnBrowserViewGetBrowserRuntimeStyleEvent)
	SetOnBrowserViewUseFramelessWindowForPictureInPicture(fn TOnBrowserViewUseFramelessWindowForPictureInPictureEvent)
}

type IEngCommandHandler_147 interface {
	IEngCommandHandler
	SetOnCommandIsChromeAppMenuItemEnabled(fn TOnCommandIsChromeAppMenuItemEnabledEvent)
	SetOnCommandIsChromeAppMenuItemVisible(fn TOnCommandIsChromeAppMenuItemVisibleEvent)
	SetOnCommandIsChromePageActionIconVisible(fn TOnCommandIsChromePageActionIconVisibleEvent)
	SetOnCommandIsChromeToolbarButtonVisible(fn TOnCommandIsChromeToolbarButtonVisibleEvent)
}

type IEngDisplayHandler_147 interface {
	IEngDisplayHandler
	SetOnDisplayContentsBoundsChange(fn TOnDisplayContentsBoundsChangeEvent)
	SetOnDisplayGetRootWindowScreenRect(fn TOnDisplayGetRootWindowScreenRectEvent)
}

type IEngFrameHandler_147 interface {
	IEngFrameHandler
	SetOnFrameFrameDestroyed(fn TOnFrameFrameDestroyedEvent)
}

type IEngLifeSpanHandler_147 interface {
	IEngLifeSpanHandler
	SetOnLifeSpanBeforeDevToolsPopup(fn TOnLifeSpanBeforeDevToolsPopupEvent)
	SetOnLifeSpanBeforePopupAborted(fn TOnLifeSpanBeforePopupAbortedEvent)
}

type IEngPreferenceObserver_147 interface {
	ICefPreferenceObserverOwn_147
	AsIntfPreferenceObserver() uintptr
	SetOnPreferenceObserverPreferenceChanged(fn TOnPreferenceObserverPreferenceChangedEvent)
}

type IEngRequestHandler_147 interface {
	IEngRequestHandler
	SetOnRequestRenderProcessResponsive(fn TOnRequestRenderProcessResponsiveEvent)
	SetOnRequestRenderProcessUnresponsive(fn TOnRequestRenderProcessUnresponsiveEvent)
}

type IEngSettingObserver_147 interface {
	ICefSettingObserverOwn_147
	AsIntfSettingObserver() uintptr
	SetOnSettingObserverSettingChanged(fn TOnSettingObserverSettingChangedEvent)
}

type IEngViewDelegate_147 interface {
	IEngViewDelegate
	SetOnViewThemeChanged(fn TOnViewThemeChangedEvent)
}

type IEngWindowDelegate_147 interface {
	IEngWindowDelegate
	SetOnWindowAcceptsFirstMouse(fn TOnWindowAcceptsFirstMouseEvent)
	SetOnWindowGetLinuxWindowProperties(fn TOnWindowGetLinuxWindowPropertiesEvent)
	SetOnWindowGetTitlebarHeight(fn TOnWindowGetTitlebarHeightEvent)
	SetOnWindowGetWindowRuntimeStyle(fn TOnWindowGetWindowRuntimeStyleEvent)
	SetOnWindowIsWindowModalDialog(fn TOnWindowIsWindowModalDialogEvent)
	SetOnWindowThemeColorsChanged(fn TOnWindowThemeColorsChangedEvent)
	SetOnWindowWindowFullscreenTransition(fn TOnWindowWindowFullscreenTransitionEvent)
	SetOnWindowWithStandardWindowButtons(fn TOnWindowWithStandardWindowButtonsEvent)
}

type IPDFPrintOptions_147 interface {
	IPDFPrintOptions
	// GenerateDocumentOutline
	// Set to true to generate a document outline.
	GenerateDocumentOutline() bool
	// GenerateTaggedPDF
	// Set to true to generate tagged (accessible) PDF.
	GenerateTaggedPDF() bool
	SetGenerateDocumentOutline(value bool)
	SetGenerateTaggedPDF(value bool)
}
