// Code generated by cefgen. DO NOT EDIT.
//
//----------------------------------------
//
// Copyright © yanghy. All Rights Reserved.
//
// Licensed under Apache License 2.0
//
//----------------------------------------

//go:build CEF127

package cef

import (
	cefTypes "github.com/energye/cef/cef/types"
	"github.com/energye/lcl/lcl"
	"github.com/energye/lcl/types"
)

type IApplicationCoreEvents_127 interface {
	IObject
}

type ICEFBrowserViewComponent_127 interface {
	ICEFBrowserViewComponent
	ICEFViewComponent_127
	// RuntimeStyle
	// Returns the runtime style for this BrowserView (ALLOY or CHROME). See
	// TCefRuntimeStyle documentation for details.
	RuntimeStyle() cefTypes.TCefRuntimeStyle
	SetOnGestureCommand(fn TOnGestureCommandEvent)
	SetOnGetBrowserRuntimeStyle(fn TOnGetBrowserRuntimeStyleEvent)
	SetOnUseFramelessWindowForPictureInPicture(fn TOnUseFramelessWindowForPictureInPicture)
}

type ICEFButtonComponent_127 interface {
	ICEFButtonComponent
	ICEFViewComponent_127
}

type ICEFFileDialogInfo_127 interface {
	ICEFFileDialogInfo
	SetAcceptDescriptions(value lcl.IStrings)
	SetAcceptExtensions(value lcl.IStrings)
}

type ICEFLabelButtonComponent_127 interface {
	ICEFLabelButtonComponent
	ICEFButtonComponent_127
}

type ICEFLinkedWinControlBase_127 interface {
	ICEFLinkedWinControlBase
	SetUseSetFocus(value bool)
	// UseSetFocus
	// Use TChromium.SetFocus when the component receives a WM_SETFOCUS message in Windows.
	UseSetFocus() bool
}

type ICEFLinkedWindowParent_127 interface {
	ICEFLinkedWindowParent
	ICEFLinkedWinControlBase_127
}

type ICEFMenuButtonComponent_127 interface {
	ICEFMenuButtonComponent
	ICEFLabelButtonComponent_127
}

type ICEFPanelComponent_127 interface {
	ICEFPanelComponent
	ICEFViewComponent_127
	// ChildViewCount
	// Returns the number of child Views.
	ChildViewCount() cefTypes.NativeUInt
}

type ICEFScrollViewComponent_127 interface {
	ICEFScrollViewComponent
	ICEFViewComponent_127
}

type ICEFTextfieldComponent_127 interface {
	ICEFTextfieldComponent
	ICEFViewComponent_127
	// CursorPosition
	// Returns the current cursor position.
	CursorPosition() cefTypes.NativeUInt
	// SelectedRange
	// Returns the selected logical text range.
	SelectedRange() TCefRange
	SetSelectedRange(value TCefRange)
}

type ICEFViewComponent_127 interface {
	ICEFViewComponent
	// GetThemeColor
	// Returns the current theme color associated with |color_id|, or the
	// placeholder color (red) if unset. See cef_color_ids.h for standard ID
	// values. Standard colors can be overridden and custom colors can be added
	// using ICefWindow.SetThemeColor.
	GetThemeColor(colorId int32) cefTypes.TCefColor
	// Insets
	// Returns the insets for this View in parent coordinates, or DIP screen
	// coordinates if there is no parent.
	Insets() TCefInsets
	SetInsets(value TCefInsets)
	SetOnThemeChanged(fn TOnThemeChangedEvent)
}

type ICEFWindowComponent_127 interface {
	ICEFWindowComponent
	ICEFPanelComponent_127
	// AddOverlayView
	// Add a View that will be overlayed on the Window contents with absolute
	// positioning and high z-order. Positioning is controlled by |docking_mode|
	// as described below. Setting |can_activate| to true (1) will allow the
	// overlay view to receive input focus. The returned cef_overlay_controller_t
	// object is used to control the overlay. Overlays are hidden by default.
	// With CEF_DOCKING_MODE_CUSTOM:
	// <code>
	// 1. The overlay is initially hidden, sized to |view|'s preferred size,
	// and positioned in the top-left corner.
	// 2. Optionally change the overlay position and/or size by calling
	// CefOverlayController methods.
	// 3. Call CefOverlayController::SetVisible(true) to show the overlay.
	// 4. The overlay will be automatically re-sized if |view|'s layout
	// changes. Optionally change the overlay position and/or size when
	// OnLayoutChanged is called on the Window's delegate to indicate a
	// change in Window bounds.</code>
	// With other docking modes:
	// <code>
	// 1. The overlay is initially hidden, sized to |view|'s preferred size,
	// and positioned based on |docking_mode|.
	// 2. Call CefOverlayController::SetVisible(true) to show the overlay.
	// 3. The overlay will be automatically re-sized if |view|'s layout changes
	// and re-positioned as appropriate when the Window resizes.</code>
	// Overlays created by this function will receive a higher z-order then any
	// child Views added previously. It is therefore recommended to call this
	// function last after all other child Views have been added so that the
	// overlay displays as the top-most child of the Window.
	AddOverlayView(view ICefView, dockingMode cefTypes.TCefDockingMode, canActivate bool) ICefOverlayController
	// RuntimeStyle
	// Returns the runtime style for this Window (ALLOY or CHROME). See
	// TCefRuntimeStyle documentation for details.
	RuntimeStyle() cefTypes.TCefRuntimeStyle
	// SetAccelerator
	// Set the keyboard accelerator for the specified |command_id|. |key_code|
	// can be any virtual key or character value. Required modifier keys are
	// specified by |shift_pressed|, |ctrl_pressed| and/or |alt_pressed|.
	// ICefWindowDelegate.OnAccelerator will be called if the keyboard
	// combination is triggered while this window has focus.
	// The |high_priority| value will be considered if a child ICefBrowserView
	// has focus when the keyboard combination is triggered. If |high_priority|
	// is true (1) then the key event will not be forwarded to the web content
	// (`keydown` event handler) or ICefKeyboardHandler first. If
	// |high_priority| is false (0) then the behavior will depend on the
	// ICefBrowserView.SetPreferAccelerators configuration.
	SetAccelerator(commandId int32, keyCode int32, shiftPressed bool, ctrlPressed bool, altPressed bool, highPriority bool)
	SetOnAcceptsFirstMouse(fn TOnAcceptsFirstMouseEvent)
	SetOnGetTitlebarHeight(fn TOnGetTitlebarHeightEvent)
	SetOnGetWindowRuntimeStyle(fn TOnGetWindowRuntimeStyleEvent)
	SetOnIsWindowModalDialog(fn TOnIsWindowModalDialogEvent)
	SetOnThemeColorsChanged(fn TOnThemeColorsChangedEvent)
	SetOnWindowFullscreenTransition(fn TOnWindowFullscreenTransitionEvent)
	SetOnWithStandardWindowButtons(fn TOnWithStandardWindowButtonsEvent)
	// SetThemeColor
	// Override a standard theme color or add a custom color associated with
	// |color_id|. See cef_color_ids.h for standard ID values. Recommended usage
	// is as follows:
	// <code>
	// 1. Customize the default native/OS theme by calling SetThemeColor before
	// showing the first Window. When done setting colors call
	// ICefWindow.ThemeChanged to trigger ICefViewDelegate.OnThemeChanged
	// notifications.
	// 2. Customize the current native/OS or Chrome theme after it changes by
	// calling SetThemeColor from the ICefWindowDelegate.OnThemeColorsChanged
	// callback. ICefViewDelegate.OnThemeChanged notifications will then be
	// triggered automatically.
	// </code>
	// The configured color will be available immediately via
	// ICefView.GetThemeColor and will be applied to each View in this
	// Window's component hierarchy when ICefViewDelegate.OnThemeChanged is
	// called. See OnThemeColorsChanged documentation for additional details.
	// Clients wishing to add custom colors should use |color_id| values >=
	// CEF_ChromeColorsEnd.
	SetThemeColor(colorId int32, color cefTypes.TCefColor)
	// ShowAsBrowserModalDialog
	// Show the Window as a browser modal dialog relative to |browser_view|. A
	// parent Window must be returned via
	// ICefWindowDelegate.OnGetParentWindow and |browser_view| must belong
	// to that parent Window. While this Window is visible, |browser_view| will
	// be disabled while other controls in the parent Window remain enabled.
	// Navigating or destroying the |browser_view| will close this Window
	// automatically. Alternately, use show() and return true (1) from
	// ICefWindowDelegate.OnIsWindowModalDialog for a window modal dialog
	// where all controls in the parent Window are disabled.
	ShowAsBrowserModalDialog(browserView ICefBrowserView)
	// ThemeChanged
	// Trigger ICefViewDelegate.OnThemeChanged callbacks for each View in
	// this Window's component hierarchy. Unlike a native/OS or Chrome theme
	// change this function does not reset theme colors to standard values and
	// does not result in a call to ICefWindowDelegate.OnThemeColorsChanged.
	// Do not call this function from ICefWindowDelegate.OnThemeColorsChanged
	// or ICefViewDelegate.OnThemeChanged.
	ThemeChanged()
}

type ICefApplication_127 interface {
	ICefApplication
	ICefApplicationCore_127
	IInterfacedObject
	AsIntfApplicationCoreEvents() uintptr
}

type ICefApplicationCore_127 interface {
	ICefApplicationCore
	IApplicationCoreEvents_127
	IInterfacedObject
	// ApiHashUniversal
	// Calls cef_api_hash to get the universal hash.
	ApiHashUniversal() string
	AsIntfApplicationCoreEvents() uintptr
	// AutoAcceptCamAndMicCapture
	// Bypasses the dialog prompting the user for permission to capture cameras and microphones.
	// Useful in automatic tests of video-conferencing Web applications. This is nearly
	// identical to kUseFakeUIForMediaStream, with the exception being that this flag does NOT
	// affect screen-capture.
	// <see href="https://peter.sh/experiments/chromium-command-line-switches/">Uses the following command line switch: --auto-accept-camera-and-microphone-capture</see>
	AutoAcceptCamAndMicCapture() bool
	// ChromeAppIconId
	// Specify an ID for an ICON resource that can be loaded from the main
	// executable and used when creating default Chrome windows such as DevTools
	// and Task Manager. If unspecified the default Chromium ICON (IDR_MAINFRAME
	// [101]) will be loaded from libcef.dll. Only supported with the Chrome
	// runtime on Windows.
	ChromeAppIconId() int32
	// ChromePolicyId
	// Specify an ID to enable Chrome policy management via Platform and OS-user
	// policies. On Windows, this is a registry key like
	// "SOFTWARE\\Policies\\Google\\Chrome". On MacOS, this is a bundle ID like
	// "com.google.Chrome". On Linux, this is an absolute directory path like
	// "/etc/opt/chrome/policies". Only supported with the Chrome runtime. See
	// https://support.google.com/chrome/a/answer/9037717 for details.
	// Chrome Browser Cloud Management integration, when enabled via the
	// "enable-chrome-browser-cloud-management" command-line flag, will also use
	// the specified ID. See https://support.google.com/chrome/a/answer/9116814
	// for details.
	ChromePolicyId() string
	// ChromeRuntime
	// Set to true (1) to enable use of the Chrome runtime in CEF. This feature
	// is considered experimental and is not recommended for most users at this
	// time. See issue #2969 for details.
	ChromeRuntime() bool
	// DisableHangMonitor
	// Suppresses hang monitor dialogs in renderer processes. This may allow slow unload handlers on a page to prevent the tab from closing, but the Task Manager can be used to terminate the offending process in this case.
	// <see href="https://peter.sh/experiments/chromium-command-line-switches/">Uses the following command line switch: --disable-hang-monitor</see>
	DisableHangMonitor() bool
	// ExitCode
	// This property can optionally be read on the main application thread after
	// CefInitialize to retrieve the initialization exit code. When CefInitialize
	// returns true (1) the exit code will be 0 (CEF_RESULT_CODE_NORMAL_EXIT).
	// Otherwise, see TCefResultCode for possible exit code values including
	// browser process initialization errors and normal early exit conditions (such
	// as CEF_RESULT_CODE_NORMAL_EXIT_PROCESS_NOTIFIED for process singleton
	// relaunch behavior).
	ExitCode() cefTypes.TCefResultCode
	// HideCrashRestoreBubble
	// Does not show the "Restore pages" popup bubble after incorrect shutdown.
	// <see href="https://peter.sh/experiments/chromium-command-line-switches/">Uses the following command line switch: --hide-crash-restore-bubble</see>
	HideCrashRestoreBubble() bool
	// LogItems
	// The log items prepended to each log line. If not set the default log items
	// will be used. Also configurable using the "log-items" command-line switch
	// with a value of "none" for no log items, or a comma-delimited list of
	// values "pid", "tid", "timestamp" or "tickcount" for custom log items.
	LogItems() cefTypes.TCefLogItems
	// NextComponentID
	// Returns the next component ID and adds this value to the valid ID list.
	NextComponentID() int32
	// PackLoadingDisabled
	// Set to true (1) to disable loading of pack files for resources and
	// locales. A resource bundle handler must be provided for the browser and
	// render processes via ICefApp.GetResourceBundleHandler() if loading of pack
	// files is disabled. Also configurable using the "disable-pack-loading"
	// command- line switch.
	PackLoadingDisabled() bool
	// PersistUserPreferences
	// To persist user preferences as a JSON file in the cache path directory set
	// this value to true (1). A |cache_path| value must also be specified
	// to enable this feature. Also configurable using the
	// "persist-user-preferences" command-line switch. Can be overridden for
	// individual CefRequestContext instances via the
	// TCefRequestContextSettings.persist_user_preferences value.
	PersistUserPreferences() bool
	// RemoteAllowOrigins
	// Enables web socket connections from the specified origins only. '*' allows any origin.
	// <see href="https://peter.sh/experiments/chromium-command-line-switches/">Uses the following command line switch: --remote-allow-origins</see>
	RemoteAllowOrigins() string
	// RemoveComponentID
	// Removes a component ID from the valid ID list when a component is destroyed.
	RemoveComponentID(componentID int32)
	SetAutoAcceptCamAndMicCapture(value bool)
	SetChromeAppIconId(value int32)
	SetChromePolicyId(value string)
	SetChromeRuntime(value bool)
	SetDisableHangMonitor(value bool)
	SetHideCrashRestoreBubble(value bool)
	SetLogItems(value cefTypes.TCefLogItems)
	SetOnAlreadyRunningAppRelaunch(fn TOnAlreadyRunningAppRelaunchEvent)
	SetOnGetDefaultRequestContextHandler(fn TOnGetDefaultRequestContextHandlerEvent)
	SetPackLoadingDisabled(value bool)
	SetPersistUserPreferences(value bool)
	SetRemoteAllowOrigins(value string)
	SetUIColorMode(value cefTypes.TCefUIColorMode)
	// UIColorMode
	// Forces light or dark mode in UI for platforms that support it.
	// <see href="https://peter.sh/experiments/chromium-command-line-switches/">Uses the following command line switches: --force-dark-mode --force-light-mode</see>
	UIColorMode() cefTypes.TCefUIColorMode
	// ValidComponentID
	// Returns true if a custom component ID is valid before executing a CEF task.
	ValidComponentID(componentID int32) bool
}

type ICefBinaryValue_127 interface {
	ICefBinaryValue
	// GetRawData
	// Returns a pointer to the beginning of the memory block. The returned
	// pointer is valid as long as the ICefBinaryValue is alive.
	GetRawData() uintptr
}

type ICefBinaryValueRef_127 interface {
	ICefBinaryValueRef
	ICefBinaryValue_127
}

type ICefBrowser_127 interface {
	ICefBrowser
	// GetFrameByIdentifier
	// Returns the frame with the specified identifier, or NULL if not found.
	GetFrameByIdentifier(identifier string) ICefFrame
	// GetFrameByName
	// Returns the frame with the specified name, or NULL if not found.
	GetFrameByName(name string) ICefFrame
	// GetFrameIdentifiers
	// Returns the identifiers of all existing frames.
	GetFrameIdentifiers(frameIdentifiers *lcl.IStrings) bool
}

type ICefBrowserHost_127 interface {
	ICefBrowserHost
	// CanExecuteChromeCommand
	// Returns true (1) if a Chrome command is supported and enabled. Values for
	// |command_id| can be found in the cef_command_ids.h file. This function can
	// only be called on the UI thread. Only used with the Chrome runtime.
	// <see cref="uCEFConstants">See the IDC_* constants in uCEFConstants.pas for all the |command_id| values.</see>
	// <see href="https://source.chromium.org/chromium/chromium/src/+/main:chrome/app/chrome_command_ids.h">The command_id values are also available in chrome/app/chrome_command_ids.h</see>
	CanExecuteChromeCommand(commandId int32) bool
	// CanZoom
	// Returns true (1) if this browser can execute the specified zoom command.
	// This function can only be called on the UI thread.
	CanZoom(command cefTypes.TCefZoomCommand) bool
	// ExecuteChromeCommand
	// Execute a Chrome command. Values for |command_id| can be found in the
	// cef_command_ids.h file. |disposition| provides information about the
	// intended command target. Only used with the Chrome runtime.
	// <see cref="uCEFConstants">See the IDC_* constants in uCEFConstants.pas for all the |command_id| values.</see>
	// <see href="https://source.chromium.org/chromium/chromium/src/+/main:chrome/app/chrome_command_ids.h">The command_id values are also available in chrome/app/chrome_command_ids.h</see>
	ExecuteChromeCommand(commandId int32, disposition cefTypes.TCefWindowOpenDisposition)
	// ExitFullscreen
	// Requests the renderer to exit browser fullscreen. In most cases exiting
	// window fullscreen should also exit browser fullscreen. With the Alloy
	// runtime this function should be called in response to a user action such
	// as clicking the green traffic light button on MacOS
	// (ICefWindowDelegate.OnWindowFullscreenTransition callback) or pressing
	// the "ESC" key (ICefKeyboardHandler.OnPreKeyEvent callback). With the
	// Chrome runtime these standard exit actions are handled internally but
	// new/additional user actions can use this function. Set |will_cause_resize|
	// to true (1) if exiting browser fullscreen will cause a view resize.
	ExitFullscreen(willCauseResize bool)
	// GetClient
	// Returns the client for this browser.
	GetClient() IEngClient
	// GetDefaultZoomLevel
	// Get the default zoom level. This value will be 0.0 by default but can be
	// configured with the Chrome runtime. This function can only be called on
	// the UI thread.
	GetDefaultZoomLevel() float64
	// GetExtension
	// Returns the extension hosted in this browser or NULL if no extension is
	// hosted. See ICefRequestContext.LoadExtension for details.
	// WARNING: This API is deprecated and will be removed in ~M127.
	GetExtension() ICefExtension_127
	// GetRuntimeStyle
	// Returns the runtime style for this browser (ALLOY or CHROME). See
	// TCefRuntimeStyle documentation for details.
	// This function can only be called on the CEF UI thread.
	GetRuntimeStyle() cefTypes.TCefRuntimeStyle
	// IsBackgroundHost
	// Returns true (1) if this browser is hosting an extension background
	// script. Background hosts do not have a window and are not displayable. See
	// ICefRequestContext.LoadExtension for details.
	// WARNING: This API is deprecated and will be removed in ~M127.
	IsBackgroundHost() bool
	// IsFullscreen
	// Returns true (1) if the renderer is currently in browser fullscreen. This
	// differs from window fullscreen in that browser fullscreen is entered using
	// the JavaScript Fullscreen API and modifies CSS attributes such as the
	// ::backdrop pseudo-element and :fullscreen pseudo-structure. This function
	// can only be called on the UI thread.
	IsFullscreen() bool
	// IsRenderProcessUnresponsive
	// Returns true (1) if the render process associated with this browser is
	// currently unresponsive as indicated by a lack of input event processing
	// for at least 15 seconds. To receive associated state change notifications
	// and optionally handle an unresponsive render process implement
	// ICefRequestHandler.OnRenderProcessUnresponsive.
	// This function can only be called on the CEF UI thread.
	IsRenderProcessUnresponsive() bool
	// Zoom
	// Execute a zoom command in this browser. If called on the UI thread the
	// change will be applied immediately. Otherwise, the change will be applied
	// asynchronously on the UI thread.
	Zoom(command cefTypes.TCefZoomCommand)
}

type ICefBrowserHostRef_127 interface {
	ICefBrowserHostRef
	ICefBrowserHost_127
}

type ICefBrowserRef_127 interface {
	ICefBrowserRef
	ICefBrowser_127
}

type ICefBrowserView_127 interface {
	ICefBrowserView
	ICefView_127
	// GetRuntimeStyle
	// Returns the runtime style for this BrowserView (ALLOY or CHROME). See
	// TCefRuntimeStyle documentation for details.
	GetRuntimeStyle() cefTypes.TCefRuntimeStyle
}

type ICefBrowserViewRef_127 interface {
	ICefBrowserViewRef
	ICefBrowserView_127
	ICefViewRef_127
}

type ICefButton_127 interface {
	ICefButton
	ICefView_127
}

type ICefButtonRef_127 interface {
	ICefButtonRef
	ICefButton_127
	ICefViewRef_127
}

type ICefChromiumTask_127 interface {
	ICefManagedTask_127
	AsIntfTask() uintptr
}

type ICefCustomStringList_127 interface {
	ICefCustomStringList
	ICefStringList_127
}

type ICefDomNode_127 interface {
	ICefDomNode
	// GetFormControlElementType
	// Returns the type of this form control element node.
	GetFormControlElementType() cefTypes.TCefDomFormControlType
}

type ICefDomNodeRef_127 interface {
	ICefDomNodeRef
	ICefDomNode_127
}

type ICefDownloadItem_127 interface {
	ICefDownloadItem
	// GetInterruptReason
	// Returns the most recent interrupt reason.
	GetInterruptReason() cefTypes.TCefDownloadInterruptReason
	// IsInterrupted
	// Returns true (1) if the download has been interrupted.
	IsInterrupted() bool
}

type ICefDownloadItemRef_127 interface {
	ICefBaseRefCountedRef
	ICefDownloadItem_127
	AsIntfDownloadItem() uintptr
}

type ICefDragData_127 interface {
	ICefDragData
	// GetFilePaths
	// Retrieve the list of file paths that are being dragged into the browser
	// window.
	GetFilePaths(paths *lcl.IStrings) int32
}

type ICefDragDataRef_127 interface {
	ICefDragDataRef
	ICefDragData_127
}

type ICefExtension_127 interface {
	ICefBaseRefCounted
	GetBackgroundPage() string
	GetBrowserActionIcon() string
	GetBrowserActionPopup() string
	// GetHandler
	// Returns the handler for this extension. Will return NULL for internal
	// extensions or if no handler was passed to
	// ICefRequestContext.LoadExtension.
	GetHandler() IEngExtensionHandler_127
	// GetIdentifier
	// Returns the unique extension identifier. This is calculated based on the
	// extension public key, if available, or on the extension path. See
	// https://developer.chrome.com/extensions/manifest/key for details.
	GetIdentifier() string
	// GetLoaderContext
	// Returns the request context that loaded this extension. Will return NULL
	// for internal extensions or if the extension has been unloaded. See the
	// ICefRequestContext.LoadExtension documentation for more information
	// about loader contexts. Must be called on the browser process UI thread.
	GetLoaderContext() ICefRequestContext
	// GetManifest
	// Returns the extension manifest contents as a ICefDictionaryValue
	// object. See https://developer.chrome.com/extensions/manifest for details.
	GetManifest() ICefDictionaryValue
	GetOptionsPage() string
	GetOptionsUIPage() string
	GetPageActionIcon() string
	GetPageActionPopup() string
	// GetPath
	// Returns the absolute path to the extension directory on disk. This value
	// will be prefixed with PK_DIR_RESOURCES if a relative path was passed to
	// ICefRequestContext.LoadExtension.
	GetPath() string
	GetURL() string
	// IsLoaded
	// Returns true (1) if this extension is currently loaded. Must be called on
	// the browser process UI thread.
	IsLoaded() bool
	// IsSame
	// Returns true (1) if this object is the same extension as |that| object.
	// Extensions are considered the same if identifier, path and loader context
	// match.
	IsSame(that ICefExtension_127) bool
	// Unload
	// Unload this extension if it is not an internal extension and is currently
	// loaded. Will result in a call to
	// ICefExtensionHandler.OnExtensionUnloaded on success.
	Unload()
}

type ICefExtensionHandler_127 interface {
	ICefBaseRefCounted
}

type ICefExtensionHandlerOwn_127 interface {
	ICefBaseRefCountedOwn
	ICefExtensionHandler_127
}

type ICefExtensionRef_127 interface {
	ICefBaseRefCountedRef
	ICefExtension_127
	AsIntfExtension() uintptr
}

type ICefGenericTask_127 interface {
	ICefGenericTask
	ICefChromiumTask_127
}

type ICefGetExtensionResourceCallback_127 interface {
	ICefBaseRefCounted
	// Cancel
	// Cancel the request.
	Cancel()
	// Cont
	// Continue the request. Read the resource contents from |stream|.
	Cont(stream ICefStreamReader)
}

type ICefGetExtensionResourceCallbackRef_127 interface {
	ICefBaseRefCountedRef
	ICefGetExtensionResourceCallback_127
	AsIntfGetExtensionResourceCallback() uintptr
}

type ICefLabelButton_127 interface {
	ICefLabelButton
	ICefButton_127
}

type ICefLabelButtonRef_127 interface {
	ICefLabelButtonRef
	ICefButtonRef_127
	ICefLabelButton_127
}

type ICefManagedTask_127 interface {
	ICefTaskOwn
	AsIntfTask() uintptr
}

type ICefMediaAccessHandler_127 interface {
	ICefBaseRefCounted
}

type ICefMediaAccessHandlerOwn_127 interface {
	ICefBaseRefCountedOwn
	ICefMediaAccessHandler_127
}

type ICefMenuButton_127 interface {
	ICefMenuButton
	ICefLabelButton_127
}

type ICefMenuButtonRef_127 interface {
	ICefMenuButtonRef
	ICefLabelButtonRef_127
	ICefMenuButton_127
}

type ICefPanel_127 interface {
	ICefPanel
	ICefView_127
}

type ICefPanelRef_127 interface {
	ICefPanelRef
	ICefPanel_127
	ICefViewRef_127
}

type ICefRequestContext_127 interface {
	ICefRequestContext
	// DidLoadExtension
	// Returns true (1) if this context was used to load the extension identified
	// by |extension_id|. Other contexts sharing the same storage will also have
	// access to the extension (see HasExtension). This function must be called
	// on the browser process UI thread.
	// WARNING: This function is deprecated and will be removed in ~M127.
	DidLoadExtension(extensionId string) bool
	// GetChromeColorSchemeColor
	// Returns the current Chrome color scheme color, or transparent (0) for the
	// default color. Must be called on the browser process UI thread.
	GetChromeColorSchemeColor() cefTypes.TCefColor
	// GetChromeColorSchemeMode
	// Returns the current Chrome color scheme mode (SYSTEM, LIGHT or DARK). Must
	// be called on the browser process UI thread.
	GetChromeColorSchemeMode() cefTypes.TCefColorVariant
	// GetChromeColorSchemeVariant
	// Returns the current Chrome color scheme variant. Must be called on the
	// browser process UI thread.
	GetChromeColorSchemeVariant() cefTypes.TCefColorVariant
	// GetContentSetting
	// Returns the current value for |content_type| that applies for the
	// specified URLs. If both URLs are NULL the default value will be returned.
	// Returns CEF_CONTENT_SETTING_VALUE_DEFAULT if no value is configured. Must
	// be called on the browser process UI thread.
	GetContentSetting(requestingUrl string, topLevelUrl string, contentType cefTypes.TCefContentSettingTypes) cefTypes.TCefContentSettingValues
	// GetExtensions
	// Retrieve the list of all extensions that this context has access to (see
	// HasExtension). |extension_ids| will be populated with the list of
	// extension ID values. Returns true (1) on success. This function must be
	// called on the browser process UI thread.
	// WARNING: This function is deprecated and will be removed in ~M127.
	GetExtensions(extensionIds lcl.IStringList) bool
	// GetExtension
	// Returns the extension matching |extension_id| or NULL if no matching
	// extension is accessible in this context (see HasExtension). This function
	// must be called on the browser process UI thread.
	// WARNING: This function is deprecated and will be removed in ~M127.
	GetExtension(extensionId string) ICefExtension_127
	// GetWebsiteSetting
	// Returns the current value for |content_type| that applies for the
	// specified URLs. If both URLs are NULL the default value will be returned.
	// Returns nullptr if no value is configured. Must be called on the browser
	// process UI thread.
	GetWebsiteSetting(requestingUrl string, topLevelUrl string, contentType cefTypes.TCefContentSettingTypes) ICefValue
	// HasExtension
	// Returns true (1) if this context has access to the extension identified by
	// |extension_id|. This may not be the context that was used to load the
	// extension (see DidLoadExtension). This function must be called on the
	// browser process UI thread.
	// WARNING: This function is deprecated and will be removed in ~M127.
	HasExtension(extensionId string) bool
	// LoadExtension
	// Load an extension.
	// If extension resources will be read from disk using the default load
	// implementation then |root_directory| should be the absolute path to the
	// extension resources directory and |manifest| should be NULL. If extension
	// resources will be provided by the client (e.g. via ICefRequestHandler
	// and/or ICefExtensionHandler) then |root_directory| should be a path
	// component unique to the extension (if not absolute this will be internally
	// prefixed with the PK_DIR_RESOURCES path) and |manifest| should contain the
	// contents that would otherwise be read from the "manifest.json" file on
	// disk.
	// The loaded extension will be accessible in all contexts sharing the same
	// storage (HasExtension returns true (1)). However, only the context on
	// which this function was called is considered the loader (DidLoadExtension
	// returns true (1)) and only the loader will receive
	// ICefRequestContextHandler callbacks for the extension.
	// ICefExtensionHandler.OnExtensionLoaded will be called on load success
	// or ICefExtensionHandler.OnExtensionLoadFailed will be called on load
	// failure.
	// If the extension specifies a background script via the "background"
	// manifest key then ICefExtensionHandler.OnBeforeBackgroundBrowser will
	// be called to create the background browser. See that function for
	// additional information about background scripts.
	// For visible extension views the client application should evaluate the
	// manifest to determine the correct extension URL to load and then pass that
	// URL to the ICefBrowserHost.CreateBrowser* function after the extension
	// has loaded. For example, the client can look for the "browser_action"
	// manifest key as documented at
	// https://developer.chrome.com/extensions/browserAction. Extension URLs take
	// the form "chrome-extension://<extension_id>/<path>".
	// Browsers that host extensions differ from normal browsers as follows:
	// - Can access chrome.* JavaScript APIs if allowed by the manifest. Visit
	// chrome://extensions-support for the list of extension APIs currently
	// supported by CEF.
	// - Main frame navigation to non-extension content is blocked.
	// - Pinch-zooming is disabled.
	// - CefBrowserHost::GetExtension returns the hosted extension.
	// - CefBrowserHost::IsBackgroundHost returns true for background hosts.
	// See https://developer.chrome.com/extensions for extension implementation
	// and usage documentation.
	// WARNING: This function is deprecated and will be removed in ~M127.
	LoadExtension(rootDirectory string, manifest ICefDictionaryValue, handler IEngExtensionHandler_127)
	// SetChromeColorScheme
	// Sets the Chrome color scheme for all browsers that share this request
	// context. |variant| values of SYSTEM, LIGHT and DARK change the underlying
	// color mode (e.g. light vs dark). Other |variant| values determine how
	// |user_color| will be applied in the current color mode. If |user_color| is
	// transparent (0) the default color will be used.
	SetChromeColorScheme(variant cefTypes.TCefColorVariant, userColor cefTypes.TCefColor)
	// SetContentSetting
	// Sets the current value for |content_type| for the specified URLs in the
	// default scope. If both URLs are NULL, and the context is not incognito,
	// the default value will be set. Pass CEF_CONTENT_SETTING_VALUE_DEFAULT for
	// |value| to use the default value for this content type.
	// WARNING: Incorrect usage of this function may cause instability or
	// security issues in Chromium. Make sure that you first understand the
	// potential impact of any changes to |content_type| by reviewing the related
	// source code in Chromium. For example, if you plan to modify
	// CEF_CONTENT_SETTING_TYPE_POPUPS, first review and understand the usage of
	// ContentSettingsType::POPUPS in Chromium:
	// https://source.chromium.org/search?q=ContentSettingsType::POPUPS
	SetContentSetting(requestingUrl string, topLevelUrl string, contentType cefTypes.TCefContentSettingTypes, value cefTypes.TCefContentSettingValues)
	// SetWebsiteSetting
	// Sets the current value for |content_type| for the specified URLs in the
	// default scope. If both URLs are NULL, and the context is not incognito,
	// the default value will be set. Pass nullptr for |value| to remove the
	// default value for this content type.
	// WARNING: Incorrect usage of this function may cause instability or
	// security issues in Chromium. Make sure that you first understand the
	// potential impact of any changes to |content_type| by reviewing the related
	// source code in Chromium. For example, if you plan to modify
	// CEF_CONTENT_SETTING_TYPE_POPUPS, first review and understand the usage of
	// ContentSettingsType::POPUPS in Chromium:
	// https://source.chromium.org/search?q=ContentSettingsType::POPUPS
	SetWebsiteSetting(requestingUrl string, topLevelUrl string, contentType cefTypes.TCefContentSettingTypes, value ICefValue)
}

type ICefRequestContextRef_127 interface {
	ICefRequestContextRef
	ICefRequestContext_127
}

type ICefScrollView_127 interface {
	ICefScrollView
	ICefView_127
}

type ICefScrollViewRef_127 interface {
	ICefScrollViewRef
	ICefScrollView_127
	ICefViewRef_127
}

type ICefStringList_127 interface {
	ICefStringList
	GetHandle() cefTypes.TCefStringList
}

type ICefStringListOwn_127 interface {
	ICefStringListOwn
	ICefCustomStringList_127
}

type ICefStringListRef_127 interface {
	ICefStringListRef
	ICefCustomStringList_127
}

type ICefTextfield_127 interface {
	ICefTextfield
	ICefView_127
}

type ICefTextfieldRef_127 interface {
	ICefTextfieldRef
	ICefTextfield_127
	ICefViewRef_127
}

type ICefURLRequestClientTask_127 interface {
	ICefManagedTask_127
	AsIntfTask() uintptr
}

type ICefUnresponsiveProcessCallback_127 interface {
	ICefBaseRefCounted
	// Terminate
	// Terminate the unresponsive process.
	Terminate()
	// Wait
	// Reset the timeout for the unresponsive process.
	Wait()
}

type ICefUnresponsiveProcessCallbackRef_127 interface {
	ICefBaseRefCountedRef
	ICefUnresponsiveProcessCallback_127
	AsIntfUnresponsiveProcessCallback() uintptr
}

type ICefUrlRequest_127 interface {
	ICefUrlRequest
	// GetClient
	// Returns the client.
	GetClient() IEngUrlrequestClient
}

type ICefUrlRequestRef_127 interface {
	ICefUrlRequestRef
	ICefUrlRequest_127
}

type ICefUrlrequestClientRef_127 interface {
	ICefBaseRefCountedRef
	ICefUrlrequestClient
	AsIntfUrlrequestClient() uintptr
}

type ICefView_127 interface {
	ICefView
	// GetThemeColor
	// Returns the current theme color associated with |color_id|, or the
	// placeholder color (red) if unset. See cef_color_ids.h for standard ID
	// values. Standard colors can be overridden and custom colors can be added
	// using ICefWindow.SetThemeColor.
	GetThemeColor(colorId int32) cefTypes.TCefColor
}

type ICefViewDelegateTask_127 interface {
	ICefManagedTask_127
	AsIntfTask() uintptr
}

type ICefViewRef_127 interface {
	ICefViewRef
	ICefView_127
}

type ICefWindow_127 interface {
	ICefWindow
	ICefPanel_127
	// AddOverlayView
	// Add a View that will be overlayed on the Window contents with absolute
	// positioning and high z-order. Positioning is controlled by |docking_mode|
	// as described below. Setting |can_activate| to true (1) will allow the
	// overlay view to receive input focus. The returned cef_overlay_controller_t
	// object is used to control the overlay. Overlays are hidden by default.
	// With CEF_DOCKING_MODE_CUSTOM:
	// 1. The overlay is initially hidden, sized to |view|'s preferred size,
	// and positioned in the top-left corner.
	// 2. Optionally change the overlay position and/or size by calling
	// CefOverlayController methods.
	// 3. Call ICefOverlayController.SetVisible(true) to show the overlay.
	// 4. The overlay will be automatically re-sized if |view|'s layout
	// changes. Optionally change the overlay position and/or size when
	// OnLayoutChanged is called on the Window's delegate to indicate a
	// change in Window bounds.
	// With other docking modes:
	// 1. The overlay is initially hidden, sized to |view|'s preferred size,
	// and positioned based on |docking_mode|.
	// 2. Call ICefOverlayController.SetVisible(true) to show the overlay.
	// 3. The overlay will be automatically re-sized if |view|'s layout changes
	// and re-positioned as appropriate when the Window resizes.
	// Overlays created by this function will receive a higher z-order then any
	// child Views added previously. It is therefore recommended to call this
	// function last after all other child Views have been added so that the
	// overlay displays as the top-most child of the Window.
	AddOverlayView(view ICefView, dockingMode cefTypes.TCefDockingMode, canActivate bool) ICefOverlayController
	// GetRuntimeStyle
	// Returns the runtime style for this Window (ALLOY or CHROME). See
	// TCefRuntimeStyle documentation for details.
	GetRuntimeStyle() cefTypes.TCefRuntimeStyle
	// SetAccelerator
	// Set the keyboard accelerator for the specified |command_id|. |key_code|
	// can be any virtual key or character value. Required modifier keys are
	// specified by |shift_pressed|, |ctrl_pressed| and/or |alt_pressed|.
	// ICefWindowDelegate.OnAccelerator will be called if the keyboard
	// combination is triggered while this window has focus.
	// The |high_priority| value will be considered if a child ICefBrowserView
	// has focus when the keyboard combination is triggered. If |high_priority|
	// is true (1) then the key event will not be forwarded to the web content
	// (`keydown` event handler) or ICefKeyboardHandler first. If
	// |high_priority| is false (0) then the behavior will depend on the
	// ICefBrowserView.SetPreferAccelerators configuration.
	SetAccelerator(commandId int32, keyCode int32, shiftPressed bool, ctrlPressed bool, altPressed bool, highPriority bool)
	// SetThemeColor
	// Override a standard theme color or add a custom color associated with
	// |color_id|. See cef_color_ids.h for standard ID values. Recommended usage
	// is as follows:
	// <code>
	// 1. Customize the default native/OS theme by calling SetThemeColor before
	// showing the first Window. When done setting colors call
	// ICefWindow.ThemeChanged to trigger ICefViewDelegate.OnThemeChanged
	// notifications.
	// 2. Customize the current native/OS or Chrome theme after it changes by
	// calling SetThemeColor from the ICefWindowDelegate.OnThemeColorsChanged
	// callback. ICefViewDelegate.OnThemeChanged notifications will then be
	// triggered automatically.
	// </code>
	// The configured color will be available immediately via
	// ICefView.GetThemeColor and will be applied to each View in this
	// Window's component hierarchy when ICefViewDelegate.OnThemeChanged is
	// called. See OnThemeColorsChanged documentation for additional details.
	// Clients wishing to add custom colors should use |color_id| values >=
	// CEF_ChromeColorsEnd.
	SetThemeColor(colorId int32, color cefTypes.TCefColor)
	// ShowAsBrowserModalDialog
	// Show the Window as a browser modal dialog relative to |browser_view|. A
	// parent Window must be returned via
	// ICefWindowDelegate.GetParentWindow() and |browser_view| must belong
	// to that parent Window. While this Window is visible, |browser_view| will
	// be disabled while other controls in the parent Window remain enabled.
	// Navigating or destroying the |browser_view| will close this Window
	// automatically. Alternately, use show() and return true (1) from
	// ICefWindowDelegate.IsWindowModalDialog() for a window modal dialog
	// where all controls in the parent Window are disabled.
	ShowAsBrowserModalDialog(browserView ICefBrowserView)
	// ThemeChanged
	// Trigger ICefViewDelegate.OnThemeChanged callbacks for each View in
	// this Window's component hierarchy. Unlike a native/OS or Chrome theme
	// change this function does not reset theme colors to standard values and
	// does not result in a call to ICefWindowDelegate.OnThemeColorsChanged.
	// Do not call this function from ICefWindowDelegate.OnThemeColorsChanged
	// or ICefViewDelegate.OnThemeChanged.
	ThemeChanged()
}

type ICefWindowRef_127 interface {
	ICefWindowRef
	ICefPanelRef_127
	ICefWindow_127
}

type ICefv8Value_127 interface {
	ICefv8Value
	// GetArrayBufferByteLength
	// Returns the length (in bytes) of the ArrayBuffer.
	GetArrayBufferByteLength() cefTypes.NativeUInt
	// GetArrayBufferData
	// Returns a pointer to the beginning of the memory block for this
	// ArrayBuffer backing store. The returned pointer is valid as long as the
	// ICefv8value is alive.
	GetArrayBufferData() uintptr
	// GetUserData
	// Returns the user data, if any, assigned to this object.
	GetUserData() ICefv8Value
	// SetUserData
	// Sets the user data for this object and returns true (1) on success.
	// Returns false (0) if this function is called incorrectly. This function
	// can only be called on user created objects.
	SetUserData(data ICefv8Value) bool
	// SetValueByAccessor
	// Registers an identifier and returns true (1) on success. Access to the
	// identifier will be forwarded to the ICefV8Accessor instance passed to
	// cef_v8value_create_object(). Returns false (0) if this
	// function is called incorrectly or an exception is thrown. For read-only
	// values this function will return true (1) even though assignment failed.
	SetValueByAccessor(key string, attribute cefTypes.TCefV8PropertyAttributes) bool
}

type ICefv8ValueRef_127 interface {
	ICefv8ValueRef
	ICefv8Value_127
}

type IChromium_127 interface {
	IChromium
	IChromiumCore_127
}

type IChromiumCore_127 interface {
	IChromiumCore
	// AcceptLanguageList
	// Set the accept language list in the browser preferences.
	AcceptLanguageList() string
	// BatterySaverModeState
	// Battery saver mode state.
	BatterySaverModeState() cefTypes.TCefBatterySaverModeState
	// CanDecZoom
	// Returns true (1) if this browser can execute the zoom OUT command.
	// This function can only be called on the CEF UI thread.
	CanDecZoom() bool
	// CanExecuteChromeCommand
	// Returns true (1) if a Chrome command is supported and enabled. Values for
	// |command_id| can be found in the cef_command_ids.h file. This function can
	// only be called on the UI thread. Only used with the Chrome runtime.
	// <see cref="uCEFConstants">See the IDC_* constants in uCEFConstants.pas for all the |command_id| values.</see>
	// <see href="https://source.chromium.org/chromium/chromium/src/+/main:chrome/app/chrome_command_ids.h">The command_id values are also available in chrome/app/chrome_command_ids.h</see>
	CanExecuteChromeCommand(commandId int32) bool
	// CanFocus
	// Indicates whether the browser can receive focus.
	CanFocus() bool
	// CanIncZoom
	// Returns true (1) if this browser can execute the zoom IN command.
	// This function can only be called on the CEF UI thread.
	CanIncZoom() bool
	// CanResetZoom
	// Returns true (1) if this browser can execute the zoom RESET command.
	// This function can only be called on the CEF UI thread.
	CanResetZoom() bool
	// ChromeColorSchemeColor
	// Returns the current Chrome color scheme color, or transparent (0) for the
	// default color. Must be called on the browser process UI thread.
	ChromeColorSchemeColor() cefTypes.TCefColor
	// ChromeColorSchemeMode
	// Returns the current Chrome color scheme mode (SYSTEM, LIGHT or DARK). Must
	// be called on the browser process UI thread.
	ChromeColorSchemeMode() cefTypes.TCefColorVariant
	// ChromeColorSchemeVariant
	// Returns the current Chrome color scheme variant. Must be called on the
	// browser process UI thread.
	ChromeColorSchemeVariant() cefTypes.TCefColorVariant
	// CreateUrlRequestWithRequestUClientStrX2
	// Create a new URL request that will be treated as originating from this
	// frame and the associated browser. Use TCustomCefUrlrequestClient.Create instead if
	// you do not want the request to have this association, in which case it may
	// be handled differently (see documentation on that function). A request
	// created with this function may only originate from the browser process,
	// and will behave as follows:
	// <code>
	// - It may be intercepted by the client via CefResourceRequestHandler or
	// CefSchemeHandlerFactory.
	// - POST data may only contain a single element of type PDE_TYPE_FILE or
	// PDE_TYPE_BYTES.
	// </code>
	// The |request| object will be marked as read-only after calling this
	// function.
	CreateUrlRequestWithRequestUClientStrX2(request ICefRequest, client IEngUrlrequestClient, frameName string, frameIdentifier string) ICefUrlRequest
	// DecZoomCommand
	// Execute a zoom OUT command in this browser. If called on the CEF UI thread the
	// change will be applied immediately. Otherwise, the change will be applied
	// asynchronously on the CEF UI thread.
	DecZoomCommand()
	// DefaultZoomLevel
	// Get the default zoom level. This value will be 0.0 by default but can be
	// configured with the Chrome runtime. This function can only be called on
	// the CEF UI thread.
	DefaultZoomLevel() float64
	// DownloadBubble
	// Enable the file download bubble when using the Chrome runtime.
	DownloadBubble() cefTypes.TCefState
	// EnableFocusDelayMs
	// Delay in milliseconds to enable browser focus.
	EnableFocusDelayMs() uint32
	// ExecuteChromeCommand
	// Execute a Chrome command. Values for |command_id| can be found in the
	// cef_command_ids.h file. |disposition| provides information about the
	// intended command target. Only used with the Chrome runtime.
	// <see cref="uCEFConstants">See the IDC_* constants in uCEFConstants.pas for all the |command_id| values.</see>
	// <see href="https://source.chromium.org/chromium/chromium/src/+/main:chrome/app/chrome_command_ids.h">The command_id values are also available in chrome/app/chrome_command_ids.h</see>
	ExecuteChromeCommand(commandId int32, disposition cefTypes.TCefWindowOpenDisposition)
	// ExecuteJavaScriptWithStrX4Int
	// Execute a string of JavaScript code in the specified frame or the main frame.
	// <param name="aCode">JavaScript code.</param>
	// <param name="aScriptURL">The URL where the script in question can be found, if any. The renderer may request this URL to show the developer the source of the error.</param>
	// <param name="aFrameName">Name of the frame where the JavaScript code will be executed. This name is generated automatically by Chromium. See ICefBrowser.GetFrameNames.</param>
	// <param name="aFrameIdentifier">Identifier of the frame where the JavaScript code will be executed.</param>
	// <param name="aStartLine">The base line number to use for error reporting.</param>
	ExecuteJavaScriptWithStrX4Int(code string, scriptURL string, frameName string, frameIdentifier string, startLine int32)
	// ExitFullscreen
	// Requests the renderer to exit browser fullscreen. In most cases exiting
	// window fullscreen should also exit browser fullscreen. With the Alloy
	// runtime this function should be called in response to a user action such
	// as clicking the green traffic light button on MacOS
	// (ICefWindowDelegate.OnWindowFullscreenTransition callback) or pressing
	// the "ESC" key (ICefKeyboardHandler.OnPreKeyEvent callback). With the
	// Chrome runtime these standard exit actions are handled internally but
	// new/additional user actions can use this function. Set |will_cause_resize|
	// to true (1) if exiting browser fullscreen will cause a view resize.
	ExitFullscreen(willCauseResize bool)
	// ExtensionHandler
	// Returns a ICefExtensionHandler instance used by the selected browser.
	ExtensionHandler() IEngExtensionHandler_127
	// Fullscreen
	// Returns true (1) if the renderer is currently in browser fullscreen. This
	// differs from window fullscreen in that browser fullscreen is entered using
	// the JavaScript Fullscreen API and modifies CSS attributes such as the
	// ::backdrop pseudo-element and :fullscreen pseudo-structure. This property
	// can only be called on the UI thread.
	Fullscreen() bool
	// GetContentSetting
	// Returns the current value for |content_type| that applies for the
	// specified URLs. If both URLs are NULL the default value will be returned.
	// Returns CEF_CONTENT_SETTING_VALUE_DEFAULT if no value is configured. Must
	// be called on the browser process UI thread.
	GetContentSetting(requestingUrl string, topLevelUrl string, contentType cefTypes.TCefContentSettingTypes) cefTypes.TCefContentSettingValues
	// GetFrameIdentifiers
	// Returns the identifiers of all existing frames.
	GetFrameIdentifiers(frameIdentifiers *lcl.IStrings) bool
	// GetWebsiteSetting
	// Returns the current value for |content_type| that applies for the
	// specified URLs. If both URLs are NULL the default value will be returned.
	// Returns nullptr if no value is configured. Must be called on the browser
	// process UI thread.
	GetWebsiteSetting(requestingUrl string, topLevelUrl string, contentType cefTypes.TCefContentSettingTypes) ICefValue
	// HSTSPolicyBypassList
	// List of comma-delimited single-label hostnames that will skip the check to possibly upgrade from http to https.
	HSTSPolicyBypassList() string
	// HTTPSUpgrade
	// Automatically upgrade to HTTPS connections.
	HTTPSUpgrade() cefTypes.TCefState
	// HighEfficiencyModeState
	// High efficiency mode state.
	HighEfficiencyModeState() cefTypes.TCefHighEfficiencyModeState
	// IncZoomCommand
	// Execute a zoom IN command in this browser. If called on the CEF UI thread the
	// change will be applied immediately. Otherwise, the change will be applied
	// asynchronously on the CEF UI thread.
	IncZoomCommand()
	// IsRenderProcessUnresponsive
	// Returns true (1) if the render process associated with this browser is
	// currently unresponsive as indicated by a lack of input event processing
	// for at least 15 seconds. To receive associated state change notifications
	// and optionally handle an unresponsive render process implement
	// ICefRequestHandler.OnRenderProcessUnresponsive.
	// This property can only be read on the CEF UI thread.
	IsRenderProcessUnresponsive() bool
	// LoadResourceWithCMStreamStrX4
	// Used to load a DATA URI with the stream contents in the specified frame or the main frame.
	// The DATA URI will be configured with the mime type and charset specified in the parameters.
	LoadResourceWithCMStreamStrX4(stream lcl.ICustomMemoryStream, mimeType string, charset string, frameName string, frameIdentifier string)
	// LoadStringWithStrX3
	// Used to load a DATA URI with the HTML string contents in the specified frame or the main frame.
	LoadStringWithStrX3(hTML string, frameName string, frameIdentifier string)
	// LoadURLWithStrX3
	// Used to navigate to a URL in the specified frame or the main frame.
	LoadURLWithStrX3(uRL string, frameName string, frameIdentifier string)
	// ResetZoomCommand
	// Execute a zoom RESET command in this browser. If called on the CEF UI thread the
	// change will be applied immediately. Otherwise, the change will be applied
	// asynchronously on the CEF UI thread.
	ResetZoomCommand()
	// RetrieveHTMLWithStrX2
	// Retrieve all the HTML content from the specified frame or the main frame.
	// Leave aFrameName empty to get the HTML source from the main frame.
	// It uses a CefStringVisitor to get the HTML content asynchronously and the
	// result will be received in the TChromiumCore.OnTextResultAvailable event.
	RetrieveHTMLWithStrX2(frameName string, frameIdentifier string)
	// RetrieveTextWithStrX2
	// Retrieve all the text content from the specified frame or the main frame.
	// Leave aFrameName empty to get the text from the main frame.
	// It uses a CefStringVisitor to get the text asynchronously and the
	// result will be received in the TChromiumCore.OnTextResultAvailable event.
	RetrieveTextWithStrX2(frameName string, frameIdentifier string)
	// RuntimeStyle
	// Returns the runtime style for this browser (ALLOY or CHROME). See
	// TCefRuntimeStyle documentation for details.
	// This property can only be read on the CEF UI thread.
	RuntimeStyle() cefTypes.TCefRuntimeStyle
	// SendProcessMessageWithPIdPMessageStrX2
	// Send a message to the specified |targetProcess|. Ownership of the message
	// contents will be transferred and the |ProcMessage| reference will be
	// invalidated. Message delivery is not guaranteed in all cases (for example,
	// if the browser is closing, navigating, or if the target process crashes).
	// Send an ACK message back from the target process if confirmation is
	// required.
	SendProcessMessageWithPIdPMessageStrX2(targetProcess cefTypes.TCefProcessId, procMessage ICefProcessMessage, frameName string, frameIdentifier string)
	SetAcceptLanguageList(value string)
	SetBatterySaverModeState(value cefTypes.TCefBatterySaverModeState)
	// SetChromeColorScheme
	// Sets the Chrome color scheme for all browsers that share this request
	// context. |variant| values of SYSTEM, LIGHT and DARK change the underlying
	// color mode (e.g. light vs dark). Other |variant| values determine how
	// |user_color| will be applied in the current color mode. If |user_color| is
	// transparent (0) the default color will be used.
	SetChromeColorScheme(variant cefTypes.TCefColorVariant, userColor cefTypes.TCefColor)
	// SetContentSetting
	// Sets the current value for |content_type| for the specified URLs in the
	// default scope. If both URLs are NULL, and the context is not incognito,
	// the default value will be set. Pass CEF_CONTENT_SETTING_VALUE_DEFAULT for
	// |value| to use the default value for this content type.
	// WARNING: Incorrect usage of this function may cause instability or
	// security issues in Chromium. Make sure that you first understand the
	// potential impact of any changes to |content_type| by reviewing the related
	// source code in Chromium. For example, if you plan to modify
	// CEF_CONTENT_SETTING_TYPE_POPUPS, first review and understand the usage of
	// ContentSettingsType::POPUPS in Chromium:
	// https://source.chromium.org/search?q=ContentSettingsType::POPUPS
	SetContentSetting(requestingUrl string, topLevelUrl string, contentType cefTypes.TCefContentSettingTypes, value cefTypes.TCefContentSettingValues)
	SetDownloadBubble(value cefTypes.TCefState)
	SetEnableFocusDelayMs(value uint32)
	SetHSTSPolicyBypassList(value string)
	SetHTTPSUpgrade(value cefTypes.TCefState)
	SetHighEfficiencyModeState(value cefTypes.TCefHighEfficiencyModeState)
	SetOnBeforeDevToolsPopup(fn TOnBeforeDevToolsPopup)
	SetOnCanFocus(fn TNotifyEvent)
	SetOnExtensionBeforeBackgroundBrowser(fn TOnBeforeBackgroundBrowserEvent)
	SetOnExtensionBeforeBrowser(fn TOnBeforeBrowserEvent)
	SetOnExtensionCanAccessBrowser(fn TOnCanAccessBrowserEvent)
	SetOnExtensionGetActiveBrowser(fn TOnGetActiveBrowserEvent)
	SetOnExtensionGetExtensionResource(fn TOnGetExtensionResourceEvent)
	SetOnExtensionLoadFailed(fn TOnExtensionLoadFailedEvent)
	SetOnExtensionLoaded(fn TOnExtensionLoadedEvent)
	SetOnExtensionUnloaded(fn TOnExtensionUnloadedEvent)
	SetOnIsChromeAppMenuItemEnabled(fn TOnIsChromeAppMenuItemEnabledEvent)
	SetOnIsChromeAppMenuItemVisible(fn TOnIsChromeAppMenuItemVisibleEvent)
	SetOnIsChromePageActionIconVisible(fn TOnIsChromePageActionIconVisibleEvent)
	SetOnIsChromeToolbarButtonVisible(fn TOnIsChromeToolbarButtonVisibleEvent)
	SetOnRenderProcessResponsive(fn TOnRenderProcessResponsive)
	SetOnRenderProcessUnresponsive(fn TOnRenderProcessUnresponsive)
	SetOnWidgetCompMsg(fn TOnCompMsgEvent)
	SetRuntimeStyle(value cefTypes.TCefRuntimeStyle)
	// SetWebsiteSetting
	// Sets the current value for |content_type| for the specified URLs in the
	// default scope. If both URLs are NULL, and the context is not incognito,
	// the default value will be set. Pass nullptr for |value| to remove the
	// default value for this content type.
	// WARNING: Incorrect usage of this function may cause instability or
	// security issues in Chromium. Make sure that you first understand the
	// potential impact of any changes to |content_type| by reviewing the related
	// source code in Chromium. For example, if you plan to modify
	// CEF_CONTENT_SETTING_TYPE_POPUPS, first review and understand the usage of
	// ContentSettingsType::POPUPS in Chromium:
	// https://source.chromium.org/search?q=ContentSettingsType::POPUPS
	SetWebsiteSetting(requestingUrl string, topLevelUrl string, contentType cefTypes.TCefContentSettingTypes, value ICefValue)
	// SimulateEditingCommand
	// Simulate editing commands using the "Input.dispatchKeyEvent" DevTools method.
	// <see href="https://chromedevtools.github.io/devtools-protocol/1-3/Input/#method-dispatchKeyEvent">See the "Input.dispatchKeyEvent" DevTools method.</see>
	// <see href="https://source.chromium.org/chromium/chromium/src/+/master:third_party/blink/renderer/core/editing/commands/editor_command_names.h">See the Chromium sources.</see>
	SimulateEditingCommand(command cefTypes.TCefEditingCommand)
	// SimulateKeyEvent
	// Dispatches a key event to the page using the "Input.dispatchKeyEvent"
	// DevTools method. The browser has to be focused before simulating any
	// key event.
	// <param name="type_">Type of the key event.</param>
	// <param name="modifiers">Bit field representing pressed modifier keys. Alt=1, Ctrl=2, Meta/Command=4, Shift=8.(default: 0).</param>
	// <param name="timestamp">Time at which the event occurred.</param>
	// <param name="text">Text as generated by processing a virtual key code with a keyboard layout. Not needed for for keyUp and rawKeyDown events.(default: "")</param>
	// <param name="unmodifiedtext">Text that would have been generated by the keyboard if no modifiers were pressed (except for shift). Useful for shortcut (accelerator) key handling.(default: "").</param>
	// <param name="keyIdentifier">Unique key identifier (e.g., 'U+0041').(default: "").</param>
	// <param name="code">Unique DOM defined string value for each physical key (e.g., 'KeyA').(default: "").</param>
	// <param name="key">Unique DOM defined string value describing the meaning of the key in the context of active modifiers, keyboard layout, etc (e.g., 'AltGr').(default: "").</param>
	// <param name="windowsVirtualKeyCode">Windows virtual key code.(default: 0).</param>
	// <param name="nativeVirtualKeyCode">Native virtual key code.(default: 0).</param>
	// <param name="autoRepeat">Whether the event was generated from auto repeat.(default: false).</param>
	// <param name="isKeypad">Whether the event was generated from the keypad.(default: false).</param>
	// <param name="isSystemKey">Whether the event was a system key event.(default: false).</param>
	// <param name="location">Whether the event was from the left or right side of the keyboard. 1=Left, 2=Right.(default: 0).</param>
	// <param name="commands">Editing commands to send with the key event (e.g., 'selectAll') (default: []). These are related to but not equal the command names used in document.execCommand and NSStandardKeyBindingResponding. See https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/editing/commands/editor_command_names.h for valid command names.</param>
	// <see href="https://chromedevtools.github.io/devtools-protocol/1-3/Input/#method-dispatchKeyEvent">See the "Input.dispatchKeyEvent" DevTools method.</see>
	SimulateKeyEvent(args TChromiumCoreSimulateKeyEventArgs)
	// SimulateMouseEvent
	// Dispatches a key event to the page using the "Input.dispatchKeyEvent"
	// DevTools method. The browser has to be focused before simulating any
	// key event.
	// <param name="type_">Type of the mouse event.</param>
	// <param name="x">X coordinate of the event relative to the main frame's viewport in CSS pixels.</param>
	// <param name="y">Y coordinate of the event relative to the main frame's viewport in CSS pixels. 0 refers to the top of the viewport and Y increases as it proceeds towards the bottom of the viewport.</param>
	// <param name="modifiers">Bit field representing pressed modifier keys. Alt=1, Ctrl=2, Meta/Command=4, Shift=8 (default: 0). See the CEF_MOUSETOUCH_EVENT_MODIFIERS_* constants.</param>
	// <param name="timestamp">Time at which the event occurred.</param>
	// <param name="button">Mouse button (default: "none").</param>
	// <param name="buttons">A number indicating which buttons are pressed on the mouse when a mouse event is triggered. Left=1, Right=2, Middle=4, Back=8, Forward=16, None=0.</param>
	// <param name="clickCount">Number of times the mouse button was clicked (default: 0).</param>
	// <param name="force">The normalized pressure, which has a range of [0,1] (default: 0). </param>
	// <param name="tangentialPressure">The normalized tangential pressure, which has a range of [-1,1] (default: 0).</param>
	// <param name="tiltX">The plane angle between the Y-Z plane and the plane containing both the stylus axis and the Y axis, in degrees of the range [-90,90], a positive tiltX is to the right (default: 0).</param>
	// <param name="tiltY">The plane angle between the X-Z plane and the plane containing both the stylus axis and the X axis, in degrees of the range [-90,90], a positive tiltY is towards the user (default: 0).</param>
	// <param name="twist">The clockwise rotation of a pen stylus around its own major axis, in degrees in the range [0,359] (default: 0).</param>
	// <param name="deltaX">X delta in CSS pixels for mouse wheel event (default: 0).</param>
	// <param name="deltaY">Y delta in CSS pixels for mouse wheel event (default: 0).</param>
	// <param name="pointerType">Pointer type (default: "mouse").</param>
	// <see href="https://chromedevtools.github.io/devtools-protocol/1-3/Input/#method-dispatchKeyEvent">See the "Input.dispatchKeyEvent" DevTools method.</see>
	SimulateMouseEvent(args TChromiumCoreSimulateMouseEventArgs)
	// WidgetHandle
	// Handle of one to the child controls created automatically by CEF to show the web contents.
	WidgetHandle() types.THandle
}

type IChromiumOptions_127 interface {
	IChromiumOptions
	// ChromeZoomBubble
	// Controls whether the Chrome zoom bubble will be shown when zooming. Only
	// supported with the Chrome runtime.
	ChromeZoomBubble() cefTypes.TCefState
	SetChromeZoomBubble(value cefTypes.TCefState)
}

type IChromiumWindow_127 interface {
	IChromiumWindow
	ICEFLinkedWinControlBase_127
}

type IEngBrowserProcessHandler_127 interface {
	IEngBrowserProcessHandler
	SetOnBrowserProcessAlreadyRunningAppRelaunch(fn TOnBrowserProcessAlreadyRunningAppRelaunchEvent)
	SetOnBrowserProcessGetDefaultRequestContextHandler(fn TOnBrowserProcessGetDefaultRequestContextHandlerEvent)
}

type IEngBrowserViewDelegate_127 interface {
	IEngBrowserViewDelegate
	SetOnBrowserViewGestureCommand(fn TOnBrowserViewGestureCommandEvent)
	SetOnBrowserViewGetBrowserRuntimeStyle(fn TOnBrowserViewGetBrowserRuntimeStyleEvent)
	SetOnBrowserViewUseFramelessWindowForPictureInPicture(fn TOnBrowserViewUseFramelessWindowForPictureInPictureEvent)
}

type IEngCommandHandler_127 interface {
	IEngCommandHandler
	SetOnCommandIsChromeAppMenuItemEnabled(fn TOnCommandIsChromeAppMenuItemEnabledEvent)
	SetOnCommandIsChromeAppMenuItemVisible(fn TOnCommandIsChromeAppMenuItemVisibleEvent)
	SetOnCommandIsChromePageActionIconVisible(fn TOnCommandIsChromePageActionIconVisibleEvent)
	SetOnCommandIsChromeToolbarButtonVisible(fn TOnCommandIsChromeToolbarButtonVisibleEvent)
}

type IEngExtensionHandler_127 interface {
	ICefExtensionHandlerOwn_127
	AsIntfExtensionHandler() uintptr
	SetOnExtensionBeforeBackgroundBrowser(fn TOnExtensionBeforeBackgroundBrowserEvent)
	SetOnExtensionBeforeBrowser(fn TOnExtensionBeforeBrowserEvent)
	SetOnExtensionCanAccessBrowser(fn TOnExtensionCanAccessBrowserEvent)
	SetOnExtensionExtensionLoadFailed(fn TOnExtensionExtensionLoadFailedEvent)
	SetOnExtensionExtensionLoaded(fn TOnExtensionExtensionLoadedEvent)
	SetOnExtensionExtensionUnloaded(fn TOnExtensionExtensionUnloadedEvent)
	SetOnExtensionGetActiveBrowser(fn TOnExtensionGetActiveBrowserEvent)
	SetOnExtensionGetExtensionResource(fn TOnExtensionGetExtensionResourceEvent)
}

type IEngLifeSpanHandler_127 interface {
	IEngLifeSpanHandler
	SetOnLifeSpanBeforeDevToolsPopup(fn TOnLifeSpanBeforeDevToolsPopupEvent)
}

type IEngMediaAccessHandler_127 interface {
	ICefMediaAccessHandlerOwn_127
	AsIntfMediaAccessHandler() uintptr
	SetOnMediaAccessRequestMediaAccessPermission(fn TOnMediaAccessRequestMediaAccessPermissionEvent)
}

type IEngRequestHandler_127 interface {
	IEngRequestHandler
	SetOnRequestRenderProcessResponsive(fn TOnRequestRenderProcessResponsiveEvent)
	SetOnRequestRenderProcessUnresponsive(fn TOnRequestRenderProcessUnresponsiveEvent)
}

type IEngViewDelegate_127 interface {
	IEngViewDelegate
	SetOnViewThemeChanged(fn TOnViewThemeChangedEvent)
}

type IEngWindowDelegate_127 interface {
	IEngWindowDelegate
	SetOnWindowAcceptsFirstMouse(fn TOnWindowAcceptsFirstMouseEvent)
	SetOnWindowGetTitlebarHeight(fn TOnWindowGetTitlebarHeightEvent)
	SetOnWindowGetWindowRuntimeStyle(fn TOnWindowGetWindowRuntimeStyleEvent)
	SetOnWindowIsWindowModalDialog(fn TOnWindowIsWindowModalDialogEvent)
	SetOnWindowThemeColorsChanged(fn TOnWindowThemeColorsChangedEvent)
	SetOnWindowWindowFullscreenTransition(fn TOnWindowWindowFullscreenTransitionEvent)
	SetOnWindowWithStandardWindowButtons(fn TOnWindowWithStandardWindowButtonsEvent)
}

type IPDFPrintOptions_127 interface {
	IPDFPrintOptions
	// GenerateDocumentOutline
	// Set to true to generate a document outline.
	GenerateDocumentOutline() bool
	// GenerateTaggedPDF
	// Set to true to generate tagged (accessible) PDF.
	GenerateTaggedPDF() bool
	SetGenerateDocumentOutline(value bool)
	SetGenerateTaggedPDF(value bool)
}
