// Code generated by cefgen. DO NOT EDIT.
//
//----------------------------------------
//
// Copyright © yanghy. All Rights Reserved.
//
// Licensed under Apache License 2.0
//
//----------------------------------------

package cef

type Raw = any

type IRaw interface {
	Raw() Raw
}

func RawAs[T any](value any) (T, bool) {
	var zero T
	raw, ok := value.(IRaw)
	if !ok {
		return zero, false
	}
	out, ok := raw.Raw().(T)
	if !ok {
		return zero, false
	}
	return out, true
}
